import Mathlib.Analysis.SpecialFunctions.Sqrt
import Erdos634.BaseBetaQuadCoord

/-!
# Base-β: the direction group lands in `V = ℚ + ℚ√−D`

Erdős #634.  `BaseBetaQuadCoord.lean` produced the two unit directions `ζ = e^{iα}`, `ξ = e^{iβ}`
of the base-β tile as coordinates over `ℚ(√−D)`, `D = 4f² − e²`.  Here they are embedded in `ℂ`
and the closure statement is proved:

* `V e f` — the subfield-shaped set `{x + y·i√D : x, y ∈ ℚ}` of `ℂ`;
* `emb_qmul` — the coordinate multiplication *is* multiplication in `ℂ`;
* `gamma_le_V` — the group `Γ = ⟨−1, ζ, ξ⟩` is contained in `V`, stated as: the submonoid of `ℂ`
  generated by `{−1, ζ, ζ⁻¹, ξ, ξ⁻¹}` lies in `V` (the conjugates *are* the inverses, by
  `zeta_mul_conj` / `xi_mul_conj`, so this submonoid is exactly `Γ`);
* `reach_mem` — a point reached from a point of `V` by adding integer multiples of `Γ`-directions
  stays in `V`.  This is the vertex-rationality step, *conditional on* the orientation hypothesis:
  it says nothing about which orientations a dissection can present.  See the report/PAPER_MAP note:
  H-ORIENT itself is **not** proved here and does not follow from `CongruentDissection`.

No `sorry`; no geometric hypothesis is used.
-/

namespace Erdos634.BaseBetaQuad

open Complex

/-- `√−D` as a complex number. -/
noncomputable def sD (e f : ℚ) : ℂ := Complex.I * (Real.sqrt ((Dq e f : ℚ) : ℝ) : ℂ)

/-- The embedding `(x,y) ↦ x + y√−D`. -/
noncomputable def emb (e f : ℚ) (z : ℚ × ℚ) : ℂ := (z.1 : ℂ) + (z.2 : ℂ) * sD e f

/-- `V = ℚ + ℚ√−D ⊆ ℂ`. -/
def V (e f : ℚ) : Set ℂ := Set.range (emb e f)

theorem sD_sq (e f : ℚ) (h : 0 ≤ Dq e f) : sD e f ^ 2 = -((Dq e f : ℚ) : ℂ) := by
  have hr : ((Real.sqrt ((Dq e f : ℚ) : ℝ) : ℝ) : ℂ) ^ 2 = ((Dq e f : ℚ) : ℂ) := by
    rw [← Complex.ofReal_pow, Real.sq_sqrt (by exact_mod_cast h)]
    norm_cast
  rw [sD, mul_pow, Complex.I_sq, hr]; ring

/-- **The coordinate product is the complex product.** -/
theorem emb_qmul (e f : ℚ) (h : 0 ≤ Dq e f) (z w : ℚ × ℚ) :
    emb e f (qmul e f z w) = emb e f z * emb e f w := by
  simp only [emb, qmul]
  push_cast
  linear_combination (-(z.2 : ℂ) * (w.2 : ℂ)) * sD_sq e f h

theorem V_mul (e f : ℚ) (h : 0 ≤ Dq e f) {u v : ℂ} (hu : u ∈ V e f) (hv : v ∈ V e f) :
    u * v ∈ V e f := by
  obtain ⟨z, rfl⟩ := hu; obtain ⟨w, rfl⟩ := hv
  exact ⟨qmul e f z w, emb_qmul e f h z w⟩

theorem V_add (e f : ℚ) {u v : ℂ} (hu : u ∈ V e f) (hv : v ∈ V e f) : u + v ∈ V e f := by
  obtain ⟨z, rfl⟩ := hu; obtain ⟨w, rfl⟩ := hv
  refine ⟨(z.1 + w.1, z.2 + w.2), ?_⟩
  simp only [emb]; push_cast; ring

theorem V_one (e f : ℚ) : (1 : ℂ) ∈ V e f := ⟨(1, 0), by simp [emb]⟩

theorem V_zero (e f : ℚ) : (0 : ℂ) ∈ V e f := ⟨(0, 0), by simp [emb]⟩

theorem V_neg (e f : ℚ) {u : ℂ} (hu : u ∈ V e f) : -u ∈ V e f := by
  obtain ⟨z, rfl⟩ := hu
  refine ⟨(-z.1, -z.2), ?_⟩
  simp only [emb]; push_cast; ring

theorem V_intMul (e f : ℚ) {u : ℂ} (n : ℤ) (hu : u ∈ V e f) : (n : ℂ) * u ∈ V e f := by
  obtain ⟨z, rfl⟩ := hu
  refine ⟨((n : ℚ) * z.1, (n : ℚ) * z.2), ?_⟩
  simp only [emb]; push_cast; ring

/-- `V` as a submonoid of `(ℂ, ·)`. -/
noncomputable def Vm (e f : ℚ) (h : 0 ≤ Dq e f) : Submonoid ℂ where
  carrier := V e f
  mul_mem' := V_mul e f h
  one_mem' := V_one e f

theorem zeta_mul_conj (e f : ℚ) (h : 0 ≤ Dq e f) (hf : f ≠ 0) :
    emb e f (zetaQ e f) * emb e f (qconj (zetaQ e f)) = 1 := by
  rw [← emb_qmul e f h, zetaQ_norm_one e f hf]; simp [emb]

theorem xi_mul_conj (e f : ℚ) (h : 0 ≤ Dq e f) (hf : f ≠ 0) :
    emb e f (xiQ e f) * emb e f (qconj (xiQ e f)) = 1 := by
  rw [← emb_qmul e f h, xiQ_norm_one e f hf]; simp [emb]

/-- The generating set of `Γ = ⟨−1, ζ, ξ⟩`, with inverses named explicitly. -/
noncomputable def gens (e f : ℚ) : Set ℂ :=
  {-1, emb e f (zetaQ e f), emb e f (qconj (zetaQ e f)),
    emb e f (xiQ e f), emb e f (qconj (xiQ e f))}

/-- **`Γ ⊆ V`.**  Every element of the direction group lies in `ℚ + ℚ√−D`. -/
theorem gamma_le_V (e f : ℚ) (h : 0 ≤ Dq e f) : Submonoid.closure (gens e f) ≤ Vm e f h := by
  rw [Submonoid.closure_le]
  rintro x (rfl | rfl | rfl | rfl | rfl)
  · exact V_neg e f (V_one e f)
  all_goals exact ⟨_, rfl⟩

/-- **The vertex-rationality step.**  Starting from a point of `V` and adding integer multiples of
`Γ`-directions, every point reached is in `V`. -/
theorem reach_mem (e f : ℚ) (h : 0 ≤ Dq e f) {p : ℂ} (hp : p ∈ V e f) (l : List ℂ)
    (hl : ∀ z ∈ l, ∃ (n : ℤ) (g : ℂ), g ∈ Submonoid.closure (gens e f) ∧ z = (n : ℂ) * g) :
    p + l.sum ∈ V e f := by
  induction l generalizing p with
  | nil => simpa using hp
  | cons a t ih =>
      obtain ⟨n, g, hg, rfl⟩ := hl a (by simp)
      have ha : (n : ℂ) * g ∈ V e f := V_intMul e f n (gamma_le_V e f h hg)
      have := ih (V_add e f hp ha) (fun z hz => hl z (by simp [hz]))
      simpa [List.sum_cons, add_assoc] using this

/-- **Non-vacuity witness.**  The standing hypotheses `0 ≤ Dq e f` and `f ≠ 0` are satisfiable:
`(e,f) = (1,2)` gives `D = 15`, the smallest member of the base-β family. -/
theorem witness_1_2 : (0 : ℚ) ≤ Dq 1 2 ∧ (2 : ℚ) ≠ 0 := by
  constructor
  · norm_num [Dq]
  · norm_num

end Erdos634.BaseBetaQuad
