-- ../../lean/CevianTiling28.lean — zero-axiom kernel verification of a tiling certificate (Erdos #634).
-- 28 copies of the tile [2, 3, 4] tile the target of ../../private/inst/cev28.txt, coordinates scaled by 8
-- into Z[sqrt15]. Kernel checks: (C1) squared side multiset [256, 576, 1024]; (C2) CCW + vertices in the
-- closed target (3 half-planes); (C3) an explicit separating edge-line per pair (378 pairs)
-- => disjoint interiors; (C4) signed 2-areas sum to the target's. Generated by rust/tiler
-- (`tiler cert`), which re-checks all four exactly in Z[sqrt15] before emitting. No imports,
-- no axioms.
namespace CevianTiling28
abbrev ZD := Int × Int
abbrev Pt := Int × Int × Int × Int
def zmul (u v : ZD) : ZD := (u.1*v.1 + 15*u.2*v.2, u.1*v.2 + u.2*v.1)
def zsub (u v : ZD) : ZD := (u.1 - v.1, u.2 - v.2)
def zadd (u v : ZD) : ZD := (u.1 + v.1, u.2 + v.2)
def znonneg (z : ZD) : Bool :=
  if 0 <= z.1 then (if 0 <= z.2 then true else 15*z.2*z.2 <= z.1*z.1)
  else (if z.2 < 0 then false else z.1*z.1 <= 15*z.2*z.2)
def znonpos (z : ZD) : Bool := znonneg (-z.1, -z.2)
def zpos (z : ZD) : Bool := !(znonpos z)
def px (p : Pt) : ZD := (p.1, p.2.1)
def py (p : Pt) : ZD := (p.2.2.1, p.2.2.2)
def cross (o a b : Pt) : ZD :=
  zsub (zmul (zsub (px a) (px o)) (zsub (py b) (py o))) (zmul (zsub (py a) (py o)) (zsub (px b) (px o)))
def dist2 (p q : Pt) : ZD :=
  zadd (zmul (zsub (px q) (px p)) (zsub (px q) (px p))) (zmul (zsub (py q) (py p)) (zsub (py q) (py p)))
abbrev Tri := Pt × Pt × Pt
def t1 (t : Tri) : Pt := t.1
def t2 (t : Tri) : Pt := t.2.1
def t3 (t : Tri) : Pt := t.2.2
def congOK (t : Tri) : Bool :=
  let d1 := dist2 (t1 t) (t2 t); let d2 := dist2 (t2 t) (t3 t); let d3 := dist2 (t3 t) (t1 t)
  let s : List ZD := [d1, d2, d3]
  s.contains ((256:Int),(0:Int)) && s.contains ((576:Int),(0:Int)) && s.contains ((1024:Int),(0:Int))
  && d1.2 == 0 && d2.2 == 0 && d3.2 == 0 && (d1.1 + d2.1 + d3.1 == 1856)
def q1 : Pt := (0,0,0,0)
def q2 : Pt := (112,0,0,0)
def q3 : Pt := (24,0,0,24)
def insideOK (t : Tri) : Bool :=
  zpos (cross (t1 t) (t2 t) (t3 t)) &&
  [t1 t, t2 t, t3 t].all (fun v => znonneg (cross q1 q2 v) && znonneg (cross q2 q3 v) && znonneg (cross q3 q1 v))
def sepBy (P Q : Pt) (A B : Tri) : Bool :=
  let sA := [t1 A, t2 A, t3 A].map (fun v => cross P Q v)
  let sB := [t1 B, t2 B, t3 B].map (fun v => cross P Q v)
  (sA.all znonneg && sB.all znonpos) || (sA.all znonpos && sB.all znonneg)
def edgeOf (t : Tri) (e : Nat) : Pt × Pt :=
  if e == 0 then (t1 t, t2 t) else if e == 1 then (t2 t, t3 t) else (t3 t, t1 t)
def area2 (t : Tri) : ZD := cross (t1 t) (t2 t) (t3 t)
def area2target : ZD := ((0:Int), (2688:Int))
def tiles : List Tri := [
  ((0,0,0,0), (32,0,0,0), (21,0,0,3)),
  ((0,0,0,0), (14,0,0,2), (8,0,0,8)),
  ((32,0,0,0), (64,0,0,0), (53,0,0,3)),
  ((32,0,0,0), (53,0,0,3), (21,0,0,3)),
  ((64,0,0,0), (96,0,0,0), (85,0,0,3)),
  ((64,0,0,0), (85,0,0,3), (53,0,0,3)),
  ((96,0,0,0), (112,0,0,0), (90,0,0,6)),
  ((96,0,0,0), (90,0,0,6), (74,0,0,6)),
  ((14,0,0,2), (28,0,0,4), (22,0,0,10)),
  ((14,0,0,2), (22,0,0,10), (8,0,0,8)),
  ((21,0,0,3), (53,0,0,3), (42,0,0,6)),
  ((53,0,0,3), (85,0,0,3), (74,0,0,6)),
  ((53,0,0,3), (74,0,0,6), (42,0,0,6)),
  ((28,0,0,4), (42,0,0,6), (36,0,0,12)),
  ((28,0,0,4), (36,0,0,12), (22,0,0,10)),
  ((42,0,0,6), (58,0,0,6), (36,0,0,12)),
  ((58,0,0,6), (90,0,0,6), (79,0,0,9)),
  ((58,0,0,6), (79,0,0,9), (47,0,0,9)),
  ((8,0,0,8), (22,0,0,10), (16,0,0,16)),
  ((47,0,0,9), (79,0,0,9), (68,0,0,12)),
  ((47,0,0,9), (68,0,0,12), (36,0,0,12)),
  ((22,0,0,10), (36,0,0,12), (30,0,0,18)),
  ((22,0,0,10), (30,0,0,18), (16,0,0,16)),
  ((36,0,0,12), (52,0,0,12), (30,0,0,18)),
  ((52,0,0,12), (68,0,0,12), (46,0,0,18)),
  ((52,0,0,12), (46,0,0,18), (30,0,0,18)),
  ((16,0,0,16), (30,0,0,18), (24,0,0,24)),
  ((30,0,0,18), (46,0,0,18), (24,0,0,24))
]
def wit : List (Bool × Nat) := [
  (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,0),
  (true,0), (true,0), (true,1), (true,1), (true,1), (true,0), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2),
  (true,2), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,2),
  (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,0), (true,0), (true,0), (false,0), (false,0),
  (true,1), (true,0), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,1), (true,1), (true,2), (true,1), (false,2), (false,2), (true,2), (true,2), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,0), (true,0), (true,0),
  (true,1), (true,1), (true,1), (true,0), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1),
  (true,0), (true,0), (true,0), (true,1), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,1), (true,2),
  (true,2), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (false,0), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,1), (true,1), (true,2), (true,1), (false,0), (false,0), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1), (true,0),
  (true,1), (true,2), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,1), (true,2), (true,1), (true,0),
  (true,0), (true,0), (true,1), (true,0), (true,0), (true,1), (true,1), (false,0), (true,0), (false,2), (true,1), (true,1),
  (true,1), (true,1), (true,2), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,1), (true,2), (true,1),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,0), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (false,0), (false,0), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1),
  (true,1), (true,2), (true,1), (true,0), (true,0), (true,0), (true,1), (false,0), (true,1), (true,1), (true,2), (true,1),
  (true,2), (true,2), (true,2), (false,0), (true,1), (true,1)
]
def pairSep (A B : Tri) (w : Bool × Nat) : Bool :=
  let pq := edgeOf (if w.1 then A else B) w.2
  sepBy pq.1 pq.2 A B
def checkPairs : List Tri → List (Bool × Nat) → Bool
  | [], ws => ws.isEmpty
  | t :: rest, ws =>
      let n := rest.length
      (ws.take n).length == n
      && (List.zip rest (ws.take n)).all (fun (u, w) => pairSep t u w)
      && checkPairs rest (ws.drop n)
def zsum (l : List ZD) : ZD := l.foldl zadd ((0:Int),(0:Int))
def checkAll : Bool :=
  tiles.length == 28 && tiles.all congOK && tiles.all insideOK
  && checkPairs tiles wit && zsum (tiles.map area2) == area2target
set_option maxRecDepth 32768 in
theorem ceviantiling28_certificate : checkAll = true := by decide
end CevianTiling28
