-- ../../lean/CevianTiling63.lean — zero-axiom kernel verification of a tiling certificate (Erdos #634).
-- 63 copies of the tile [2, 3, 4] tile the target of ../../private/inst/cev63.txt, coordinates scaled by 8
-- into Z[sqrt15]. Kernel checks: (C1) squared side multiset [256, 576, 1024]; (C2) CCW + vertices in the
-- closed target (3 half-planes); (C3) an explicit separating edge-line per pair (1953 pairs)
-- => disjoint interiors; (C4) signed 2-areas sum to the target's. Generated by rust/tiler
-- (`tiler cert`), which re-checks all four exactly in Z[sqrt15] before emitting. No imports,
-- no axioms.
namespace CevianTiling63
abbrev ZD := Int × Int
abbrev Pt := Int × Int × Int × Int
def zmul (u v : ZD) : ZD := (u.1*v.1 + 15*u.2*v.2, u.1*v.2 + u.2*v.1)
def zsub (u v : ZD) : ZD := (u.1 - v.1, u.2 - v.2)
def zadd (u v : ZD) : ZD := (u.1 + v.1, u.2 + v.2)
def znonneg (z : ZD) : Bool :=
  if 0 <= z.1 then (if 0 <= z.2 then true else 15*z.2*z.2 <= z.1*z.1)
  else (if z.2 < 0 then false else z.1*z.1 <= 15*z.2*z.2)
def znonpos (z : ZD) : Bool := znonneg (-z.1, -z.2)
def zpos (z : ZD) : Bool := !(znonpos z)
def px (p : Pt) : ZD := (p.1, p.2.1)
def py (p : Pt) : ZD := (p.2.2.1, p.2.2.2)
def cross (o a b : Pt) : ZD :=
  zsub (zmul (zsub (px a) (px o)) (zsub (py b) (py o))) (zmul (zsub (py a) (py o)) (zsub (px b) (px o)))
def dist2 (p q : Pt) : ZD :=
  zadd (zmul (zsub (px q) (px p)) (zsub (px q) (px p))) (zmul (zsub (py q) (py p)) (zsub (py q) (py p)))
abbrev Tri := Pt × Pt × Pt
def t1 (t : Tri) : Pt := t.1
def t2 (t : Tri) : Pt := t.2.1
def t3 (t : Tri) : Pt := t.2.2
def congOK (t : Tri) : Bool :=
  let d1 := dist2 (t1 t) (t2 t); let d2 := dist2 (t2 t) (t3 t); let d3 := dist2 (t3 t) (t1 t)
  let s : List ZD := [d1, d2, d3]
  s.contains ((256:Int),(0:Int)) && s.contains ((576:Int),(0:Int)) && s.contains ((1024:Int),(0:Int))
  && d1.2 == 0 && d2.2 == 0 && d3.2 == 0 && (d1.1 + d2.1 + d3.1 == 1856)
def q1 : Pt := (0,0,0,0)
def q2 : Pt := (168,0,0,0)
def q3 : Pt := (36,0,0,36)
def insideOK (t : Tri) : Bool :=
  zpos (cross (t1 t) (t2 t) (t3 t)) &&
  [t1 t, t2 t, t3 t].all (fun v => znonneg (cross q1 q2 v) && znonneg (cross q2 q3 v) && znonneg (cross q3 q1 v))
def sepBy (P Q : Pt) (A B : Tri) : Bool :=
  let sA := [t1 A, t2 A, t3 A].map (fun v => cross P Q v)
  let sB := [t1 B, t2 B, t3 B].map (fun v => cross P Q v)
  (sA.all znonneg && sB.all znonpos) || (sA.all znonpos && sB.all znonneg)
def edgeOf (t : Tri) (e : Nat) : Pt × Pt :=
  if e == 0 then (t1 t, t2 t) else if e == 1 then (t2 t, t3 t) else (t3 t, t1 t)
def area2 (t : Tri) : ZD := cross (t1 t) (t2 t) (t3 t)
def area2target : ZD := ((0:Int), (6048:Int))
def tiles : List Tri := [
  ((0,0,0,0), (24,0,0,0), (28,0,0,4)),
  ((0,0,0,0), (14,0,0,2), (8,0,0,8)),
  ((24,0,0,0), (48,0,0,0), (52,0,0,4)),
  ((24,0,0,0), (38,0,0,2), (32,0,0,8)),
  ((48,0,0,0), (72,0,0,0), (76,0,0,4)),
  ((48,0,0,0), (62,0,0,2), (56,0,0,8)),
  ((72,0,0,0), (104,0,0,0), (93,0,0,3)),
  ((72,0,0,0), (86,0,0,2), (80,0,0,8)),
  ((104,0,0,0), (136,0,0,0), (125,0,0,3)),
  ((104,0,0,0), (125,0,0,3), (93,0,0,3)),
  ((136,0,0,0), (168,0,0,0), (157,0,0,3)),
  ((136,0,0,0), (157,0,0,3), (125,0,0,3)),
  ((14,0,0,2), (28,0,0,4), (22,0,0,10)),
  ((14,0,0,2), (22,0,0,10), (8,0,0,8)),
  ((38,0,0,2), (52,0,0,4), (46,0,0,10)),
  ((38,0,0,2), (46,0,0,10), (32,0,0,8)),
  ((62,0,0,2), (76,0,0,4), (70,0,0,10)),
  ((62,0,0,2), (70,0,0,10), (56,0,0,8)),
  ((86,0,0,2), (100,0,0,4), (94,0,0,10)),
  ((86,0,0,2), (94,0,0,10), (80,0,0,8)),
  ((93,0,0,3), (125,0,0,3), (114,0,0,6)),
  ((125,0,0,3), (157,0,0,3), (146,0,0,6)),
  ((125,0,0,3), (146,0,0,6), (114,0,0,6)),
  ((28,0,0,4), (36,0,0,12), (22,0,0,10)),
  ((52,0,0,4), (60,0,0,12), (46,0,0,10)),
  ((76,0,0,4), (84,0,0,12), (70,0,0,10)),
  ((100,0,0,4), (114,0,0,6), (108,0,0,12)),
  ((100,0,0,4), (108,0,0,12), (94,0,0,10)),
  ((114,0,0,6), (130,0,0,6), (108,0,0,12)),
  ((130,0,0,6), (146,0,0,6), (124,0,0,12)),
  ((130,0,0,6), (124,0,0,12), (108,0,0,12)),
  ((8,0,0,8), (22,0,0,10), (16,0,0,16)),
  ((32,0,0,8), (46,0,0,10), (40,0,0,16)),
  ((56,0,0,8), (84,0,0,12), (60,0,0,12)),
  ((80,0,0,8), (94,0,0,10), (88,0,0,16)),
  ((22,0,0,10), (36,0,0,12), (30,0,0,18)),
  ((22,0,0,10), (30,0,0,18), (16,0,0,16)),
  ((46,0,0,10), (74,0,0,14), (50,0,0,14)),
  ((46,0,0,10), (54,0,0,18), (40,0,0,16)),
  ((94,0,0,10), (108,0,0,12), (102,0,0,18)),
  ((94,0,0,10), (102,0,0,18), (88,0,0,16)),
  ((36,0,0,12), (44,0,0,20), (30,0,0,18)),
  ((60,0,0,12), (84,0,0,12), (88,0,0,16)),
  ((108,0,0,12), (124,0,0,12), (102,0,0,18)),
  ((50,0,0,14), (74,0,0,14), (78,0,0,18)),
  ((50,0,0,14), (78,0,0,18), (54,0,0,18)),
  ((74,0,0,14), (102,0,0,18), (78,0,0,18)),
  ((16,0,0,16), (44,0,0,20), (20,0,0,20)),
  ((40,0,0,16), (54,0,0,18), (48,0,0,24)),
  ((54,0,0,18), (70,0,0,18), (48,0,0,24)),
  ((70,0,0,18), (102,0,0,18), (91,0,0,21)),
  ((70,0,0,18), (91,0,0,21), (59,0,0,21)),
  ((20,0,0,20), (44,0,0,20), (48,0,0,24)),
  ((20,0,0,20), (34,0,0,22), (28,0,0,28)),
  ((59,0,0,21), (91,0,0,21), (80,0,0,24)),
  ((59,0,0,21), (80,0,0,24), (48,0,0,24)),
  ((34,0,0,22), (48,0,0,24), (42,0,0,30)),
  ((34,0,0,22), (42,0,0,30), (28,0,0,28)),
  ((48,0,0,24), (64,0,0,24), (42,0,0,30)),
  ((64,0,0,24), (80,0,0,24), (58,0,0,30)),
  ((64,0,0,24), (58,0,0,30), (42,0,0,30)),
  ((28,0,0,28), (42,0,0,30), (36,0,0,36)),
  ((42,0,0,30), (58,0,0,30), (36,0,0,36))
]
def wit : List (Bool × Nat) := [
  (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2),
  (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,2), (true,2),
  (true,1), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1),
  (true,1), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,2), (true,2), (true,2), (true,1), (true,2),
  (true,2), (true,2), (true,0), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,1), (true,1), (true,1), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1),
  (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2),
  (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,2),
  (true,2), (true,2), (true,2), (true,1), (true,1), (true,2), (true,1), (true,1), (true,2), (true,2), (true,1), (true,2),
  (true,2), (true,2), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,0), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,2),
  (true,2), (true,1), (true,1), (true,1), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,2), (true,1),
  (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,2), (true,1), (true,1), (true,1), (true,2), (true,2),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,1), (true,2), (true,2), (true,2), (true,2),
  (true,1), (true,1), (true,2), (true,2), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,0), (true,1), (true,0), (true,0), (true,0), (true,0), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1),
  (true,1), (true,1), (true,0), (true,0), (true,0), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,2), (true,2), (true,1), (true,1), (true,2), (true,2), (false,0), (true,2), (true,1), (true,1), (true,2),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,1), (true,2), (true,2),
  (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,1), (true,2), (true,1), (true,2), (true,1), (true,1),
  (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1),
  (true,1), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2),
  (true,1), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,2), (true,1), (true,1), (true,2), (true,2),
  (true,1), (true,2), (true,2), (true,1), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,0), (true,0), (true,0), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,1), (true,1), (true,0), (true,0), (true,0), (true,2), (true,2), (true,2), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,1), (true,2), (true,2), (true,2), (true,2),
  (true,1), (true,1), (true,2), (true,2), (true,1), (true,2), (true,2), (true,1), (true,2), (true,2), (true,2), (true,1),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,2), (true,2), (true,2),
  (true,2), (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,2),
  (true,2), (true,1), (true,1), (true,1), (true,2), (true,1), (true,0), (true,0), (true,2), (true,2), (true,2), (true,2),
  (false,0), (false,0), (false,0), (false,0), (true,1), (true,0), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,1), (true,0), (true,0), (true,0), (true,0), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1),
  (true,0), (true,0), (true,0), (true,1), (true,0), (true,0), (true,0), (true,1), (true,1), (true,2), (true,1), (true,1),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,2), (true,1), (true,1), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,2), (true,2), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,2),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,0), (false,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,1), (true,1), (true,0), (true,0), (true,1), (true,1), (true,0), (true,1), (true,0), (true,0), (true,1), (true,0),
  (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,0), (true,0), (true,1), (true,1), (true,0),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,0),
  (true,0), (true,0), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2),
  (false,0), (true,1), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,2), (false,0), (true,1), (true,2),
  (true,2), (true,1), (true,2), (true,2), (true,2), (true,1), (true,1), (true,2), (true,2), (true,1), (true,2), (true,2),
  (true,2), (true,2), (true,1), (true,2), (true,2), (true,2), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1),
  (false,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,0), (true,1),
  (true,1), (true,1), (true,1), (true,0), (true,0), (true,1), (true,1), (true,0), (true,1), (true,1), (true,0), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,2), (true,0), (true,0), (true,0), (true,2), (true,2), (true,2), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1),
  (true,1), (true,2), (true,2), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,0),
  (true,0), (true,0), (true,1), (true,1), (false,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,1), (true,1), (true,1), (true,0), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1),
  (true,1), (true,2), (true,2), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,1), (true,2), (true,1),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (false,0), (false,0), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,0), (true,1), (true,0), (true,0), (true,0), (true,1), (true,1), (true,0), (true,0),
  (true,0), (true,0), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,0), (true,0), (true,0),
  (true,0), (true,1), (true,1), (true,0), (true,0), (true,1), (true,1), (true,1), (true,0), (true,1), (true,1), (true,1),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,0), (true,0), (true,1), (true,1),
  (true,1), (true,1), (true,0), (true,0), (true,1), (true,0), (true,0), (true,1), (true,1), (true,0), (true,1), (true,1),
  (true,1), (true,0), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,0), (true,1),
  (true,1), (true,1), (true,1), (true,0), (true,0), (true,1), (true,1), (true,0), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (false,0), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,2), (true,1),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (false,0), (false,0), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,0), (true,1), (true,1), (true,0), (true,1),
  (true,0), (true,0), (true,1), (true,0), (true,0), (true,0), (true,1), (true,0), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,0), (true,0), (true,2), (true,2), (true,1), (true,1), (true,0), (true,0), (true,2), (true,0), (true,0), (true,1),
  (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (false,2), (true,2), (true,2), (false,0), (true,2), (false,2),
  (false,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2),
  (true,2), (true,2), (true,2), (true,1), (true,1), (true,2), (true,2), (true,1), (true,2), (true,2), (false,0), (true,2),
  (true,2), (true,2), (false,0), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,0), (true,1), (true,0), (true,0), (true,1), (true,0), (true,0), (true,0),
  (true,1), (true,0), (false,0), (true,1), (true,1), (true,1), (true,1), (false,0), (true,2), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,0), (true,1), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,0),
  (true,0), (true,0), (true,1), (true,0), (true,0), (true,0), (true,1), (true,1), (true,2), (true,0), (true,0), (true,2),
  (true,0), (true,0), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,0), (false,0),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (false,0), (true,0), (true,0), (true,1), (true,1),
  (true,0), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2),
  (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,2), (true,0), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1),
  (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,0), (true,0), (true,1), (true,1), (true,1), (true,0),
  (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,2), (true,2), (true,2), (false,0),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,0), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (false,2), (false,2), (true,0),
  (true,0), (true,1), (true,1), (true,0), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,0), (true,1), (true,2), (true,2), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,1),
  (true,2), (true,1), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1), (true,2), (true,2), (true,1), (true,1),
  (true,1), (true,2), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,2), (true,1), (true,1), (true,2), (true,2), (false,0), (true,1), (false,2), (true,2), (true,2),
  (true,0), (true,0), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (false,0), (false,0), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,2), (true,1), (true,1), (true,1), (true,2), (true,1), (true,0), (true,0), (true,0), (true,1), (false,0), (true,1),
  (true,1), (true,2), (true,1), (true,2), (true,2), (true,2), (false,0), (true,1), (true,1)
]
def pairSep (A B : Tri) (w : Bool × Nat) : Bool :=
  let pq := edgeOf (if w.1 then A else B) w.2
  sepBy pq.1 pq.2 A B
def checkPairs : List Tri → List (Bool × Nat) → Bool
  | [], ws => ws.isEmpty
  | t :: rest, ws =>
      let n := rest.length
      (ws.take n).length == n
      && (List.zip rest (ws.take n)).all (fun (u, w) => pairSep t u w)
      && checkPairs rest (ws.drop n)
def zsum (l : List ZD) : ZD := l.foldl zadd ((0:Int),(0:Int))
def checkAll : Bool :=
  tiles.length == 63 && tiles.all congOK && tiles.all insideOK
  && checkPairs tiles wit && zsum (tiles.map area2) == area2target
set_option maxRecDepth 8192 in
set_option maxHeartbeats 0 in
theorem ceviantiling63_certificate : checkAll = true := by decide
end CevianTiling63
