import Mathlib.Tactic

/-!
# The base-`β` direction invariant: factorisation of the tile polynomial

Erdős #634, base-`β` branch.  A tiling of the isosceles target by the tile
`(a,b,c) = (ef, f²−e², f²)` gives, for every `λ`, an identity between a boundary value and a sum
over tiles of `i^J λ^K` times one of two "tile polynomials".  After clearing `λ^{-3}` the identity
reads

    R(λ) = λ³ · P(λ) · A(λ) + Q(λ) · B(λ)      in  ℤ[i][λ, λ⁻¹]

with

    P(λ) = i·e·f·λ³ − b·λ² + f²            (unreflected tiles)
    Q(λ) = f²·λ³ − b·λ − i·e·f             (reflected tiles, = λ³ · V₋(λ))
    R(λ) = i·m·f³·λ⁶ + e·m·N₀·λ³ − i·m·f³   (the boundary of the target; S = f³m)

where `b = f² − e²` and `N₀ = 3f² − e²`.

This file proves the three algebraic facts that reduce that identity to its essential form.
Everything is a polynomial identity, so it is stated over an arbitrary commutative ring `R` with a
designated element `I` satisfying `I² = −1`; no field, no analysis, no geometry.

* `P_factor`  :  `P = I · G * (e·λ + I·f)`
* `Q_factor`  :  `Q = G * (f·λ + I·e)`
* `R_factor`  :  `R = G * H`

with the *shared* primitive quadratic factor and the cofactor

    G(λ) = f·λ² − I·e·λ − f
    H(λ) = m·(I·f²·λ⁴ − e·f·λ³ + I·b·λ² + e·f·λ + I·f²).

**Consequence.**  `G` is a nonzerodivisor in `R[λ]` when `R` is a domain and `f ≠ 0`, so the tiling
identity is equivalent to

    H(λ) = I·λ³·(e·λ + I·f)·A(λ) + (f·λ + I·e)·B(λ),

which is the form in which the combinatorial constraints on `A` and `B` are read off.  Note the two
surviving generators are *linear*: all the degree of the problem sits in `G`, which cancels.

**A negative worth recording.**  The ideal `(e·λ + I·f, f·λ + I·e)` contains
`f·(e·λ + I·f) − e·(f·λ + I·e) = I·(f² − e²) = I·b`, and modulo `b` one has `f² ≡ e²`, so
`λ₀ = −I·f/e` satisfies `λ₀² ≡ −1`; evaluating `H` there gives exactly `m·I·(e² − f²) = −m·I·b`.
So `H` always lies in that ideal: the identity carries **no** ideal-theoretic obstruction.  Any
exclusion must come from the combinatorial constraint that `A` and `B` are sums of `N` monomials
with unit coefficients, not from divisibility.  `ideal_membership_is_automatic` below records the
computational core of that observation.

Axiom-clean.
-/

namespace Erdos634.LambdaFactor

variable {R : Type*} [CommRing R]

/-- The shared quadratic factor `G(λ) = f·λ² − I·e·λ − f`. -/
def G (I e f lam : R) : R := f * lam ^ 2 - I * e * lam - f

/-- **The unreflected tile polynomial factors.**  `P = I·G·(e·λ + I·f)`, using `I² = −1`.

The three roots of `P` are therefore the two roots of `G` — which are `ω = e^{iα/2}` and its Galois
conjugate, both of modulus one — together with `−I·f/e`, which lies in `ℚ(i)`.  It is that third,
*rational* root that makes the one-sided evaluation possible: at `λ = −I·f/e` the unreflected tiles
contribute nothing at all. -/
theorem P_factor (I e f lam : R) (hI : I ^ 2 = -1) :
    I * e * f * lam ^ 3 - (f ^ 2 - e ^ 2) * lam ^ 2 + f ^ 2
      = I * G I e f lam * (e * lam + I * f) := by
  unfold G
  linear_combination (f ^ 2 - (f ^ 2 - e ^ 2) * lam ^ 2 + I * e * f * lam) * hI

/-- **The reflected tile polynomial factors**, with the *same* quadratic `G`:
`Q = G·(f·λ + I·e)`.  Its third root is `−I·e/f`. -/
theorem Q_factor (I e f lam : R) (hI : I ^ 2 = -1) :
    f ^ 2 * lam ^ 3 - (f ^ 2 - e ^ 2) * lam - I * e * f
      = G I e f lam * (f * lam + I * e) := by
  unfold G
  linear_combination (e ^ 2 * lam) * hI

/-- **The boundary polynomial is divisible by the same `G`.**

`R = G · H`, where `H = m·(I·f²·λ⁴ − e·f·λ³ + I·b·λ² + e·f·λ + I·f²)`.  Here `R` is the boundary
value of the invariant on the target triangle, cleared of `λ⁻³`:

    R(λ) = I·m·f³·λ⁶ + e·m·(3f² − e²)·λ³ − I·m·f³

(the target's equal side is `S = f³·m`, so the outer coefficients are `f³`, not `f²`).

This is the step that makes the whole reduction work.  It is *not* a coincidence: `G`'s roots are
`ω` and its conjugate, and the boundary value must vanish at `ω` because both tile polynomials do —
the geometric statement `2f³·sin(3α/2) = e·(3f² − e²)` is exactly `R(ω) = 0`. -/
theorem R_factor (I e f m lam : R) (hI : I ^ 2 = -1) :
    I * m * f ^ 3 * lam ^ 6 + e * m * (3 * f ^ 2 - e ^ 2) * lam ^ 3 - I * m * f ^ 3
      = G I e f lam *
          (m * (I * f ^ 2 * lam ^ 4 - e * f * lam ^ 3 + I * (f ^ 2 - e ^ 2) * lam ^ 2
                + e * f * lam + I * f ^ 2)) := by
  unfold G
  linear_combination (m * e * ((f ^ 2 - e ^ 2) * lam ^ 3 + f ^ 2 * lam ^ 5 + f ^ 2 * lam)) * hI

/-- The cofactor `H`. -/
def H (I e f m lam : R) : R :=
  m * (I * f ^ 2 * lam ^ 4 - e * f * lam ^ 3 + I * (f ^ 2 - e ^ 2) * lam ^ 2
       + e * f * lam + I * f ^ 2)

/-- **The two surviving generators are linear, and their `ℤ[i]`-combination produces `b`.**

`f·(e·λ + I·f) − e·(f·λ + I·e) = I·(f² − e²) = I·b`.  So the ideal generated by the two linear
forms contains `b`, and (since `gcd(e,b) = 1`) equals `(b, e·λ + I·f)`. -/
theorem b_in_ideal (I e f lam : R) :
    f * (e * lam + I * f) - e * (f * lam + I * e) = I * (f ^ 2 - e ^ 2) := by ring

/-- **Ideal membership is automatic — the negative result.**

Work modulo `b = f² − e²`, where `f² ≡ e²`.  Substituting the root `λ₀` of `e·λ + I·f` (which
exists modulo `b` because `gcd(e, b) = 1`) into `H` leaves exactly `−m·I·b`, a multiple of `b`.
This identity is the computational core: for any `λ₀` with `e·λ₀ + I·f = 0` and `λ₀² = −1`, the
value `H(λ₀)` is `−m·I·(f² − e²)`, hence divisible by `f² − e²`.  (Modulo `b` the hypothesis
`λ₀² = −1` is automatic, since `λ₀ = −I·f/e` and `f² ≡ e² (mod b)`.)

Consequently the `λ`-family imposes **no** divisibility condition on `(e,f,m)`: every arithmetic
consequence of the identity is satisfied identically.  Exclusions must come from the combinatorial
side — that `A` and `B` are sums of exactly `N` monomials with unit coefficients. -/
theorem ideal_membership_is_automatic (I e f m lam : R)
    (hroot : e * lam + I * f = 0) (hsq : lam ^ 2 = -1) :
    H I e f m lam = -(m * I * (f ^ 2 - e ^ 2)) := by
  unfold H
  have h4 : lam ^ 4 = 1 := by
    have h : lam ^ 4 = (lam ^ 2) ^ 2 := by ring
    rw [h, hsq]; norm_num
  have h3 : lam ^ 3 = -lam := by
    have h : lam ^ 3 = lam ^ 2 * lam := by ring
    rw [h, hsq]; ring
  have hel : e * lam = -(I * f) := by linear_combination hroot
  rw [h4, h3, hsq]
  linear_combination (2 * m * f) * hel

#print axioms Erdos634.LambdaFactor.P_factor
#print axioms Erdos634.LambdaFactor.Q_factor
#print axioms Erdos634.LambdaFactor.R_factor
#print axioms Erdos634.LambdaFactor.b_in_ideal
#print axioms Erdos634.LambdaFactor.ideal_membership_is_automatic

/-!
## The metric class cannot close a base-`β` candidate

The identity `V₊·A + V₋·B = W` constrains `A, B` only through `‖A‖₁ + ‖B‖₁ ≤ N`, since each
Laurent coefficient is a sum of `n_K` fourth roots of unity.  An exact linear-programming duality
computation (primal = dual, verified on all 171 triples with `2 ≤ f ≤ 13`, `m ≤ 3`) gives the
optimal lower bound

    ‖A‖₁ + ‖B‖₁  ≥  m·(3f − 2e)·(f + e)/f,

attained by the genuine 44-tiling.  So *any* bound in this class — any `λ`, any kernel, any moment
ladder, any Riesz product, any `Lᵖ` duality — fires only if `N` is below that optimum, i.e. only if

    m·f·(3f² − e²)  <  (3f − 2e)·(f + e).

`metric_class_never_fires` shows the opposite inequality holds always, with a factor `11/6` to
spare, so no member of the class can ever exclude a base-`β` candidate.  Equality in the `11/6`
bound occurs exactly at `(e,f,m) = (1,2,1)`.

This is a *negative* result, and it is the point: it closes the entire signed-direction /
colouring-invariant programme for this branch, strengthening the paper's own `rem:nogo` (which
shows the identity is solvable ignoring size) to the size-constrained problem.
-/

/-- **No metric bound in the invariant class can exclude a base-`β` candidate.**

For all integers `1 ≤ e < f` and `1 ≤ m`,

    6·m·f·(3f² − e²)  ≥  11·(3f − 2e)·(f + e),

so `m·f·(3f² − e²) / ((3f − 2e)(f + e)) ≥ 11/6 > 1` and the contradiction the metric route needs —
namely that this ratio be `< 1` — never occurs.  Equality holds exactly at `(e,f,m) = (1,2,1)`. -/
theorem metric_class_never_fires (e f m : ℤ) (he : 1 ≤ e) (hef : e < f) (hm : 1 ≤ m) :
    11 * ((3 * f - 2 * e) * (f + e)) ≤ 6 * (m * f * (3 * f ^ 2 - e ^ 2)) := by
  have ht : 1 ≤ f - e := by omega
  -- the m = 1 case, after f = e + t
  have base : 11 * ((3 * f - 2 * e) * (f + e)) ≤ 6 * (f * (3 * f ^ 2 - e ^ 2)) := by
    nlinarith [sq_nonneg (f - e - 1), sq_nonneg (e - 1), sq_nonneg (f - e),
      mul_nonneg (sub_nonneg.mpr he) (sub_nonneg.mpr ht),
      mul_nonneg (mul_nonneg (sub_nonneg.mpr he) (sub_nonneg.mpr he)) (sub_nonneg.mpr ht),
      mul_nonneg (mul_nonneg (sub_nonneg.mpr ht) (sub_nonneg.mpr ht)) (sub_nonneg.mpr he),
      mul_nonneg (mul_nonneg (sub_nonneg.mpr ht) (sub_nonneg.mpr ht)) (sub_nonneg.mpr ht)]
  -- and m ≥ 1 only helps, since f·(3f² − e²) > 0
  have hpos : 0 < f * (3 * f ^ 2 - e ^ 2) := by nlinarith
  nlinarith [mul_le_mul_of_nonneg_right hm (le_of_lt hpos)]

end Erdos634.LambdaFactor

#print axioms Erdos634.LambdaFactor.metric_class_never_fires
