import Erdos634.LemmaPTree
import Erdos634.LemmaPNode2

/-!
# Lemma P, composed: no congruent dissection of the `(2,3)` base-β target by `(6,5,9)` has base
# word beginning `a c b`

Erdős #634, `N = 23`.  `LemmaPTree.node_0` (generated by `gen_tree.py`, every node a theorem) is
restated here in the corpus's own objects — `ThickBlockingLemmas.target63` and `w1t0` — and the
base-word hypothesis is spelled out.

## The statement

`lemmaP_no_dissection`: for any `CongruentDissection` `D` whose target carrier is
`target63.carrier` and whose model is congruent to `w1t0` (the `(6,5,9)` tile), if `D` has three
tiles with base edges `[0,6]`, `[6,15]`, `[15,20]` on `y = 0` (`HasBaseEdge`, i.e. the base word
begins `a c b`), then `False`.

**What "the base word begins `a c b`" is here**: the predicate `LemmaPTree.BaseWordHyp` — the
existence of tiles with those three base edges.  This is the base-word predicate the tree's
base-word kills consume (`CertNode.base_edge_clash`); it is not derived from
`CornerBaseEdgesReal` (which gives the *corner* tile's base edge as `a` or `c` but no block
lengths beyond it), so the hypothesis is stated, not derived.

## Trust base

`placement_completeness`, `six_placements` (proved `Dissection`-level theorems), `CertNode.lean`
(the per-kill soundness lemmas), and per node the generated linear arithmetic.  Nothing about the
constructor; no search in the trust base.  `#print axioms`: the standard three.

## Non-vacuity

`LemmaPTree.T*_sides`, `T*_inside`, `node_*_config`: every node's placed tiles are congruent to
the model, inside the target, with pairwise disjoint interiors — the node hypotheses describe
real partial configurations.  `baseword_hyp_config`: the base-word hypothesis itself is realised
by the three-tile configuration of node 4.

Axiom-clean; no `sorry`.
-/

namespace Erdos634.LemmaPTheorem

open Erdos634.Geometry Erdos634.CertCoord Erdos634.CertNode Erdos634.LemmaPTree
  Erdos634.ThickBlockingLemmas

theorem sr32_eq_rr : sr 32 = rr := rfl

/-- The generated target is the corpus's `target63`. -/
theorem TGT_carrier_eq : TGT.carrier = target63.carrier := by
  have hpts : TGT.pts = target63.pts := by
    funext k
    fin_cases k
    · show mkPt 0 (0 * sr 32) = mkPt 0 0
      simp
    · show mkPt 46 (0 * sr 32) = mkPt 46 0
      simp
    · show mkPt 23 (5 / 2 * sr 32) = mkPt 23 (5 / 2 * rr)
      rfl
  unfold Tri.carrier
  rw [hpts]

/-- The generated model is the corpus's `w1t0`. -/
theorem MODEL_eq_w1t0 : MODEL = w1t0 := by
  have hpts : MODEL.pts = w1t0.pts := by
    funext k
    fin_cases k
    · show mkPt 0 (0 * sr 32) = mkPt 0 0
      simp
    · show mkPt 6 (0 * sr 32) = mkPt 6 0
      simp
    · show mkPt (23 / 3) (5 / 6 * sr 32) = mkPt (23 / 3) (5 / 6 * rr)
      rfl
  unfold MODEL w1t0 rtri mkTri
  congr 1

/-- **LEMMA P.**  No congruent dissection of the `(2,3)` base-β target by copies of `(6,5,9)` has
three tiles with base edges `[0,6]`, `[6,15]`, `[15,20]` — i.e. none has base word beginning
`a c b`. -/
theorem lemmaP_no_dissection {N : ℕ} (D : CongruentDissection N)
    (htarget : D.target.carrier = target63.carrier)
    (hmodel : D.model.Congruent w1t0)
    (hbase : (∃ i, HasBaseEdge D.toDissection i 0 6) ∧ (∃ i, HasBaseEdge D.toDissection i 6 15) ∧
      (∃ i, HasBaseEdge D.toDissection i 15 20)) : False :=
  node_0 D (htarget.trans TGT_carrier_eq.symm) (MODEL_eq_w1t0 ▸ hmodel) hbase

/-- **Non-vacuity of the base-word hypothesis**: the four tiles of node 4 (`T0, T1, T2, T5`) are
congruent to the model, inside the target, pairwise interior-disjoint, and realise the three base
edges `[0,6]`, `[6,15]`, `[15,20]`. -/
theorem baseword_hyp_config :
    T0.carrier ⊆ TGT.carrier ∧ T1.carrier ⊆ TGT.carrier ∧ T5.carrier ⊆ TGT.carrier ∧
    Disjoint (interior T0.carrier) (interior T1.carrier) ∧
    Disjoint (interior T1.carrier) (interior T5.carrier) ∧
    Disjoint (interior T0.carrier) (interior T5.carrier) ∧
    T0.pts 0 = mkPt 0 0 ∧ T0.pts 1 = mkPt 6 0 ∧
    T1.pts 0 = mkPt 6 0 ∧ T1.pts 1 = mkPt 15 0 ∧
    T5.pts 0 = mkPt 15 0 ∧ T5.pts 1 = mkPt 20 0 := by
  obtain ⟨d01, d02, d03, d12, d13, d23⟩ := node_5_config
  refine ⟨T0_inside, T1_inside, T5_inside, d01, d13, d03, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;>
    simp [T0, T1, T5, rtri, mkTri_pts, rp]

/-- `node2_jam` (hand-written, 2026-09-12) is subsumed: node 12 of the generated tree is the same
configuration, `w1t0, w1t1`. -/
theorem node2_jam_again {N : ℕ} (D : CongruentDissection N)
    (htarget : D.target.carrier = target63.carrier) (hmodel : D.model.Congruent w1t0)
    (hbase : (∃ i, HasBaseEdge D.toDissection i 0 6) ∧ (∃ i, HasBaseEdge D.toDissection i 6 15) ∧
      (∃ i, HasBaseEdge D.toDissection i 15 20))
    (i₀ i₁ : Fin N) (h₀ : D.tile i₀ = w1t0) (h₁ : D.tile i₁ = w1t1) : False :=
  lemmaP_no_dissection D htarget hmodel hbase

end Erdos634.LemmaPTheorem

#print axioms Erdos634.LemmaPTheorem.lemmaP_no_dissection
#print axioms Erdos634.LemmaPTheorem.baseword_hyp_config
