import Mathlib.Tactic

/-!
# Sufficiency calculus: ladder, cevian split, relation lattice, seed arithmetic

Erdős #634, construction side.  This file holds the arithmetic cores of the sufficiency
(realizability) program, with the geometric input isolated into named statements in the doc
comments, the interface discipline of `WallStraddle.lean` and `Collar.lean`.

Throughout, the base-`β` tile is `(a,b,c) = (ef, f²−e², f²)` with `gcd(e,f) = 1`, `1 ≤ e < f`;
the target `Δ_m` has base `Y = e·m·N₁`, equal sides `X = f³·m`, count `N = m²N₁`, `N₁ = 3f²−e²`.

* `ladder_cells` — the standard `k`-subdivision census behind the **universal** closure
  `N realizable ⟹ k²N realizable`, valid in every branch (paper, Theorem `thm:ladder`).
* `cevian_*`, `two_tiles_plus_atom` — the cevian split `Δ_m = (fm)-scaled tile ⊔ W_m` and
  `W_m = (fm)-scaled tile ⊔ atom(m)`: sufficiency per member reduces to the **atom spectrum**.
* `rel_*` — the relation lattice `Λ(e,f) = {n ∈ ℤ³ : n·(a,b,c) = 0} = ⟨(f,0,−e), (e,f,−f)⟩`,
  and hence the **interface floor**: distinct two-sided words need length `≥ f·min(a,b)`.
* `base_b_census`, `side_census` — the boundary-word residues at every multiplier `m`.
* `atom_base_forced`, `corner_fill_unique` — the unit atom's base word is `bᵉ`; at `e = 1` the
  single `b`-edge overflows a base corner, so the unit atom admits no tiling.
* `add_count`, `pgram_cols`, `pgram_cell_count` — the **addition law**
  `m₁, m₂ ∈ S(e,f), f ∣ m₁ ⟹ m₁+m₂ ∈ S(e,f)` (no divisibility needed at `e = 1`).

Axiom-clean.
-/

namespace Erdos634.Primitives

/-! ## The universal ladder

**Theorem (`thm:ladder`, paper; geometric).**  If a triangle `T` is cut into `N` congruent copies
of a tile `t`, then `kT` is cut into `k²N` copies of `t`, for every `k ≥ 1` — in every branch,
for every shape: subdivide `kT` by the triangular grid of side `k` into `k(k+1)/2` translates and
`k(k−1)/2` half-turns of `T`, and tile each.  A half-turned tiling is a tiling by the half-turned
tile, which is congruent to `t`.  The census below is the whole arithmetic content. -/

/-- **The `k`-subdivision census.**  `k(k+1)/2` up-cells and `k(k−1)/2` down-cells make `k²`:
in the denominator-free form, `k(k+1) + k(k−1) = 2k²`. -/
theorem ladder_cells (k : ℤ) : k * (k + 1) + k * (k - 1) = 2 * k ^ 2 := by ring

/-- Ladder instances used by the `N ≤ 200` spectrum table: `112 = 2²·28`, `176 = 2²·44`,
and the two counts settled by the collar theorem at `(1,2)`: `275 = 5²·11`, `539 = 7²·11`. -/
theorem ladder_instances :
    (2:ℤ) ^ 2 * 28 = 112 ∧ (2:ℤ) ^ 2 * 44 = 176 ∧
    (5:ℤ) ^ 2 * 11 = 275 ∧ (7:ℤ) ^ 2 * 11 = 539 := by norm_num

/-! ## The cevian split

The cevian from the apex to the base point at distance `e·c·m` from the east corner cuts `Δ_m`
into two pieces (certified instances at `(1,2)`: `CevianTiling28.lean` = the west piece of `Δ₂`,
`CevianTiling63.lean` = of `Δ₃`).  The east piece has sides `(ef²m, fbm, f³m) = (fm)·(a,b,c)`:
it **is the tile at scale `fm`**, hence carries a tiling by `(fm)²` copies for every `m`.  The
west piece `W_m` (sides `e(2f²−e²)m`, `f³m`, `fbm`; angles `β`, `2α`, `α+β`) splits again along
the wall from `(fam, 0)` to the apex into the `(fm)`-scaled tile and the **atom** — the isosceles
triangle with legs `fbm`, base `ebm`, apex angle `α`.  Consequently

  `Δ_m  =  (fm)-scaled tile  ⊔  (fm)-scaled tile  ⊔  atom(m)`,

and realizability at multiplier `m` follows from a tiling of the atom at scale `m` alone. -/

/-- The cevian splits the base: `e·N₁·m = e(2f²−e²)m + e·f²·m`. -/
theorem cevian_base (e f m : ℤ) :
    e * (3 * f ^ 2 - e ^ 2) * m = e * (2 * f ^ 2 - e ^ 2) * m + e * f ^ 2 * m := by ring

/-- The east piece's three sides are `(a, b, c)` scaled by `fm`: it is the tile at scale `fm`. -/
theorem cevian_east_scaled (e f m : ℤ) :
    e * f ^ 2 * m = (e * f) * (f * m) ∧
    f * (f ^ 2 - e ^ 2) * m = (f ^ 2 - e ^ 2) * (f * m) ∧
    f ^ 3 * m = f ^ 2 * (f * m) :=
  ⟨by ring, by ring, by ring⟩

/-- Counts across the cevian: `m²N₁ = m²(2f²−e²) + (fm)²`. -/
theorem cevian_count (e f m : ℤ) :
    m ^ 2 * (3 * f ^ 2 - e ^ 2) = m ^ 2 * (2 * f ^ 2 - e ^ 2) + (f * m) ^ 2 := by ring

/-- The west piece splits into the `(fm)`-scaled tile and the atom: `m²(2f²−e²) = (fm)² + bm²`. -/
theorem west_split (e f m : ℤ) :
    m ^ 2 * (2 * f ^ 2 - e ^ 2) = (f * m) ^ 2 + (f ^ 2 - e ^ 2) * m ^ 2 := by ring

/-- **The whole target is two scaled tiles plus one atom**: `m²N₁ = 2(fm)² + bm²`. -/
theorem two_tiles_plus_atom (e f m : ℤ) :
    m ^ 2 * (3 * f ^ 2 - e ^ 2) = 2 * (f * m) ^ 2 + (f ^ 2 - e ^ 2) * m ^ 2 := by ring

/-! ## The relation lattice

A maximal straight segment inside a tiling carries a word of whole tile edges on each side; the
two words have equal length, so their multiset difference `n = (n_a, n_b, n_c) ∈ ℤ³` satisfies
`n_a·a + n_b·b + n_c·c = 0`.  The lattice of such relations is generated by
`v₁ = (f, 0, −e)` (`f` a-edges = `e` c-edges, length `ef²`) and `v₂ = (e, f, −f)`
(`e` a's + `f` b's = `f` c's, length `f³`): `rel_b_mult` shows `f ∣ n_b`, and `rel_param` that a
`b`-free relation is a multiple of `v₁`.  Any nonzero relation therefore has one-sided length at
least `f·min(a,b)` — `n_b ≠ 0` forces `≥ f` b's on a side, `n_b = 0` forces a multiple of `v₁` —
so **every interface shorter than `f·min(a,b)` carries the same word on both sides**.

The eight kernel-certified `(1,2)`-family tilings (`Tiling44` = `N44B`, `N44C`, `Tiling99`,
`PgramTiling22`, `CevianTiling28/63`, `Tiling28`, `Tiling77`) were swept exactly: every interface
equation they use — `c = 2a`, `2b = 3a`, `2b = a+c`, `3c = 4b`, `a+2b = 2c` — is a relation whose
value at general `(e,f)` factors as `(unit)·(f−2e)·(positive)`.  All of them vanish exactly on
`f = 2e`, i.e. on the member `(1,2)` and nowhere else: **the certified seed complexes are
`(1,2)`-degenerate and transfer to no other member.**  (Sweep: `code/interface_census.py`.) -/

/-- `v₁ = (f, 0, −e)` is a relation: `f·a − e·c = 0`. -/
theorem rel_v1 (e f : ℤ) : f * (e * f) - e * f ^ 2 = 0 := by ring

/-- `v₂ = (e, f, −f)` is a relation: `e·a + f·b − f·c = 0`. -/
theorem rel_v2 (e f : ℤ) : e * (e * f) + f * (f ^ 2 - e ^ 2) - f * f ^ 2 = 0 := by ring

/-- Any relation has `f ∣ n_b·e²`: reducing `n_a·a + n_b·b + n_c·c = 0` mod `f`. -/
theorem rel_b_mod_f (x y z e f : ℤ)
    (h : x * (e * f) + y * (f ^ 2 - e ^ 2) + z * f ^ 2 = 0) :
    f ∣ y * e ^ 2 :=
  ⟨x * e + y * f + z * f, by linear_combination -h⟩

/-- With `gcd(e,f) = 1`: `f ∣ n_b` on every relation. -/
theorem rel_b_mult (x y z e f : ℤ) (hc : IsCoprime f e)
    (h : x * (e * f) + y * (f ^ 2 - e ^ 2) + z * f ^ 2 = 0) :
    f ∣ y :=
  (hc.pow_right (n := 2)).dvd_of_dvd_mul_right (rel_b_mod_f x y z e f h)

/-- A `b`-free relation is a multiple of `v₁`: from `x·a + z·c = 0`, `x = f·s` and `z = −e·s`. -/
theorem rel_param (x z e f : ℤ) (hf : f ≠ 0) (hc : IsCoprime f e)
    (h : x * (e * f) + z * f ^ 2 = 0) :
    ∃ s : ℤ, x = f * s ∧ z = -(e * s) := by
  have h1 : f * (x * e + z * f) = 0 := by linear_combination h
  have h2 : x * e + z * f = 0 := by
    rcases mul_eq_zero.mp h1 with h' | h'
    · exact absurd h' hf
    · exact h'
  have h3 : f ∣ x * e := ⟨-z, by linear_combination h2⟩
  obtain ⟨s, hs⟩ := hc.dvd_of_dvd_mul_right h3
  refine ⟨s, hs, ?_⟩
  have h4 : f * (e * s + z) = 0 := by linear_combination h2 - e * hs
  rcases mul_eq_zero.mp h4 with h' | h'
  · exact absurd h' hf
  · linarith

/-! ## Boundary censuses at multiplier `m`

The base of `Δ_m` has length `e·m·N₁`; a boundary word `(n_a, n_b, n_c)` on it satisfies
`n_b ≡ e·m (mod f)`.  Certified instances: `m = 2` gives `n_b ≡ 0 (mod 2)` — both 44-tilings
have `n_b = 0`; `m = 3` gives `n_b ≡ 1 (mod 2)` — the 99-tiling has `n_b = 7`.  On an equal side
(length `f³m`) the mod-`e` residue reads `n_b + n_c ≡ f·m (mod e)`.  These are congruences,
satisfiable for every `m ≥ 1`: **no multiplier is excluded by boundary arithmetic**; the `m = 1`
exclusions are geometric (per-member exhaustions; Hypothesis (walls) conditionally in general). -/

/-- Base census: `(n_b − e·m)·e²` is divisible by `f`. -/
theorem base_b_census (na nb nc e f m : ℤ)
    (h : na * (e * f) + nb * (f ^ 2 - e ^ 2) + nc * f ^ 2 = e * m * (3 * f ^ 2 - e ^ 2)) :
    f ∣ (nb - e * m) * e ^ 2 :=
  ⟨na * e + nb * f + nc * f - 3 * e * m * f, by linear_combination -h⟩

/-- With `gcd(e,f) = 1`: the base `b`-count satisfies `n_b ≡ e·m (mod f)` at every multiplier. -/
theorem base_b_census' (na nb nc e f m : ℤ) (hc : IsCoprime f e)
    (h : na * (e * f) + nb * (f ^ 2 - e ^ 2) + nc * f ^ 2 = e * m * (3 * f ^ 2 - e ^ 2)) :
    f ∣ nb - e * m :=
  (hc.pow_right (n := 2)).dvd_of_dvd_mul_right (base_b_census na nb nc e f m h)

/-- Side census: on an equal side, `(n_b + n_c − f·m)·f²` is divisible by `e`. -/
theorem side_census (na nb nc e f m : ℤ)
    (h : na * (e * f) + nb * (f ^ 2 - e ^ 2) + nc * f ^ 2 = m * f ^ 3) :
    e ∣ (nb + nc - f * m) * f ^ 2 :=
  ⟨nb * e - na * f, by linear_combination h⟩

/-! ## The unit atom is dead (its base word is forced)

The atom at scale `1` has base `e·b`.  Its base word satisfies `n_b ≡ e (mod f)` by the census
below, and `0 ≤ n_b ≤ e < f` forces `n_b = e` exactly; the residual `n_a·a + n_c·c = 0` with
nonnegative counts then forces `n_a = n_c = 0`.  So **the unit atom's base is `bᵉ`, whole
`b`-edges, for every member** — no `a` or `c` ever appears.

At `e = 1` the base is a single `b`-edge.  Its two endpoint corners inside the atom are the
tile's `α`- and `γ`-corners (the corners adjacent to side `b`), and each base corner of the atom
has opening `α + β`.  Filling an opening of exactly `α + β` by tile angles has the unique
solution `{α, β}` (`corner_fill_unique`); `γ = 2α + β` does not fit.  So the `γ`-end overflows:
**the unit atom admits no tiling at `e = 1`, for every `f`.**  (At `(2,3)` the unit atom dies by
a forced overlap — commit `417c774`; the general `e ≥ 2` case is open.)  This is the one-line
reason the block-plus-middle skeleton cannot produce an `m = 1` tiling. -/

/-- Atom base census: `(n_b − e)·e²` is divisible by `f` on the atom's base `e·b`. -/
theorem atom_base_census (na nb nc e f : ℤ)
    (h : na * (e * f) + nb * (f ^ 2 - e ^ 2) + nc * f ^ 2 = e * (f ^ 2 - e ^ 2)) :
    f ∣ (nb - e) * e ^ 2 :=
  ⟨na * e + nb * f + nc * f - e * f, by linear_combination -h⟩

/-- **The atom's base word is forced to `bᵉ`.**  With `gcd(e,f) = 1`, `0 ≤ n_b ≤ e < f` and
nonnegative counts, the only word on the atom base is `n_b = e`, `n_a = n_c = 0`. -/
theorem atom_base_forced (na nb nc e f : ℤ) (hc : IsCoprime f e)
    (he : 0 < e) (hef : e < f) (hna : 0 ≤ na) (hnb : 0 ≤ nb) (hnbe : nb ≤ e) (hnc : 0 ≤ nc)
    (h : na * (e * f) + nb * (f ^ 2 - e ^ 2) + nc * f ^ 2 = e * (f ^ 2 - e ^ 2)) :
    nb = e ∧ na = 0 ∧ nc = 0 := by
  have hf : 0 < f := lt_trans he hef
  obtain ⟨k, hk⟩ :=
    (hc.pow_right (n := 2)).dvd_of_dvd_mul_right (atom_base_census na nb nc e f h)
  have hk0 : k = 0 := by
    rcases lt_trichotomy k 0 with h' | h' | h'
    · exfalso
      have h2 : f * k ≤ f * (-1) := mul_le_mul_of_nonneg_left (by omega) hf.le
      linarith
    · exact h'
    · exfalso
      have h2 : f * 1 ≤ f * k := mul_le_mul_of_nonneg_left (by omega) hf.le
      linarith
  have hnb_e : nb = e := by rw [hk0, mul_zero] at hk; linarith
  have h0 : na * (e * f) + nc * f ^ 2 = 0 := by
    linear_combination h - (f ^ 2 - e ^ 2) * hnb_e
  have hef0 : 0 < e * f := mul_pos he hf
  have hz1 : na * (e * f) = 0 ∧ nc * f ^ 2 = 0 := by
    constructor <;> nlinarith [mul_nonneg hna hef0.le, mul_nonneg hnc (pow_pos hf 2).le]
  refine ⟨hnb_e, ?_, ?_⟩
  · rcases mul_eq_zero.mp hz1.1 with h' | h'
    · exact h'
    · exact absurd h' (ne_of_gt hef0)
  · rcases mul_eq_zero.mp hz1.2 with h' | h'
    · exact h'
    · exact absurd h' (ne_of_gt (pow_pos hf 2))

/-- **Corner fill is unique.**  In the angle count `(α, β) ↦ (1,0)`, `γ ↦ (2,1)`, an opening of
exactly `α + β = (1,1)` is filled only by one `α` and one `β`: the solutions of
`p + 2r = 1 ∧ q + r = 1` in ℕ are exactly `(p,q,r) = (1,1,0)`.  In particular a `γ`-corner
(`r = 1`) never fits, which kills the `γ`-end of the unit atom's single base `b`-edge at `e=1`. -/
theorem corner_fill_unique (p q r : ℕ) :
    (p + 2 * r = 1 ∧ q + r = 1) ↔ (p = 1 ∧ q = 1 ∧ r = 0) := by omega

/-! ## The addition law (seed calculus)

**Theorem (paper).**  For every member `(e,f)` and `m₁, m₂ ≥ 1` with `Δ_{m₁}` and `Δ_{m₂}`
tileable and `f ∣ m₁`: `Δ_{m₁+m₂}` is tileable.  At `e = 1` the divisibility is unnecessary.

Geometry: cut the band `Δ_{m₁+m₂} ∖ Δ_{m₁}^{apex}` from its top-west vertex parallel to the east
leg; the pieces are the apex-anchored `Δ_{m₁}`, the parallelogram `P` spanned by `m₁·Y₁` (base
direction) and `m₂·X₁` (east-leg direction), and an upright `Δ_{m₂}` at the west corner — three
full straight interfaces, flush by the isosceles altitude identity `X₁·cos β = Y₁/2` exactly as
in the collar lemma (`lem:collar`, companion).  `P` is tiled: at `e = 1` by `m₁·m₂` translates of
the unit parallelogram `P₁` (`thm:pgram-e1`); in general, when `m₁ = f·s`, as a grid of
`(s·N₁) × (m₂·f)` copies of the `a×c` two-tile cell — the side divisibilities are `pgram_cols`,
the count is `pgram_cell_count`.

This replaces the single-seed step of `prop:widecol` (companion), whose stated form leaves the
corner triangle `Δ_{M−t}` untiled: the honest law needs both seeds.  Consequences: `S(e,f)` is
closed under `m ↦ km` (subdivision), under `+` restricted to `f ∣ m₁` (all members), and under
`+` outright at `e = 1`.  With seeds `{2,3}` at `(1,2)` this regenerates `S(1,2) = {m ≥ 2}`
(`thm:realize12`); at `(1,3)`, seeds can only start at `Δ₃` (`m=1` exhausted, `m=2` excluded),
and `⟨3⟩` under these operations is exactly the multiples of `3`. -/

/-- Count bookkeeping of the addition law: `(m₁+m₂)²N = m₁²N + 2m₁m₂N + m₂²N`. -/
theorem add_count (m1 m2 N : ℤ) :
    (m1 + m2) ^ 2 * N = m1 ^ 2 * N + 2 * (m1 * m2 * N) + m2 ^ 2 * N := by ring

/-- The connecting parallelogram is a whole `a × c` grid when `f ∣ m₁`: its base `m₁·(e·N₁)` is
`s·N₁` whole `a`-edges and its slant `m₂·f³` is `m₂·f` whole `c`-edges. -/
theorem pgram_cols (s N1 e f m2 : ℤ) :
    (f * s) * (e * N1) = (s * N1) * (e * f) ∧ m2 * f ^ 3 = (m2 * f) * f ^ 2 :=
  ⟨by ring, by ring⟩

/-- Two tiles per cell: the parallelogram carries `2·m₁·m₂·N₁ = 2·(s·N₁)·(m₂·f)` tiles. -/
theorem pgram_cell_count (s N1 m2 f : ℤ) :
    2 * ((f * s) * m2 * N1) = 2 * ((s * N1) * (m2 * f)) := by ring

/-- `(1,3)` reachability from `Δ₃`: `(3k)²·26 = k²·234` — the multiples of `3` and nothing
else are reachable from a `Δ₃` seed under subdivision and addition. -/
theorem reachable_13 (k : ℤ) : (3 * k) ^ 2 * 26 = k ^ 2 * 234 := by ring

/-! ## The cevian family closes at `(1,2)`: the W-parallelogram slabs

The cevian piece `W_m` (sides `e(2f²−e²)m`, `f³m`, `fbm`) obeys the same addition law as the
target once its unit parallelogram is tiled: `W_{m₁+m₂} = W_{m₁} ⊔ P ⊔ W_{m₂}` with `P` spanned
by `m₁·fb` (cevian direction) and `m₂·e(2f²−e²)` (base direction) at angle `α+β`.  At `e = 1`
the `c`-glued two-tile brick — sides `a`, `b`, angle `α+β` — fills `P` by slabs: the base side
is `Y = 2f²−1 = f·a + b`, so `f` slabs of height `a` (each `X/b = f` bricks, `X = fb`) and one
slab of height `b` (`X/a = b` bricks) tile the unit `P` with `f² + b = 2f²−1` bricks, i.e.
`2(2f²−1)` tiles.  With the kernel-certified seeds `W₂` (`CevianTiling28`) and `W₃`
(`CevianTiling63`) the addition law reaches every `m ≥ 2`; and `W₁` is dead unconditionally,
since a `7`-tiling of `W₁` plus the east scaled tile would tile `Δ₁ = (8,8,11)`, refuted by the
certified `N = 11` exhaustion.  Hence at `(1,2)`:

  **`N = 7m²` is a tile count for every `m ≥ 2`, and for no other `m` on this target** —

a second (target, tile) pair over the tile `(2,3,4)` with a completely determined instance
spectrum, and the new count `175 = 7·5²`. -/

/-- The W-parallelogram slab census at `e = 1`: `Y = 2f²−1 = f·a + b` with `a = f`, `b = f²−1`,
and the brick count is `f·f + b = 2f²−1`, i.e. `2(2f²−1)` tiles. -/
theorem w_slab_counts (f : ℤ) :
    2 * f ^ 2 - 1 = f * f + (f ^ 2 - 1) ∧
    2 * (f * f + (f ^ 2 - 1)) = 2 * (2 * f ^ 2 - 1) :=
  ⟨by ring, by ring⟩

/-- Cevian-family anchors at `(1,2)`: `28 = 7·2²`, `63 = 7·3²`, `112 = 7·4²`, `175 = 7·5²`. -/
theorem w_counts :
    (7:ℤ) * 2 ^ 2 = 28 ∧ (7:ℤ) * 3 ^ 2 = 63 ∧ (7:ℤ) * 4 ^ 2 = 112 ∧ (7:ℤ) * 5 ^ 2 = 175 := by
  norm_num

end Erdos634.Primitives

#print axioms Erdos634.Primitives.ladder_cells
#print axioms Erdos634.Primitives.two_tiles_plus_atom
#print axioms Erdos634.Primitives.rel_b_mult
#print axioms Erdos634.Primitives.rel_param
#print axioms Erdos634.Primitives.base_b_census'
#print axioms Erdos634.Primitives.atom_base_forced
#print axioms Erdos634.Primitives.corner_fill_unique
#print axioms Erdos634.Primitives.add_count
