import Erdos634.CertNode

/-!
# Control: the certified-search format on the real 44-tiling -- GENERATED by `gen_tree.py t44`

The first three nodes of the constructor's search on `Tiling44` (target `(0,0),(176,0),(88,24√15)`,
tile `(16,24,32)`), with the real tiling's tiles placed.  Here no node is a refutation: the
conclusion of `node_k` is that some unplaced tile of the dissection is one of the node's *live*
placements.  `Tiling44NodesControl.lean` instantiates these at `Tiling44Bridge.dissection` and
checks the live placement named is the real next tile.  Every kill at these nodes is a genuine
escape/overlap, proved as at Lemma P; nothing is assumed about the constructor.

No `sorry`; standard axioms.
-/

set_option maxHeartbeats 4000000

namespace Erdos634.Tiling44Nodes

open Erdos634.Geometry Erdos634.CertCoord Erdos634.CertGeom Erdos634.PlacementCompleteness
  Erdos634.SixPlacements Erdos634.CertNode

theorem hD15 : (0:ℝ) < 15 := by norm_num
theorem sr15_lt : sr 15 < 4 := sr_lt hD15 (by norm_num) (by norm_num)
theorem sr15_gt1 : 1 < sr 15 := sr_gt hD15 (by norm_num) (by norm_num)

theorem TGT_pos : 0 < ef 0 0 176 0 88 24 := by unfold ef; norm_num
/-- The target `(0, 0)`, `(176, 0)`, `(88, 24·r)`. -/
noncomputable def TGT : Tri := rtri 15 hD15 0 0 176 0 88 24 TGT_pos
theorem MODEL_pos : 0 < ef 0 0 16 0 22 6 := by unfold ef; norm_num
/-- The model tile `(0, 0)`, `(16, 0)`, `(22, 6·r)`: sides `16, 24, 32`. -/
noncomputable def MODEL : Tri := rtri 15 hD15 0 0 16 0 22 6 MODEL_pos
theorem MODEL_sides : dist (MODEL.pts 0) (MODEL.pts 1) = 16 ∧ dist (MODEL.pts 1) (MODEL.pts 2) = 24 ∧
    dist (MODEL.pts 0) (MODEL.pts 2) = 32 :=
  model_sides_rp hD15 MODEL_pos (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)

theorem T0_pos : 0 < ef 0 0 16 0 22 6 := by unfold ef; norm_num
/-- `T0` = `(0, 0)`, `(16, 0)`, `(22, 6·r)`. -/
noncomputable def T0 : Tri := rtri 15 hD15 0 0 16 0 22 6 T0_pos
theorem T0_pts : T0.pts 0 = rp 15 0 0 ∧ T0.pts 1 = rp 15 16 0 ∧ T0.pts 2 = rp 15 22 6 := ⟨rfl, rfl, rfl⟩

theorem T1_pos : 0 < ef 0 0 32 0 11 3 := by unfold ef; norm_num
/-- `T1` = `(0, 0)`, `(32, 0)`, `(11, 3·r)`. -/
noncomputable def T1 : Tri := rtri 15 hD15 0 0 32 0 11 3 T1_pos
theorem T1_pts : T1.pts 0 = rp 15 0 0 ∧ T1.pts 1 = rp 15 32 0 ∧ T1.pts 2 = rp 15 11 3 := ⟨rfl, rfl, rfl⟩

theorem T2_pos : 0 < ef 0 0 32 0 21 3 := by unfold ef; norm_num
/-- `T2` = `(0, 0)`, `(32, 0)`, `(21, 3·r)`. -/
noncomputable def T2 : Tri := rtri 15 hD15 0 0 32 0 21 3 T2_pos
theorem T2_pts : T2.pts 0 = rp 15 0 0 ∧ T2.pts 1 = rp 15 32 0 ∧ T2.pts 2 = rp 15 21 3 := ⟨rfl, rfl, rfl⟩

theorem T3_pos : 0 < ef 0 0 24 0 28 4 := by unfold ef; norm_num
/-- `T3` = `(0, 0)`, `(24, 0)`, `(28, 4·r)`. -/
noncomputable def T3 : Tri := rtri 15 hD15 0 0 24 0 28 4 T3_pos
theorem T3_pts : T3.pts 0 = rp 15 0 0 ∧ T3.pts 1 = rp 15 24 0 ∧ T3.pts 2 = rp 15 28 4 := ⟨rfl, rfl, rfl⟩

theorem T4_pos : 0 < ef 16 0 32 0 38 6 := by unfold ef; norm_num
/-- `T4` = `(16, 0)`, `(32, 0)`, `(38, 6·r)`. -/
noncomputable def T4 : Tri := rtri 15 hD15 16 0 32 0 38 6 T4_pos
theorem T4_pts : T4.pts 0 = rp 15 16 0 ∧ T4.pts 1 = rp 15 32 0 ∧ T4.pts 2 = rp 15 38 6 := ⟨rfl, rfl, rfl⟩

theorem T5_pos : 0 < ef 16 0 48 0 27 3 := by unfold ef; norm_num
/-- `T5` = `(16, 0)`, `(48, 0)`, `(27, 3·r)`. -/
noncomputable def T5 : Tri := rtri 15 hD15 16 0 48 0 27 3 T5_pos
theorem T5_pts : T5.pts 0 = rp 15 16 0 ∧ T5.pts 1 = rp 15 48 0 ∧ T5.pts 2 = rp 15 27 3 := ⟨rfl, rfl, rfl⟩

theorem T6_pos : 0 < ef 16 0 48 0 37 3 := by unfold ef; norm_num
/-- `T6` = `(16, 0)`, `(48, 0)`, `(37, 3·r)`. -/
noncomputable def T6 : Tri := rtri 15 hD15 16 0 48 0 37 3 T6_pos
theorem T6_pts : T6.pts 0 = rp 15 16 0 ∧ T6.pts 1 = rp 15 48 0 ∧ T6.pts 2 = rp 15 37 3 := ⟨rfl, rfl, rfl⟩

theorem T7_pos : 0 < ef 16 0 40 0 44 4 := by unfold ef; norm_num
/-- `T7` = `(16, 0)`, `(40, 0)`, `(44, 4·r)`. -/
noncomputable def T7 : Tri := rtri 15 hD15 16 0 40 0 44 4 T7_pos
theorem T7_pts : T7.pts 0 = rp 15 16 0 ∧ T7.pts 1 = rp 15 40 0 ∧ T7.pts 2 = rp 15 44 4 := ⟨rfl, rfl, rfl⟩

theorem T8_pos : 0 < ef 16 0 38 6 22 6 := by unfold ef; norm_num
/-- `T8` = `(16, 0)`, `(38, 6·r)`, `(22, 6·r)`. -/
noncomputable def T8 : Tri := rtri 15 hD15 16 0 38 6 22 6 T8_pos
theorem T8_pts : T8.pts 0 = rp 15 16 0 ∧ T8.pts 1 = rp 15 38 6 ∧ T8.pts 2 = rp 15 22 6 := ⟨rfl, rfl, rfl⟩

theorem T9_pos : 0 < ef 16 0 38 6 (121/8) (33/8) := by unfold ef; norm_num
/-- `T9` = `(16, 0)`, `(38, 6·r)`, `(121/8, 33/8·r)`. -/
noncomputable def T9 : Tri := rtri 15 hD15 16 0 38 6 (121/8) (33/8) T9_pos
theorem T9_pts : T9.pts 0 = rp 15 16 0 ∧ T9.pts 1 = rp 15 38 6 ∧ T9.pts 2 = rp 15 (121/8) (33/8) := ⟨rfl, rfl, rfl⟩

/-- Node 0: 0 placed tile(s), `v = (0, 0)`, `d = (1, 0)`; kills: child None, child None, escape(Q, edge 2), escape(Q, edge 2), child None, child None. -/
theorem node_0 {N : ℕ} (D : CongruentDissection N)
    (htarget : D.target.carrier = TGT.carrier) (hmodel : D.model.Congruent MODEL)
    : ∃ j, j ∉ ([] : List (Fin N)).toFinset ∧ ((D.tile j).carrier = T0.carrier ∨ (D.tile j).carrier = T1.carrier ∨ (D.tile j).carrier = T2.carrier ∨ (D.tile j).carrier = T3.carrier) := by
  classical
  have hyT : ∀ p ∈ TGT.carrier, 0 ≤ p 1 := fun p hp => target_y_nonneg hD15 (by norm_num) TGT_pos hp
  have hU : ∀ p, p ∈ unfilled D.toDissection ([] : List (Fin N)).toFinset ↔ p ∈ TGT.carrier := by
    intro p; rw [mem_unfilled_iff, htarget]
    simp []
  have hlex : ∀ p ∈ closure (unfilled D.toDissection ([] : List (Fin N)).toFinset), LexLE (rp 15 0 0) p := by
    refine hlex_of D.toDissection _ _ ((TGT.carrier ∩ halfR 15 0 1 0) ∩ (halfR 15 1 0 0)) ((TGT.isCompact.isClosed.inter (isClosed_halfR _ _ _ _)).inter (isClosed_halfR _ _ _ _)) ?_ ?_
    · intro p hpT hnot
      obtain ⟨X, Y, rfl⟩ := exists_rp hD15 p
      have hpT' : rp 15 X Y ∈ TGT.carrier := htarget ▸ hpT
      obtain ⟨hT0, hT1, hT2⟩ := rtri_ef_nonneg hD15 TGT_pos hpT'
      unfold ef at hT0 hT1 hT2
      have hY : 0 ≤ Y := by
        by_contra hR; push_neg at hR
        linarith
      simp only [Set.mem_inter_iff, Set.mem_union, mem_halfR_rp hD15]
      refine ⟨⟨hpT', by linarith⟩, ?_⟩
      rcases le_or_gt 0 X with hX | hX
      · exact (by linarith)
      · -- the region X < xv, Y ≥ yv
        exfalso; linarith
    · intro p hp
      obtain ⟨X, Y, rfl⟩ := exists_rp hD15 p
      simp only [Set.mem_inter_iff, Set.mem_union, mem_halfR_rp hD15] at hp
      obtain ⟨⟨hpT, hY⟩, hdis⟩ := hp
      obtain ⟨hT0, hT1, hT2⟩ := rtri_ef_nonneg hD15 TGT_pos hpT
      unfold ef at hT0 hT1 hT2
      refine lexLE_rp hD15 (by linarith) (fun hYe => ?_)
      rcases hdis with h <;> linarith
  have hfree : ∀ ε : ℝ, 0 < ε → ∃ t s : ℝ, 0 < t ∧ t < ε ∧ 0 < s ∧ s < ε ∧
      rp 15 0 0 + t • (rp 15 1 0 + s • perp (rp 15 1 0)) ∈ unfilled D.toDissection ([] : List (Fin N)).toFinset := by
    refine hfree_of hD15 (B := 4) (by norm_num) sr15_lt (τ := (1/4)) (by norm_num) _ _ _ ?_
    intro t ht htτ
    rw [pt_ccw_rp 15 hD15, hU]
    have ht2 : t ^ 2 ≤ (1/4) * t := by nlinarith [mul_le_mul_of_nonneg_left htτ ht.le]
    have ht2p : 0 < t ^ 2 := by positivity
    exact mem_rtri hD15 TGT_pos (by unfold ef; linarith) (by unfold ef; linarith) (by unfold ef; linarith)
  have hblocked : ∃ δ : ℝ, 0 < δ ∧ ∀ t s : ℝ, 0 < t → t < δ → 0 < s → s < δ →
      rp 15 0 0 + t • (rp 15 1 0 - s • perp (rp 15 1 0)) ∉ unfilled D.toDissection ([] : List (Fin N)).toFinset := by
    exact hblocked_base hD15 D.toDissection _ (fun p hp => hyT p (htarget ▸ hp)) 0
  obtain ⟨j, hj, k₀, k₁, k₂, hk01, hk02, hk12, hk₀, ⟨c', hc', hk₁⟩, hk₂⟩ :=
    placement_completeness D.toDissection ([] : List (Fin N)).toFinset (rp 15 0 0) (rp 15 1 0) (rp_unit hD15 (by norm_num)) hlex hfree hblocked
  have hcong : (D.tile j).Congruent MODEL := (D.tiles_congruent j).trans hmodel
  obtain ⟨hMa, hMb, hMc⟩ := MODEL_sides
  rcases six_placements hcong hMa hMb hMc (rp_unit hD15 (by norm_num)) hk01 hk02 hk12 hk₀ hc' hk₁ hk₂ with
    ⟨hP, hQ⟩ | ⟨hP, hQ⟩ | ⟨hP, hQ⟩ | ⟨hP, hQ⟩ | ⟨hP, hQ⟩ | ⟨hP, hQ⟩
  · -- placement 1: (16, 32, 24)
    have hP' : (D.tile j).pts k₁ = rp 15 16 0 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 22 6 := by
      rw [hQ, placeThird_rp hD15 0 0 1 0 16 32 24 22 6 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    have hjc : (D.tile j).carrier = T0.carrier :=
      carrier_eq_rtri_of_pts hD15 _ hk01 hk02 hk12 hk₀ hP' hQ' T0_pos
    exact ⟨j, hj, Or.inl hjc⟩
  · -- placement 2: (32, 16, 24)
    have hP' : (D.tile j).pts k₁ = rp 15 32 0 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 11 3 := by
      rw [hQ, placeThird_rp hD15 0 0 1 0 32 16 24 11 3 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    have hjc : (D.tile j).carrier = T1.carrier :=
      carrier_eq_rtri_of_pts hD15 _ hk01 hk02 hk12 hk₀ hP' hQ' T1_pos
    exact ⟨j, hj, Or.inr (Or.inl hjc)⟩
  · -- placement 3: (16, 24, 32)
    have hP' : (D.tile j).pts k₁ = rp 15 16 0 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 (-6) 6 := by
      rw [hQ, placeThird_rp hD15 0 0 1 0 16 24 32 (-6) 6 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    exact (escape_of D.toDissection htarget j k₂ hQ' (not_mem_rtri_of_edge2 hD15 TGT_pos (by unfold ef; norm_num))).elim
  · -- placement 4: (24, 16, 32)
    have hP' : (D.tile j).pts k₁ = rp 15 24 0 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 (-4) 4 := by
      rw [hQ, placeThird_rp hD15 0 0 1 0 24 16 32 (-4) 4 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    exact (escape_of D.toDissection htarget j k₂ hQ' (not_mem_rtri_of_edge2 hD15 TGT_pos (by unfold ef; norm_num))).elim
  · -- placement 5: (32, 24, 16)
    have hP' : (D.tile j).pts k₁ = rp 15 32 0 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 21 3 := by
      rw [hQ, placeThird_rp hD15 0 0 1 0 32 24 16 21 3 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    have hjc : (D.tile j).carrier = T2.carrier :=
      carrier_eq_rtri_of_pts hD15 _ hk01 hk02 hk12 hk₀ hP' hQ' T2_pos
    exact ⟨j, hj, Or.inr (Or.inr (Or.inl hjc))⟩
  · -- placement 6: (24, 32, 16)
    have hP' : (D.tile j).pts k₁ = rp 15 24 0 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 28 4 := by
      rw [hQ, placeThird_rp hD15 0 0 1 0 24 32 16 28 4 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    have hjc : (D.tile j).carrier = T3.carrier :=
      carrier_eq_rtri_of_pts hD15 _ hk01 hk02 hk12 hk₀ hP' hQ' T3_pos
    exact ⟨j, hj, Or.inr (Or.inr (Or.inr (hjc)))⟩

/-- Node 1: 1 placed tile(s), `v = (16, 0)`, `d = (1, 0)`; kills: child None, child None, escape(Q, edge 2), escape(Q, edge 2), child None, child None. -/
theorem node_1 {N : ℕ} (D : CongruentDissection N)
    (htarget : D.target.carrier = TGT.carrier) (hmodel : D.model.Congruent MODEL)
    (i0 : Fin N) (h0 : (D.tile i0).carrier = T0.carrier)
    : ∃ j, j ∉ ([i0] : List (Fin N)).toFinset ∧ ((D.tile j).carrier = T4.carrier ∨ (D.tile j).carrier = T5.carrier ∨ (D.tile j).carrier = T6.carrier ∨ (D.tile j).carrier = T7.carrier) := by
  classical
  have hyT : ∀ p ∈ TGT.carrier, 0 ≤ p 1 := fun p hp => target_y_nonneg hD15 (by norm_num) TGT_pos hp
  have hU : ∀ p, p ∈ unfilled D.toDissection ([i0] : List (Fin N)).toFinset ↔ p ∈ TGT.carrier ∧ p ∉ T0.carrier := by
    intro p; rw [mem_unfilled_iff, htarget]
    simp [h0]
  have hlex : ∀ p ∈ closure (unfilled D.toDissection ([i0] : List (Fin N)).toFinset), LexLE (rp 15 16 0) p := by
    refine hlex_of D.toDissection _ _ ((TGT.carrier ∩ halfR 15 0 1 0) ∩ (halfR 15 1 0 (-16))) ((TGT.isCompact.isClosed.inter (isClosed_halfR _ _ _ _)).inter (isClosed_halfR _ _ _ _)) ?_ ?_
    · intro p hpT hnot
      obtain ⟨X, Y, rfl⟩ := exists_rp hD15 p
      have hpT' : rp 15 X Y ∈ TGT.carrier := htarget ▸ hpT
      obtain ⟨hT0, hT1, hT2⟩ := rtri_ef_nonneg hD15 TGT_pos hpT'
      unfold ef at hT0 hT1 hT2
      have hn0 : ¬ (0 ≤ 0 * X + 16 * Y + 0 ∧ 0 ≤ (-6) * X + 6 * Y + 96 ∧ 0 ≤ 6 * X + (-22) * Y + 0) := fun h =>
        hnot i0 (by simp) (by rw [h0]; exact mem_rtri hD15 T0_pos (by unfold ef; linarith [h.1]) (by unfold ef; linarith [h.2.1]) (by unfold ef; linarith [h.2.2]))
      have hY : 0 ≤ Y := by
        by_contra hR; push_neg at hR
        linarith
      simp only [Set.mem_inter_iff, Set.mem_union, mem_halfR_rp hD15]
      refine ⟨⟨hpT', by linarith⟩, ?_⟩
      rcases le_or_gt 16 X with hX | hX
      · exact (by linarith)
      · -- the region X < xv, Y ≥ yv
        exact (hn0 ⟨by linarith, by linarith, by linarith⟩).elim
    · intro p hp
      obtain ⟨X, Y, rfl⟩ := exists_rp hD15 p
      simp only [Set.mem_inter_iff, Set.mem_union, mem_halfR_rp hD15] at hp
      obtain ⟨⟨hpT, hY⟩, hdis⟩ := hp
      obtain ⟨hT0, hT1, hT2⟩ := rtri_ef_nonneg hD15 TGT_pos hpT
      unfold ef at hT0 hT1 hT2
      refine lexLE_rp hD15 (by linarith) (fun hYe => ?_)
      rcases hdis with h <;> linarith
  have hfree : ∀ ε : ℝ, 0 < ε → ∃ t s : ℝ, 0 < t ∧ t < ε ∧ 0 < s ∧ s < ε ∧
      rp 15 16 0 + t • (rp 15 1 0 + s • perp (rp 15 1 0)) ∈ unfilled D.toDissection ([i0] : List (Fin N)).toFinset := by
    refine hfree_of hD15 (B := 4) (by norm_num) sr15_lt (τ := (1/4)) (by norm_num) _ _ _ ?_
    intro t ht htτ
    rw [pt_ccw_rp 15 hD15, hU]
    have ht2 : t ^ 2 ≤ (1/4) * t := by nlinarith [mul_le_mul_of_nonneg_left htτ ht.le]
    have ht2p : 0 < t ^ 2 := by positivity
    exact ⟨mem_rtri hD15 TGT_pos (by unfold ef; linarith) (by unfold ef; linarith) (by unfold ef; linarith), not_mem_rtri_of_edge1 hD15 T0_pos (by unfold ef; linarith)⟩
  have hblocked : ∃ δ : ℝ, 0 < δ ∧ ∀ t s : ℝ, 0 < t → t < δ → 0 < s → s < δ →
      rp 15 16 0 + t • (rp 15 1 0 - s • perp (rp 15 1 0)) ∉ unfilled D.toDissection ([i0] : List (Fin N)).toFinset := by
    exact hblocked_base hD15 D.toDissection _ (fun p hp => hyT p (htarget ▸ hp)) 16
  obtain ⟨j, hj, k₀, k₁, k₂, hk01, hk02, hk12, hk₀, ⟨c', hc', hk₁⟩, hk₂⟩ :=
    placement_completeness D.toDissection ([i0] : List (Fin N)).toFinset (rp 15 16 0) (rp 15 1 0) (rp_unit hD15 (by norm_num)) hlex hfree hblocked
  have hcong : (D.tile j).Congruent MODEL := (D.tiles_congruent j).trans hmodel
  obtain ⟨hMa, hMb, hMc⟩ := MODEL_sides
  have hj0 : j ≠ i0 := fun h => hj (by rw [h]; simp)
  rcases six_placements hcong hMa hMb hMc (rp_unit hD15 (by norm_num)) hk01 hk02 hk12 hk₀ hc' hk₁ hk₂ with
    ⟨hP, hQ⟩ | ⟨hP, hQ⟩ | ⟨hP, hQ⟩ | ⟨hP, hQ⟩ | ⟨hP, hQ⟩ | ⟨hP, hQ⟩
  · -- placement 1: (16, 32, 24)
    have hP' : (D.tile j).pts k₁ = rp 15 32 0 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 38 6 := by
      rw [hQ, placeThird_rp hD15 16 0 1 0 16 32 24 22 6 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    have hjc : (D.tile j).carrier = T4.carrier :=
      carrier_eq_rtri_of_pts hD15 _ hk01 hk02 hk12 hk₀ hP' hQ' T4_pos
    exact ⟨j, hj, Or.inl hjc⟩
  · -- placement 2: (32, 16, 24)
    have hP' : (D.tile j).pts k₁ = rp 15 48 0 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 27 3 := by
      rw [hQ, placeThird_rp hD15 16 0 1 0 32 16 24 11 3 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    have hjc : (D.tile j).carrier = T5.carrier :=
      carrier_eq_rtri_of_pts hD15 _ hk01 hk02 hk12 hk₀ hP' hQ' T5_pos
    exact ⟨j, hj, Or.inr (Or.inl hjc)⟩
  · -- placement 3: (16, 24, 32)
    have hP' : (D.tile j).pts k₁ = rp 15 32 0 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 10 6 := by
      rw [hQ, placeThird_rp hD15 16 0 1 0 16 24 32 (-6) 6 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    exact (escape_of D.toDissection htarget j k₂ hQ' (not_mem_rtri_of_edge2 hD15 TGT_pos (by unfold ef; norm_num))).elim
  · -- placement 4: (24, 16, 32)
    have hP' : (D.tile j).pts k₁ = rp 15 40 0 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 12 4 := by
      rw [hQ, placeThird_rp hD15 16 0 1 0 24 16 32 (-4) 4 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    exact (escape_of D.toDissection htarget j k₂ hQ' (not_mem_rtri_of_edge2 hD15 TGT_pos (by unfold ef; norm_num))).elim
  · -- placement 5: (32, 24, 16)
    have hP' : (D.tile j).pts k₁ = rp 15 48 0 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 37 3 := by
      rw [hQ, placeThird_rp hD15 16 0 1 0 32 24 16 21 3 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    have hjc : (D.tile j).carrier = T6.carrier :=
      carrier_eq_rtri_of_pts hD15 _ hk01 hk02 hk12 hk₀ hP' hQ' T6_pos
    exact ⟨j, hj, Or.inr (Or.inr (Or.inl hjc))⟩
  · -- placement 6: (24, 32, 16)
    have hP' : (D.tile j).pts k₁ = rp 15 40 0 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 44 4 := by
      rw [hQ, placeThird_rp hD15 16 0 1 0 24 32 16 28 4 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    have hjc : (D.tile j).carrier = T7.carrier :=
      carrier_eq_rtri_of_pts hD15 _ hk01 hk02 hk12 hk₀ hP' hQ' T7_pos
    exact ⟨j, hj, Or.inr (Or.inr (Or.inr (hjc)))⟩

/-- Node 2: 2 placed tile(s), `v = (16, 0)`, `d = (11/16, 3/16·r)`; kills: escape(Q, edge 2), overlap(tile 0), escape(Q, edge 2), escape(Q, edge 2), child None, escape(Q, edge 2). -/
theorem node_2 {N : ℕ} (D : CongruentDissection N)
    (htarget : D.target.carrier = TGT.carrier) (hmodel : D.model.Congruent MODEL)
    (i0 i1 : Fin N) (h0 : (D.tile i0).carrier = T0.carrier) (h1 : (D.tile i1).carrier = T4.carrier)
    : ∃ j, j ∉ ([i0, i1] : List (Fin N)).toFinset ∧ ((D.tile j).carrier = T8.carrier) := by
  classical
  have hyT : ∀ p ∈ TGT.carrier, 0 ≤ p 1 := fun p hp => target_y_nonneg hD15 (by norm_num) TGT_pos hp
  have hU : ∀ p, p ∈ unfilled D.toDissection ([i0, i1] : List (Fin N)).toFinset ↔ p ∈ TGT.carrier ∧ p ∉ T0.carrier ∧ p ∉ T4.carrier := by
    intro p; rw [mem_unfilled_iff, htarget]
    simp [h0, h1]
  have hlex : ∀ p ∈ closure (unfilled D.toDissection ([i0, i1] : List (Fin N)).toFinset), LexLE (rp 15 16 0) p := by
    refine hlex_of D.toDissection _ _ ((TGT.carrier ∩ halfR 15 0 1 0) ∩ (halfR 15 1 0 (-16))) ((TGT.isCompact.isClosed.inter (isClosed_halfR _ _ _ _)).inter (isClosed_halfR _ _ _ _)) ?_ ?_
    · intro p hpT hnot
      obtain ⟨X, Y, rfl⟩ := exists_rp hD15 p
      have hpT' : rp 15 X Y ∈ TGT.carrier := htarget ▸ hpT
      obtain ⟨hT0, hT1, hT2⟩ := rtri_ef_nonneg hD15 TGT_pos hpT'
      unfold ef at hT0 hT1 hT2
      have hn0 : ¬ (0 ≤ 0 * X + 16 * Y + 0 ∧ 0 ≤ (-6) * X + 6 * Y + 96 ∧ 0 ≤ 6 * X + (-22) * Y + 0) := fun h =>
        hnot i0 (by simp) (by rw [h0]; exact mem_rtri hD15 T0_pos (by unfold ef; linarith [h.1]) (by unfold ef; linarith [h.2.1]) (by unfold ef; linarith [h.2.2]))
      have hn1 : ¬ (0 ≤ 0 * X + 16 * Y + 0 ∧ 0 ≤ (-6) * X + 6 * Y + 192 ∧ 0 ≤ 6 * X + (-22) * Y + (-96)) := fun h =>
        hnot i1 (by simp) (by rw [h1]; exact mem_rtri hD15 T4_pos (by unfold ef; linarith [h.1]) (by unfold ef; linarith [h.2.1]) (by unfold ef; linarith [h.2.2]))
      have hY : 0 ≤ Y := by
        by_contra hR; push_neg at hR
        linarith
      simp only [Set.mem_inter_iff, Set.mem_union, mem_halfR_rp hD15]
      refine ⟨⟨hpT', by linarith⟩, ?_⟩
      rcases le_or_gt 16 X with hX | hX
      · exact (by linarith)
      · -- the region X < xv, Y ≥ yv
        exact (hn0 ⟨by linarith, by linarith, by linarith⟩).elim
    · intro p hp
      obtain ⟨X, Y, rfl⟩ := exists_rp hD15 p
      simp only [Set.mem_inter_iff, Set.mem_union, mem_halfR_rp hD15] at hp
      obtain ⟨⟨hpT, hY⟩, hdis⟩ := hp
      obtain ⟨hT0, hT1, hT2⟩ := rtri_ef_nonneg hD15 TGT_pos hpT
      unfold ef at hT0 hT1 hT2
      refine lexLE_rp hD15 (by linarith) (fun hYe => ?_)
      rcases hdis with h <;> linarith
  have hfree : ∀ ε : ℝ, 0 < ε → ∃ t s : ℝ, 0 < t ∧ t < ε ∧ 0 < s ∧ s < ε ∧
      rp 15 16 0 + t • (rp 15 (11/16) (3/16) + s • perp (rp 15 (11/16) (3/16))) ∈ unfilled D.toDissection ([i0, i1] : List (Fin N)).toFinset := by
    refine hfree_of hD15 (B := 4) (by norm_num) sr15_lt (τ := (1/8)) (by norm_num) _ _ _ ?_
    intro t ht htτ
    rw [pt_ccw_rp 15 hD15, hU]
    have ht2 : t ^ 2 ≤ (1/8) * t := by nlinarith [mul_le_mul_of_nonneg_left htτ ht.le]
    have ht2p : 0 < t ^ 2 := by positivity
    exact ⟨mem_rtri hD15 TGT_pos (by unfold ef; linarith) (by unfold ef; linarith) (by unfold ef; linarith), not_mem_rtri_of_edge1 hD15 T0_pos (by unfold ef; linarith), not_mem_rtri_of_edge2 hD15 T4_pos (by unfold ef; linarith)⟩
  have hblocked : ∃ δ : ℝ, 0 < δ ∧ ∀ t s : ℝ, 0 < t → t < δ → 0 < s → s < δ →
      rp 15 16 0 + t • (rp 15 (11/16) (3/16) - s • perp (rp 15 (11/16) (3/16))) ∉ unfilled D.toDissection ([i0, i1] : List (Fin N)).toFinset := by
    have hsub : T4.carrier ⊆ (D.tile i1).carrier := (h1.trans
      (carrier_eq_rtri_of_pts hD15 T4 (k₀ := 0) (k₁ := 1) (k₂ := 2) (by decide) (by decide) (by decide) rfl rfl rfl T4_pos)).symm.subset
    refine hblocked_of_wedge hD15 sr15_gt1 D.toDissection _ (i := i1) (by simp) _ _ T4 hsub rfl
      (wedge_interior T4 (rp 15 (11/16) (3/16)) (sr 15 • perp (rp 15 (11/16) (3/16))) 0 (1/32) (-1/3) (11/96) ?_ ?_ ?_ ?_)
    · rw [T4_pts.1, T4_pts.2.1, T4_pts.2.2]; refine plane_ext ?_ ?_ <;> simp <;> ring
    · rw [sr_smul_perp_rp hD15, T4_pts.1, T4_pts.2.1, T4_pts.2.2]; refine plane_ext ?_ ?_ <;> simp <;> ring
    · exact Or.inr ⟨by norm_num, by norm_num⟩
    · exact Or.inl (by norm_num)
  obtain ⟨j, hj, k₀, k₁, k₂, hk01, hk02, hk12, hk₀, ⟨c', hc', hk₁⟩, hk₂⟩ :=
    placement_completeness D.toDissection ([i0, i1] : List (Fin N)).toFinset (rp 15 16 0) (rp 15 (11/16) (3/16)) (rp_unit hD15 (by norm_num)) hlex hfree hblocked
  have hcong : (D.tile j).Congruent MODEL := (D.tiles_congruent j).trans hmodel
  obtain ⟨hMa, hMb, hMc⟩ := MODEL_sides
  have hj0 : j ≠ i0 := fun h => hj (by rw [h]; simp)
  have hj1 : j ≠ i1 := fun h => hj (by rw [h]; simp)
  rcases six_placements hcong hMa hMb hMc (rp_unit hD15 (by norm_num)) hk01 hk02 hk12 hk₀ hc' hk₁ hk₂ with
    ⟨hP, hQ⟩ | ⟨hP, hQ⟩ | ⟨hP, hQ⟩ | ⟨hP, hQ⟩ | ⟨hP, hQ⟩ | ⟨hP, hQ⟩
  · -- placement 1: (16, 32, 24)
    have hP' : (D.tile j).pts k₁ = rp 15 27 3 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 (57/4) (33/4) := by
      rw [hQ, placeThird_rp hD15 16 0 (11/16) (3/16) 16 32 24 22 6 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    exact (escape_of D.toDissection htarget j k₂ hQ' (not_mem_rtri_of_edge2 hD15 TGT_pos (by unfold ef; norm_num))).elim
  · -- placement 2: (32, 16, 24)
    have hP' : (D.tile j).pts k₁ = rp 15 38 6 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 (121/8) (33/8) := by
      rw [hQ, placeThird_rp hD15 16 0 (11/16) (3/16) 32 16 24 11 3 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    have hjc : (D.tile j).carrier = T9.carrier :=
      carrier_eq_rtri_of_pts hD15 _ hk01 hk02 hk12 hk₀ hP' hQ' T9_pos
    exact (overlap_of D.toDissection hj0.symm h0 hjc (w := rp 15 (965/56) (487/168))
      (mem_interior_rtri hD15 T0_pos (by unfold ef; norm_num) (by unfold ef; norm_num) (by unfold ef; norm_num))
      (mem_interior_rtri hD15 T9_pos (by unfold ef; norm_num) (by unfold ef; norm_num) (by unfold ef; norm_num))).elim
  · -- placement 3: (16, 24, 32)
    have hP' : (D.tile j).pts k₁ = rp 15 27 3 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 (-5) 3 := by
      rw [hQ, placeThird_rp hD15 16 0 (11/16) (3/16) 16 24 32 (-6) 6 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    exact (escape_of D.toDissection htarget j k₂ hQ' (not_mem_rtri_of_edge2 hD15 TGT_pos (by unfold ef; norm_num))).elim
  · -- placement 4: (24, 16, 32)
    have hP' : (D.tile j).pts k₁ = rp 15 (65/2) (9/2) := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 2 2 := by
      rw [hQ, placeThird_rp hD15 16 0 (11/16) (3/16) 24 16 32 (-4) 4 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    exact (escape_of D.toDissection htarget j k₂ hQ' (not_mem_rtri_of_edge2 hD15 TGT_pos (by unfold ef; norm_num))).elim
  · -- placement 5: (32, 24, 16)
    have hP' : (D.tile j).pts k₁ = rp 15 38 6 := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 22 6 := by
      rw [hQ, placeThird_rp hD15 16 0 (11/16) (3/16) 32 24 16 21 3 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    have hjc : (D.tile j).carrier = T8.carrier :=
      carrier_eq_rtri_of_pts hD15 _ hk01 hk02 hk12 hk₀ hP' hQ' T8_pos
    exact ⟨j, hj, hjc⟩
  · -- placement 6: (24, 32, 16)
    have hP' : (D.tile j).pts k₁ = rp 15 (65/2) (9/2) := by rw [hP, rp_add_smul]; norm_num
    have hQ' : (D.tile j).pts k₂ = rp 15 24 8 := by
      rw [hQ, placeThird_rp hD15 16 0 (11/16) (3/16) 24 32 16 28 4 (by norm_num) (by norm_num) (by norm_num)]; norm_num
    exact (escape_of D.toDissection htarget j k₂ hQ' (not_mem_rtri_of_edge2 hD15 TGT_pos (by unfold ef; norm_num))).elim

/-! ## Non-vacuity: every placed tile is congruent to the model and inside the target, and
every node's placed tiles have pairwise disjoint interiors -- the node hypotheses describe
genuine partial configurations, not empty ones. -/

theorem T0_sides : dist (T0.pts 0) (T0.pts 1) ^ 2 = 256 ∧ dist (T0.pts 1) (T0.pts 2) ^ 2 = 576 ∧
    dist (T0.pts 2) (T0.pts 0) ^ 2 = 1024 := by
  rw [T0_pts.1, T0_pts.2.1, T0_pts.2.2, dist_rp_sq 15 hD15, dist_rp_sq 15 hD15, dist_rp_sq 15 hD15]; norm_num
theorem T0_inside : T0.carrier ⊆ TGT.carrier :=
  rtri_subset hD15 T0_pos _ (mem_rtri hD15 TGT_pos (by unfold ef; norm_num) (by unfold ef; norm_num) (by unfold ef; norm_num)) (mem_rtri hD15 TGT_pos (by unfold ef; norm_num) (by unfold ef; norm_num) (by unfold ef; norm_num)) (mem_rtri hD15 TGT_pos (by unfold ef; norm_num) (by unfold ef; norm_num) (by unfold ef; norm_num))

theorem T4_sides : dist (T4.pts 0) (T4.pts 1) ^ 2 = 256 ∧ dist (T4.pts 1) (T4.pts 2) ^ 2 = 576 ∧
    dist (T4.pts 2) (T4.pts 0) ^ 2 = 1024 := by
  rw [T4_pts.1, T4_pts.2.1, T4_pts.2.2, dist_rp_sq 15 hD15, dist_rp_sq 15 hD15, dist_rp_sq 15 hD15]; norm_num
theorem T4_inside : T4.carrier ⊆ TGT.carrier :=
  rtri_subset hD15 T4_pos _ (mem_rtri hD15 TGT_pos (by unfold ef; norm_num) (by unfold ef; norm_num) (by unfold ef; norm_num)) (mem_rtri hD15 TGT_pos (by unfold ef; norm_num) (by unfold ef; norm_num) (by unfold ef; norm_num)) (mem_rtri hD15 TGT_pos (by unfold ef; norm_num) (by unfold ef; norm_num) (by unfold ef; norm_num))

theorem disj_T0_T4 : Disjoint (interior T0.carrier) (interior T4.carrier) := by
  refine disj_of_sep_edge hD15 T0 T4 22 6 16 0 (by norm_num) ?_ ?_
  · intro k; fin_cases k
    · exact ⟨0, 0, T0_pts.1, by unfold ef; norm_num⟩
    · exact ⟨16, 0, T0_pts.2.1, by unfold ef; norm_num⟩
    · exact ⟨22, 6, T0_pts.2.2, by unfold ef; norm_num⟩
  · intro k; fin_cases k
    · exact ⟨16, 0, T4_pts.1, by unfold ef; norm_num⟩
    · exact ⟨32, 0, T4_pts.2.1, by unfold ef; norm_num⟩
    · exact ⟨38, 6, T4_pts.2.2, by unfold ef; norm_num⟩

theorem node_2_config :
    Disjoint (interior T0.carrier) (interior T4.carrier) :=
  disj_T0_T4

end Erdos634.Tiling44Nodes

#print axioms Erdos634.Tiling44Nodes.node_0
#print axioms Erdos634.Tiling44Nodes.node_1
#print axioms Erdos634.Tiling44Nodes.node_2
