import Erdos634.Tiling44Nodes
import Erdos634.Tiling44Control

/-!
# Accept-control: the certified-search format on the real 44-tiling

Erdős #634.  `Tiling44Nodes.lean` (generated by `gen_tree.py t44`) states, for the first three
nodes of the constructor's search on the `(16,16,22)`-by-`(2,3,4)` tiling (scaled ×8, field
`ℚ(√15)`), that some unplaced tile of *any* congruent dissection with that target and model is one
of the node's live placements — the node's kills being genuine escapes/overlaps proved exactly as
in `LemmaPTree.lean`.  This file instantiates those theorems at the kernel-checked real tiling
`Tiling44Bridge.dissection` and checks that the live placement the real tiling takes is the one
`gen_tree.py` names as the child:

* `control_root` — `node_0` applies to the real dissection (its hypotheses are dischargeable);
  the real first tile `tiles[0] = (0,0),(16,0),(22,6√15)` *is* `T0`, the first live placement;
* `control_node_1`, `control_node_2` — same at depth 1 and 2, with the real tiles placed:
  `tiles[1] = (16,0),(32,0),(38,6√15)` is `T4`, and `tiles[2] = (16,0),(38,6√15),(22,6√15)` is
  `T8`, the *only* live placement at depth 2.

So the format accepts a real tiling: at every node it certifies the kills and passes the real
next tile through as a child, never killing it.  (The reject control is the deliberate corruption
of one overlap witness in `LemmaPTree.lean`, which fails to build — recorded in
`private/ROOM/attack/report_generator.md`.)

Axiom-clean; no `sorry`.
-/

namespace Erdos634.Tiling44NodesControl

open Erdos634.Geometry Erdos634.CertCoord Erdos634.CertNode Erdos634.Tiling44Nodes
  Erdos634.Tiling44Bridge Erdos634.Tiling44Control Erdos634.Z15Real

theorem sr15_eq : sr 15 = Real.sqrt 15 := rfl

/-- The real target is the generated `TGT`. -/
theorem htarget : dissection.target.carrier = TGT.carrier := by
  show targetTri.carrier = TGT.carrier
  have hpts : targetTri.pts = TGT.pts := by
    rw [targetTri_eq]
    funext k
    fin_cases k
    · show mkPt 0 0 = mkPt 0 (0 * sr 15); simp
    · show mkPt 176 0 = mkPt 176 (0 * sr 15); simp
    · rfl
  unfold Tri.carrier
  rw [hpts]

/-- The real model (the first piece) is the generated `MODEL`. -/
theorem model_eq : dissection.model = MODEL := by
  show pieceTri headI_mem_tiles = MODEL
  have hpts : (pieceTri headI_mem_tiles).pts = MODEL.pts := by
    funext k
    fin_cases k <;> rw [pieceTri_pts] <;>
      simp [vertexOf, toR, zx, zy, toZPt, Tiling44.tiles, Tiling44.t1, Tiling44.t2, Tiling44.t3,
        MODEL, rtri, mkTri_pts, rp, sr]
  unfold pieceTri MODEL rtri mkTri
  congr 1

theorem hmodel : dissection.model.Congruent MODEL := model_eq ▸ Tri.Congruent.refl _

/-- The real tiles `0`, `1`, `2` as indices. -/
def idx1 : Fin Tiling44.tiles.length := ⟨1, by rw [tiles_length]; norm_num⟩
def idx2 : Fin Tiling44.tiles.length := ⟨2, by rw [tiles_length]; norm_num⟩

theorem tile1_pts :
    (dissection.tile idx1).pts 0 = rp 15 16 0 ∧ (dissection.tile idx1).pts 1 = rp 15 32 0 ∧
    (dissection.tile idx1).pts 2 = rp 15 38 6 := by
  rw [tile_eq]
  unfold pieceAt
  refine ⟨?_, ?_, ?_⟩ <;> rw [pieceTri_pts] <;>
    simp [vertexOf, toR, zx, zy, toZPt, idx1, Tiling44.tiles, Tiling44.t1, Tiling44.t2,
      Tiling44.t3, rp, sr]

theorem tile2_pts :
    (dissection.tile idx2).pts 0 = rp 15 16 0 ∧ (dissection.tile idx2).pts 1 = rp 15 38 6 ∧
    (dissection.tile idx2).pts 2 = rp 15 22 6 := by
  rw [tile_eq]
  unfold pieceAt
  refine ⟨?_, ?_, ?_⟩ <;> rw [pieceTri_pts] <;>
    simp [vertexOf, toR, zx, zy, toZPt, idx2, Tiling44.tiles, Tiling44.t1, Tiling44.t2,
      Tiling44.t3, rp, sr]

theorem tile0_pts' :
    (dissection.tile idx0).pts 0 = rp 15 0 0 ∧ (dissection.tile idx0).pts 1 = rp 15 16 0 ∧
    (dissection.tile idx0).pts 2 = rp 15 22 6 := by
  obtain ⟨h0, h1, h2⟩ := tile0_pts
  refine ⟨?_, ?_, ?_⟩
  · rw [h0]; simp [rp]
  · rw [h1]; simp [rp]
  · rw [h2]; rfl

/-- **The real first tile is `T0`**, the first live placement of `node_0`. -/
theorem real_tile0 : (dissection.tile idx0).carrier = T0.carrier :=
  carrier_eq_rtri_of_pts hD15 _ (k₀ := 0) (k₁ := 1) (k₂ := 2) (by decide) (by decide) (by decide)
    tile0_pts'.1 tile0_pts'.2.1 tile0_pts'.2.2 T0_pos

/-- **The real second tile is `T4`**, the first live placement of `node_1`. -/
theorem real_tile1 : (dissection.tile idx1).carrier = T4.carrier :=
  carrier_eq_rtri_of_pts hD15 _ (k₀ := 0) (k₁ := 1) (k₂ := 2) (by decide) (by decide) (by decide)
    tile1_pts.1 tile1_pts.2.1 tile1_pts.2.2 T4_pos

/-- **The real third tile is `T8`**, the only live placement of `node_2`. -/
theorem real_tile2 : (dissection.tile idx2).carrier = T8.carrier :=
  carrier_eq_rtri_of_pts hD15 _ (k₀ := 0) (k₁ := 1) (k₂ := 2) (by decide) (by decide) (by decide)
    tile2_pts.1 tile2_pts.2.1 tile2_pts.2.2 T8_pos

/-- **ACCEPT, depth 0.**  `node_0` holds of the real tiling, and the real tile realises it. -/
theorem control_root :
    (∃ j, j ∉ ([] : List (Fin Tiling44.tiles.length)).toFinset ∧
      ((dissection.tile j).carrier = T0.carrier ∨ (dissection.tile j).carrier = T1.carrier ∨
       (dissection.tile j).carrier = T2.carrier ∨ (dissection.tile j).carrier = T3.carrier)) ∧
    (dissection.tile idx0).carrier = T0.carrier :=
  ⟨node_0 dissection htarget hmodel, real_tile0⟩

/-- **ACCEPT, depth 1.** -/
theorem control_node_1 :
    (∃ j, j ∉ ([idx0] : List (Fin Tiling44.tiles.length)).toFinset ∧
      ((dissection.tile j).carrier = T4.carrier ∨ (dissection.tile j).carrier = T5.carrier ∨
       (dissection.tile j).carrier = T6.carrier ∨ (dissection.tile j).carrier = T7.carrier)) ∧
    (dissection.tile idx1).carrier = T4.carrier :=
  ⟨node_1 dissection htarget hmodel idx0 real_tile0, real_tile1⟩

/-- **ACCEPT, depth 2.**  Exactly one live placement, and it is the real tile. -/
theorem control_node_2 :
    (∃ j, j ∉ ([idx0, idx1] : List (Fin Tiling44.tiles.length)).toFinset ∧
      (dissection.tile j).carrier = T8.carrier) ∧
    (dissection.tile idx2).carrier = T8.carrier :=
  ⟨node_2 dissection htarget hmodel idx0 idx1 real_tile0 real_tile1, real_tile2⟩

end Erdos634.Tiling44NodesControl

#print axioms Erdos634.Tiling44NodesControl.control_root
#print axioms Erdos634.Tiling44NodesControl.control_node_1
#print axioms Erdos634.Tiling44NodesControl.control_node_2
