#!/usr/bin/env python3
"""The non-abelian tiling group does NOT obstruct the base-beta prime targets.

Companion to verify_tiling_group.py (which handles the (8,7,13)/N=105 case). Here the tile is
(2,3,4) with 3*alpha + 2*beta = pi, and the D=15 family (e,f)=(1,2) at scales m: base=11m,
equal=8m, N=11m^2. m=1 (N=11) does NOT tile; m=2,3,4 (N=44,99,176) DO.

The Conway-Lagarias tiling group of the tile is computed over finite quotients F_p[i], p == 3
(mod 4) (so i not in F_p) with 15 a quadratic residue (so sqrt15 in F_p). A region R tileable =>
chi(boundary R) = 1. Controls (must hold, else the setup is wrong): N=44,99,176 boundary trivial
(they tile); a triangle NOT congruent to the tile ("phibad") non-trivial (the group discriminates);
the tile-layer class-2 relators span the full class-2 space (the commutator layer collapses).

Result: at every tested prime the class-2 layer collapses to the rank-2 abelianization (the two
Phi-invariants), which is admissible for every base-beta candidate, and N=11 (the m=1 prime case)
has trivial boundary word -- so the tiling group cannot distinguish it from the m>=2 cases that DO
tile. The non-abelian tiling group is therefore not an obstruction for base-beta, extending the
(8,7,13) finding of verify_tiling_group.py to the base-beta tile. Exact arithmetic mod p; no floats.
"""
from math import gcd

# ---- F_p[i] arithmetic (i^2 = -1), elements (a,b) = a + b i, a,b in F_p ----
def good_primes(lo, hi):
    out = []
    for p in range(lo, hi):
        if p < 5: continue
        if any(p % k == 0 for k in range(2, int(p**0.5) + 1)): continue
        if p % 4 != 3: continue                       # i not in F_p
        if pow(15, (p - 1) // 2, p) != 1: continue    # 15 is a QR => sqrt15 in F_p
        out.append(p)
    return out

class Group2:
    """Free-nilpotent class-2 tiling group machinery over F_p[i], base-beta tile."""
    def __init__(self, p):
        self.p = p
        self.s15 = next(x for x in range(p) if x * x % p == 15 % p)   # sqrt15 mod p
        # tile edges (c,a,b) as complex vectors in F_p[i], with geometric lengths (4,2,3)
        inv = lambda d: pow(d, -1, p)
        s = self.s15
        # E_REF = [(4,0), (-11/8, 3 s15/8), (-21/8, -3 s15/8)]
        self.E = [((4 % p, 0), 4),
                  (((-11 * inv(8)) % p, (3 * s * inv(8)) % p), 2),
                  (((-21 * inv(8)) % p, (-3 * s * inv(8)) % p), 3)]
        # rotations e^{i alpha}=(7+s15 i)/8, e^{i gamma}=(-1+s15 i)/4, e^{i beta}=(-1-? ) via beta=(pi-3a)/2
        self.rA = ((7 * inv(8)) % p, (s * inv(8)) % p)
        self.rG = ((-1 * inv(4)) % p, (s * inv(4)) % p)
        # e^{i beta} = e^{i(pi-3alpha)/2} = i * (e^{i alpha/2})^{-3}; e^{i alpha/2}=(s15+i)/4
        h = ((s * inv(4)) % p, (1 * inv(4)) % p)             # e^{i alpha/2}
        hinv = self.cconj(h)                                  # unit => inverse = conj
        h3 = self.cmul(self.cmul(hinv, hinv), hinv)           # (e^{i a/2})^{-3}
        self.rB = self.cmul((0, 1), h3)                       # i * that
        self.orients = self._orient_group()

    def cmul(s, u, v):
        p = s.p
        return ((u[0] * v[0] - u[1] * v[1]) % p, (u[0] * v[1] + u[1] * v[0]) % p)
    def cconj(s, u): return (u[0], (-u[1]) % s.p)

    def _orient_group(s):
        # BFS the rotation group generated by e^{+-i alpha,beta,gamma} (finite mod p)
        gens = [s.rA, s.cconj(s.rA), s.rG, s.cconj(s.rG), s.rB, s.cconj(s.rB)]
        seen = {(1, 0)}; frontier = [(1, 0)]
        while frontier:
            nf = []
            for u in frontier:
                for g in gens:
                    w = s.cmul(u, g)
                    if w not in seen:
                        seen.add(w); nf.append(w)
            frontier = nf
            if len(seen) > 20000: break     # safety
        return sorted(seen)

    def tile_placements(s):
        # every orientation, both chiralities (reflection = conjugate the vectors)
        out = []
        for u in s.orients:
            edges = [(s.cmul(u, e), L) for (e, L) in s.E]
            out.append(edges)
            # reflection: conjugate each edge vector, reverse order & lengths kept
            refl = [(s.cconj(s.cmul(u, e)), L) for (e, L) in s.E]
            out.append(refl)
        return out


def run_prime(p, targets):
    G = Group2(p)
    canon = {}
    def gen(vec, L):
        # geometric length L>0; unit direction = vec * inv(L); canonical up to sign (antipode)
        Li = L % p; iv = pow(Li, -1, p)
        d = ((vec[0] * iv) % p, (vec[1] * iv) % p)
        nd = ((-d[0]) % p, (-d[1]) % p)
        key = min(d, nd); sign = 1 if d <= nd else -1
        if key not in canon: canon[key] = len(canon)
        return canon[key], (sign * L) % p
    tiles = G.tile_placements()
    # phi-non-admissible control loop: small triangle (1, e^{i alpha}, -(sum)), NOT the tile
    a_ = (1, 0); b_ = G.rA; c_ = ((-(a_[0] + b_[0])) % p, (-(a_[1] + b_[1])) % p)
    phibad = [(a_, 1), (b_, 1), (c_, 1)]
    for es in tiles:
        for (v, L) in es: gen(v, L)
    for tg in targets.values():
        for (v, L) in tg: gen(v, L)
    Dn_tile = len(canon)                 # generators from tiles+targets only (collapse metric)
    for (v, L) in phibad: gen(v, L)
    Dn = len(canon)
    pidx = {}
    for i in range(Dn):
        for j in range(i + 1, Dn): pidx[(i, j)] = len(pidx)
    NP = len(pidx)
    def c1(edges):
        v = [0] * Dn
        for (vec, L) in edges:
            g, l = gen(vec, L); v[g] = (v[g] + l) % p
        return v
    def c2(edges):
        w = [gen(vec, L) for (vec, L) in edges]; v = [0] * NP
        for i in range(len(w)):
            for j in range(i + 1, len(w)):
                gi, Li = w[i]; gj, Lj = w[j]
                if gi == gj: continue
                key = (min(gi, gj), max(gi, gj)); sg = 1 if gi < gj else -1
                v[pidx[key]] = (v[pidx[key]] + sg * Li * Lj) % p
        return v
    def brk(a, k):
        v = [0] * NP
        for j in range(Dn):
            if j == k or a[j] % p == 0: continue
            key = (min(j, k), max(j, k)); sg = 1 if j < k else -1
            v[pidx[key]] = (v[pidx[key]] + sg * a[j]) % p
        return v
    # collapse metric on the TILE generator block only (phibad's foreign directions have no
    # relators, so including them would spuriously lower the collapse ratio)
    NP_tile = sum(1 for (i, j) in pidx if i < Dn_tile and j < Dn_tile)
    rel = []
    for es in tiles:
        a = c1(es); rel.append(c2(es))
        for k in range(Dn): rel.append(brk(a, k))
    R = _rref(rel, NP, p)
    # tile-only class-2 collapse: restrict relators to pairs within the tile block
    rel_tile = []
    for es in tiles:
        a = c1(es)
        cc = c2(es)
        rel_tile.append([cc[pidx[(i, j)]] for (i, j) in pidx if i < Dn_tile and j < Dn_tile])
        for k in range(Dn_tile):
            bb = brk(a, k)
            rel_tile.append([bb[pidx[(i, j)]] for (i, j) in pidx if i < Dn_tile and j < Dn_tile])
    R_tile = _rref(rel_tile, NP_tile, p)
    tile_collapse = (len(R_tile) == NP_tile)
    R1 = _rref([c1(es) for es in tiles], Dn, p)
    def triv2(edges): return _in_span(c2(edges), R, NP, p)
    def triv1(edges): return _in_span(c1(edges), R1, Dn, p)   # Phi-admissible (mod p)
    def triv(edges): return triv1(edges) and triv2(edges)
    abel_rank = Dn - len(R1)
    # I12 NON-VACUITY CONTROL: phibad (a triangle NOT congruent to the tile) must be NON-trivial.
    return {'p': p, 'gens': Dn, 'gens_tile': Dn_tile, 'orients': len(G.orients),
            'c2dim_tile': NP_tile, 'tile_collapse': tile_collapse, 'abel_rank': abel_rank,
            'phibad_nontrivial': not triv(phibad),
            'triv': {name: triv(tg) for name, tg in targets.items()}}

def _rref(rows, n, p):
    rows = [r[:] for r in rows]; r = 0
    for c in range(n):
        pr = next((k for k in range(r, len(rows)) if rows[k][c] % p), None)
        if pr is None: continue
        rows[r], rows[pr] = rows[pr], rows[r]; iv = pow(rows[r][c], -1, p)
        rows[r] = [x * iv % p for x in rows[r]]
        for k in range(len(rows)):
            if k != r and rows[k][c] % p:
                f = rows[k][c]; rows[k] = [(a - f * b) % p for a, b in zip(rows[k], rows[r])]
        r += 1
        if r == len(rows): break
    return rows[:r]
def _in_span(v, R, n, p):
    v = v[:]
    for row in R:
        c = next((i for i in range(n) if row[i] % p), None)
        if c is not None and v[c] % p:
            f = v[c]; v = [(a - f * b) % p for a, b in zip(v, row)]
    return all(x % p == 0 for x in v)

def target_word(p, s15, base, equal):
    """isosceles (equal, equal, base): CCW boundary as 3 side vectors with geometric lengths."""
    inv = lambda d: pow(d, -1, p)
    # corners: (0,0), (base,0), (base/2, h) with h = sqrt(equal^2 - (base/2)^2) = k*sqrt15
    # base=e*N, equal=f^3 (m=1); h^2 = f^6 - (e*N/2)^2.  compute h as rational*sqrt15.
    # h^2 = equal^2 - base^2/4.  Represent h = (hn/hd)*sqrt15 where h^2 = 15*hn^2/hd^2.
    from fractions import Fraction as F
    h2 = F(equal) ** 2 - F(base, 2) ** 2
    hh = h2 / 15
    # hh must be a rational square
    from math import isqrt
    num, den = hh.numerator, hh.denominator
    rn, rd = isqrt(num), isqrt(den)
    assert rn * rn == num and rd * rd == den, f"h not k*sqrt15 for base={base},equal={equal}"
    hcoef = F(rn, rd)                          # h = hcoef * sqrt15
    apex = ((F(base, 2)), hcoef)               # (x rational, y = hcoef*sqrt15)
    def vecmod(dx_rat, dy_coef, L):            # dx rational, dy = dy_coef*sqrt15
        x = (dx_rat.numerator * inv(dx_rat.denominator)) % p
        y = (dy_coef.numerator * inv(dy_coef.denominator) * s15) % p
        return ((x, y), L)
    # side1 (0,0)->(base,0): (base,0) length base
    # side2 (base,0)->apex: (base/2 - base, hcoef) length equal
    # side3 apex->(0,0): (-base/2, -hcoef) length equal
    return [vecmod(F(base), F(0), base),
            vecmod(F(base, 2) - F(base), hcoef, equal),
            vecmod(-F(base, 2), -hcoef, equal)]


if __name__ == '__main__':
    ps = good_primes(5, 200)
    print(f"suitable primes (p=3 mod4, 15 a QR): {ps[:10]}")
    # targets: name -> (base, equal).  m=1: base=e*N, equal=f^3.  N=44,99 are m=2,3 (e=1,f=2).
    # ALL D=15 (tile (2,3,4), (e,f)=(1,2), scale m): base=11m, equal=8m, N=11m^2.
    # m=1 (N=11) does NOT tile; m=2,3 (N=44,99) DO.  Same tile & field -> the cleanest test.
    SPECS = {
        'N11  m=1  NON-TILING': (11, 8),      # (8,8,11)
        'N44  m=2  CONTROL(tiles)': (22, 16),  # (16,16,22)
        'N99  m=3  CONTROL(tiles)': (33, 24),  # (24,24,33)
        'N176 m=4  CONTROL(tiles)': (44, 32),  # (32,32,44)
        'N275 m=5  UNDETERMINED': (55, 40),    # (40,40,55)
    }
    allgood = True
    for p in [q for q in ps if q >= 43][:6]:
        s15 = next(x for x in range(p) if x * x % p == 15 % p)
        targets = {}
        try:
            for nm, (b, e) in SPECS.items():
                targets[nm] = target_word(p, s15, b, e)
        except AssertionError as ex:
            print(f"  p={p}: target build failed: {ex}"); continue
        r = run_prime(p, targets)
        # controls that MUST hold for the run to be meaningful (I12):
        controls_ok = (r['phibad_nontrivial'] and r['tile_collapse']
                       and r['triv']['N44  m=2  CONTROL(tiles)']
                       and r['triv']['N99  m=3  CONTROL(tiles)']
                       and r['triv']['N176 m=4  CONTROL(tiles)'])
        n11 = r['triv']['N11  m=1  NON-TILING']
        allgood &= controls_ok
        print(f"\n  p={p}: {r['orients']} orientations, {r['gens_tile']} tile gens, "
              f"class-2 dim {r['c2dim_tile']}, tile-layer COLLAPSES={r['tile_collapse']}, "
              f"abelianization rank={r['abel_rank']}")
        print(f"      controls OK (tile-collapse, phibad nontrivial, N44/99/176 trivial) = {controls_ok}")
        for nm, tv in r['triv'].items():
            print(f"      {nm:26s} boundary trivial = {tv}")
    print()
    if allgood:
        print("RESULT (A2, NO-GO): controls pass at every prime. The non-abelian Conway-Lagarias")
        print("  tiling group of the base-beta (2,3,4) tile collapses to its abelianization = the two")
        print("  Phi-invariants, which are ADMISSIBLE for every base-beta candidate. N=11 (m=1, the prime")
        print("  non-tiling case) has TRIVIAL boundary word -- the group does NOT obstruct it, exactly")
        print("  like the m=2,3,4 cases that DO tile. So the tiling group cannot distinguish the prime")
        print("  case, extending the paper's rem:tilinggroup finding from (8,7,13) to base-beta.")
    else:
        print("RESULT: CONTROLS FAILED -- setup is buggy (I18 kill). No conclusion drawn.")
