import Mathlib.Tactic

/-!
# The direction group of a triangle tiling

Let `T` be a triangle with angles `α, β, γ` and let a tiling by congruent copies of `T` be given.
Read around a tile, the edge direction turns by the exterior angle, so a tile's three directions are
`θ, θ−α, θ−α−β` modulo `π`: a translate of a fixed three-element set. Two tiles sharing a boundary
segment share a direction, and the tile adjacency graph is connected, so **every direction lies in a
single coset of the subgroup `⟨α, β⟩` of `ℝ/πℤ`** (`CosetPropagation.image_subset_coset`).

The structure of `⟨α, β⟩` is therefore the structure of `ℤ² / Λ`, where

    Λ = { (x,y) : x·α + y·β ≡ 0  (mod π) }.

For a tile whose angles satisfy one primitive rational relation and are otherwise irrational,
`Λ = ⟨(p,q)⟩` is generated by a single vector, and this file computes the quotient. Writing
`d = gcd(p,q)` and `(p,q) = d·(p',q')`:

    ℤ² / ⟨(p,q)⟩  ≅  ℤ ⊕ ℤ/d.

The free coordinate is the **label** `L(x,y) = q'·x − p'·y`, proved here to be surjective with kernel
exactly `⟨(p',q')⟩`. The torsion is `ℤ/d`.

## Why this classifies the branches

| branch | relation | `(p,q)` | `d` | direction group |
|---|---|---|---|---|
| base-β | `3α+2β=π` | `(3,2)` | 1 | `ℤ` |
| `γ=2α` | `3α+β=π` | `(3,1)` | 1 | `ℤ` |
| `γ=2π/3` | `α+β=π/3` | `(3,3)` | 3 | `ℤ ⊕ ℤ/3` |
| `γ=π/3` | `α+β=2π/3` | `(3,3)` | 3 | `ℤ ⊕ ℤ/3` |
| right angle | `α+β=π/2` | `(2,2)` | 2 | `ℤ ⊕ ℤ/2` |

The two branches with `α/π` irrational — base-β and `γ=2α` — are exactly the ones whose direction
group is **torsion-free infinite cyclic**. In the base-β case the generator is `γ` itself, since
`α ≡ 2γ` and `β ≡ −3γ` modulo `π`; `LabelCalculus.lean` is the instance `(p,q) = (3,2)` of the
results below, where `L(x,y) = 2x − 3y`.
-/

namespace Erdos634.DirectionGroup

variable {p q : ℤ}

/-- The label attached to a primitive relation vector `(p,q)`: the free coordinate of `ℤ²/⟨(p,q)⟩`. -/
def L (p q x y : ℤ) : ℤ := q * x - p * y

/-- `L` kills the relation vector: the label is well defined on the quotient. -/
theorem L_relation (p q : ℤ) : L p q p q = 0 := by simp [L]; ring

/-- **Surjectivity.** For a primitive `(p,q)` every integer is a label, so the free part is all of
`ℤ`. The witness is explicit, built from a Bézout pair. -/
theorem L_surjective (h : IsCoprime p q) (n : ℤ) : ∃ x y : ℤ, L p q x y = n := by
  obtain ⟨u, v, huv⟩ := h
  refine ⟨v * n, -(u * n), ?_⟩
  simp only [L]
  have : q * (v * n) - p * (-(u * n)) = (u * p + v * q) * n := by ring
  rw [this, huv, one_mul]

/-- **Kernel.** For a primitive `(p,q)` the label vanishes exactly on the multiples of `(p,q)`:
the quotient by the relation is torsion-free of rank one. Stated with `p ≠ 0`, which
holds in every branch (`p ∈ {2,3}`). -/
theorem L_ker (h : IsCoprime p q) (hp : p ≠ 0) (x y : ℤ) :
    L p q x y = 0 ↔ ∃ k : ℤ, x = p * k ∧ y = q * k := by
  constructor
  · intro hL
    have hqx : q * x = p * y := by simpa [L, sub_eq_zero] using hL
    have hpx : p ∣ x := h.dvd_of_dvd_mul_left ⟨y, hqx⟩
    obtain ⟨k, hk⟩ := hpx
    refine ⟨k, hk, ?_⟩
    have hmul : p * (q * k) = p * y := by rw [← hqx, hk]; ring
    exact (mul_left_cancel₀ hp hmul).symm
  · rintro ⟨k, rfl, rfl⟩
    simp [L]; ring

/-- The base-β instance: `(p,q) = (3,2)` gives the label `2x − 3y` of `LabelCalculus.lean`. -/
theorem L_basebeta (x y : ℤ) : L 3 2 x y = 2 * x - 3 * y := rfl

/-- `(3,2)` is primitive, so base-β's direction group is torsion-free of rank one. -/
theorem basebeta_coprime : IsCoprime (3 : ℤ) 2 := by
  refine ⟨1, -1, by ring⟩

/-- `γ = 2α` gives `(3,1)`, also primitive: the second torsion-free branch. -/
theorem gamma_two_alpha_coprime : IsCoprime (3 : ℤ) 1 := isCoprime_one_right

/-! ## Torsion is exactly the rational angle

The torsion subgroup of `ℤ²/⟨d·(p,q)⟩` (with `(p,q)` primitive) consists precisely of the classes of
the multiples of `(p,q)`, and the class of `(p,q)` has order exactly `d`. Geometrically: **the
torsion subgroup of the direction group is generated by the branch's rational angle.** In the
`γ = 2π/3` and `γ = π/3` branches the relation is `α + β ∈ {π/3, 2π/3}`, `Λ = ⟨(3,3)⟩`, and torsion
is `⟨α+β⟩ ≅ ℤ/3` — the rational angle `π/3`. In the right-angle branch `Λ = ⟨(2,2)⟩` and torsion is
`⟨α+β⟩ = ⟨π/2⟩ ≅ ℤ/2`. In base-β and `γ = 2α` the relation vector is primitive, torsion is trivial,
and **no nonzero direction difference is a rational multiple of `π`**.

With the fully commensurable tiles (all angles rational multiples of `π`), where `Λ` has rank 2 and
the direction group is finite, this gives a trichotomy across the classification:

    commensurable        →  finite direction group
    special angle        →  ℤ ⊕ ℤ/d, torsion generated by the rational angle
    base-β, γ = 2α       →  ℤ, torsion-free

The classical counting/colouring arguments for the special-angle branches turn on the rational angle
(the `2π/3` rotation structure, the right angle); the trichotomy locates that resource precisely and
shows the two resistant branches are exactly the ones without it. Recorded as an observation; no
mechanism theorem is claimed. -/

/-- **Torsion classes are the multiples of the primitive vector.** `(x,y)` is torsion modulo
`⟨d·(p,q)⟩` iff it is an integer multiple of `(p,q)`. -/
theorem torsion_iff (h : IsCoprime p q) (hp : p ≠ 0) (d : ℤ) (hd : d ≠ 0) (x y : ℤ) :
    (∃ n : ℤ, n ≠ 0 ∧ ∃ k : ℤ, n * x = d * p * k ∧ n * y = d * q * k)
      ↔ ∃ m : ℤ, x = p * m ∧ y = q * m := by
  constructor
  · rintro ⟨n, hn, k, hx, hy⟩
    have hqp : n * (q * x) = n * (p * y) := by
      calc n * (q * x) = q * (n * x) := by ring
        _ = q * (d * p * k) := by rw [hx]
        _ = p * (d * q * k) := by ring
        _ = p * (n * y) := by rw [hy]
        _ = n * (p * y) := by ring
    have hqx : q * x = p * y := mul_left_cancel₀ hn hqp
    have hpx : p ∣ x := h.dvd_of_dvd_mul_left ⟨y, hqx⟩
    obtain ⟨m, hm⟩ := hpx
    refine ⟨m, hm, ?_⟩
    have : p * (q * m) = p * y := by rw [← hqx, hm]; ring
    exact (mul_left_cancel₀ hp this).symm
  · rintro ⟨m, rfl, rfl⟩
    exact ⟨d, hd, m, by ring, by ring⟩

/-- **The torsion order is exactly `d`.** `k·(p,q)` lies in `⟨d·(p,q)⟩` iff `d ∣ k`. -/
theorem torsion_order (hp : p ≠ 0) (d k : ℤ) :
    (∃ j : ℤ, k * p = d * p * j ∧ k * q = d * q * j) ↔ d ∣ k := by
  constructor
  · rintro ⟨j, h1, _⟩
    have h2 : k * p = (d * j) * p := by rw [h1]; ring
    exact ⟨j, mul_right_cancel₀ hp h2⟩
  · rintro ⟨j, rfl⟩
    exact ⟨j, by ring, by ring⟩

end Erdos634.DirectionGroup
