import Mathlib.Tactic
import Erdos634.OrderForcing

/-!
# The frontier invariant: arithmetic core

The exhaustive search prunes a *frontier* (the uncovered polygons together with the per-side
boundary edge-type counts) by five conditions. Two of them, the area condition and the corner
angle condition, are geometric. The remaining three are arithmetic, and the one that carries the
combinatorial weight is

* **(P2)** every maximal straight run of the uncovered boundary joining two convex corners has
  integral length lying in the numerical semigroup `⟨a,b,c⟩`.

This file fixes that language and records the run lengths that are *gaps*, so that a frontier
carrying one of them is inadmissible. Each gap below is a restatement of a lemma proved in
`OrderForcing`, in the vocabulary the invariant uses.
-/

namespace Erdos634.Frontier

/-- The tile's short edge, `a = ef`. -/
def sideA (e f : ℕ) : ℕ := e * f
/-- The tile's middle edge, `b = f² − e²`. -/
def sideB (e f : ℕ) : ℕ := f * f - e * e
/-- The tile's long edge, `c = f²`. -/
def sideC (e f : ℕ) : ℕ := f * f

/-- Membership in the numerical semigroup generated by the three tile edges. A boundary run of
length `n` can be partitioned into whole tile edges exactly when `inSemi e f n` holds. -/
def inSemi (e f n : ℕ) : Prop := ∃ x y z : ℕ, x * sideA e f + y * sideB e f + z * sideC e f = n

/-- **(P2)**: a list of straight-run lengths is admissible when every entry lies in the
semigroup. -/
def runsOK (e f : ℕ) (runs : List ℕ) : Prop := ∀ n ∈ runs, inSemi e f n

/-- A run whose length is a gap makes the frontier inadmissible. This is the shape in which every
kill below is consumed. -/
theorem runsOK_fail {e f : ℕ} {runs : List ℕ} {n : ℕ} (hmem : n ∈ runs) (hgap : ¬ inSemi e f n) :
    ¬ runsOK e f runs := fun h => hgap (h n hmem)

/-! ## Gap catalogue at `e = 1`

Each entry names the configuration that produces the run, and is proved by the corresponding
lemma of `OrderForcing`. -/

/-- The anchored south cover of a row `c`-edge: after the forced mate-top `a`, a partial right-end
edge would leave a run `n` with `n + f + t = f²` and `0 < t < f`, and no such `n` lies in the
semigroup. -/
theorem gap_south_straddle {f t n : ℕ} (hf : 3 ≤ f) (ht1 : 1 ≤ t) (htf : t < f)
    (hn : n + f + t = f * f) : ¬ inSemi 1 f n := by
  rintro ⟨x, y, z, h⟩
  simp only [sideA, sideB, sideC, one_mul] at h
  refine OrderForcing.south_cover_straddle (x := x) (y := y) (z := z) hf ht1 htf ?_
  have h9 : 9 ≤ f * f := by nlinarith
  obtain ⟨B, hB⟩ : ∃ B, f * f = B + 1 := ⟨f * f - 1, by omega⟩
  rw [hB] at h hn ⊢
  simp only [Nat.add_sub_cancel] at h ⊢
  omega

/-- The east cover of an `X`-cell's `b`-edge, after a leak tile lays its `a` first: the remaining
run `n` satisfies `n + 1 + f = f²` and is a gap. -/
theorem gap_east_cover {f n : ℕ} (hf : 3 ≤ f) (hn : n + 1 + f = f * f) :
    ¬ inSemi 1 f n := by
  rintro ⟨x, y, z, h⟩
  simp only [sideA, sideB, sideC, one_mul] at h
  refine OrderForcing.east_cover_gap (x := x) (y := y) (z := z) hf ?_
  have h9 : 9 ≤ f * f := by nlinarith
  obtain ⟨B, hB⟩ : ∃ B, f * f = B + 1 := ⟨f * f - 1, by omega⟩
  rw [hB] at h hn ⊢
  simp only [Nat.add_sub_cancel] at h ⊢
  omega

/-- Laying a `c` along a chord of length `2b` leaves a run `n` with `n + 2 = f²`, a gap for
`f ≥ 3`; at `f = 2` it equals `a`, the coincidence the `(1,2)` tilings exploit. -/
theorem gap_two_b_minus_c {f n : ℕ} (hf : 3 ≤ f) (hn : n + 2 = f * f) :
    ¬ inSemi 1 f n := by
  rintro ⟨x, y, z, h⟩
  simp only [sideA, sideB, sideC, one_mul] at h
  refine OrderForcing.gap_2b_minus_c (x := x) (y := y) (z := z) hf ?_
  have h9 : 9 ≤ f * f := by nlinarith
  obtain ⟨B, hB⟩ : ∃ B, f * f = B + 1 := ⟨f * f - 1, by omega⟩
  rw [hB] at h hn ⊢
  simp only [Nat.add_sub_cancel] at h ⊢
  omega

/-- The catalogue is non-vacuous in the other direction: the run `n` with `n + f = f²` *is* in the
semigroup, being `f − 1` copies of `a`. A predicate that excluded everything would say nothing. -/
theorem south_cover_mem {f n : ℕ} (hf : 3 ≤ f) (hn : n + f = f * f) : inSemi 1 f n := by
  obtain ⟨g, hg⟩ : ∃ g, f = g + 1 := ⟨f - 1, by omega⟩
  subst hg
  refine ⟨g, 0, 0, ?_⟩
  simp only [sideA, sideB, sideC, Nat.zero_mul, Nat.add_zero, one_mul]
  have hring : g * (g + 1) + (g + 1) = (g + 1) * (g + 1) := by ring
  omega

/-! ## Corner rigidity for the two open instances at `N = 84` and `N = 88`

Both remaining instances below `N = 91` have every target corner filled in exactly one way, so the
corner tiles are forced in angle. The fill equations use the branch relation of each tile.

* `N = 84`: tile `(2,3,4)`, target `(24,24,42)`, with `γ = 2α+β` and `3α+2β = π`. The corners are
  `α`, `α` and `α+2β`.
* `N = 88`: tile `(3,5,7)`, target `(21,55,56)`, with `γ = 2π/3` and `α+β = π/3`, so `γ = 2α+2β`.
  The corners are `α`, `2β` and `2α+β`.
-/

/-- `N = 84`: the apex angle `α+2β` is filled only by `{α, β, β}`. -/
theorem corner84_apex (x y z : ℕ) (h1 : x + 2 * z = 1) (h2 : y + z = 2) :
    x = 1 ∧ y = 2 ∧ z = 0 := by omega

/-- `N = 84`: each base angle `α` is filled only by a single `α`. -/
theorem corner84_base (x y z : ℕ) (h1 : x + 2 * z = 1) (h2 : y + z = 0) :
    x = 1 ∧ y = 0 ∧ z = 0 := by omega

/-- `N = 88`: the angle `2α+β` is filled only by `{α, α, β}`. -/
theorem corner88_a (x y z : ℕ) (h1 : x + 2 * z = 2) (h2 : y + 2 * z = 1) :
    x = 2 ∧ y = 1 ∧ z = 0 := by omega

/-- `N = 88`: the angle `2β` is filled only by two `β`-corners. -/
theorem corner88_b (x y z : ℕ) (h1 : x + 2 * z = 0) (h2 : y + 2 * z = 2) :
    x = 0 ∧ y = 2 ∧ z = 0 := by omega

/-- `N = 88`: the angle `α` is filled only by a single `α`. -/
theorem corner88_c (x y z : ℕ) (h1 : x + 2 * z = 1) (h2 : y + 2 * z = 0) :
    x = 1 ∧ y = 0 ∧ z = 0 := by omega

/-! ## The corner step at an `α`-corner

At a target corner of angle `α` the corner tile is unique and its flanks are `{b,c}`, so its
`a`-edge is a chord with both ends on the boundary. Its far side is a single whole `a`, because
`a` has a unique decomposition; the reflected partner would repeat `γ` at a straight junction and
`2γ > π`; so the direct partner is forced, the two together present `β` and `γ` at each end of the
chord, and exactly `α` remains. The unique filler of `α` has flanks `{b,c}`, so the next boundary
edge at either end is a `b` or a `c`, never an `a`. -/

/-- The residue at either end of the corner chord is `α`, whose fill is a single `α`-corner:
`β + γ + α = π` with `γ = 2α+β` reads `(1+2)α + (1+1)β = π`, i.e. `3α + 2β = π`. -/
theorem corner_step_residue (x y z : ℕ) (h1 : x + 2 * z = 1) (h2 : y + z = 0) :
    x = 1 ∧ y = 0 ∧ z = 0 := by omega

/-- One step further the chain branches: the residue `3α+β` admits both `{3α, β}` and `{α, γ}`,
so the forcing stops after the first edge at each corner. -/
theorem corner_step_branches :
    (3 + 2 * 0 = 3 ∧ 1 + 0 = 1) ∧ (1 + 2 * 1 = 3 ∧ 0 + 1 = 1) := by omega

end Erdos634.Frontier
