import Mathlib.Tactic
import Erdos634.OrderForcing

/-!
# The frontier invariant: arithmetic core

The exhaustive search prunes a *frontier* (the uncovered polygons together with the per-side
boundary edge-type counts) by five conditions. Two of them, the area condition and the corner
angle condition, are geometric. The remaining three are arithmetic, and the one that carries the
combinatorial weight is

* **(P2)** every maximal straight run of the uncovered boundary joining two convex corners has
  integral length lying in the numerical semigroup `⟨a,b,c⟩`.

This file fixes that language and records the run lengths that are *gaps*, so that a frontier
carrying one of them is inadmissible. Each gap below is a restatement of a lemma proved in
`OrderForcing`, in the vocabulary the invariant uses.
-/

namespace Erdos634.Frontier

/-- The tile's short edge, `a = ef`. -/
def sideA (e f : ℕ) : ℕ := e * f
/-- The tile's middle edge, `b = f² − e²`. -/
def sideB (e f : ℕ) : ℕ := f * f - e * e
/-- The tile's long edge, `c = f²`. -/
def sideC (e f : ℕ) : ℕ := f * f

/-- Membership in the numerical semigroup generated by the three tile edges. A boundary run of
length `n` can be partitioned into whole tile edges exactly when `inSemi e f n` holds. -/
def inSemi (e f n : ℕ) : Prop := ∃ x y z : ℕ, x * sideA e f + y * sideB e f + z * sideC e f = n

/-- **(P2)**: a list of straight-run lengths is admissible when every entry lies in the
semigroup. -/
def runsOK (e f : ℕ) (runs : List ℕ) : Prop := ∀ n ∈ runs, inSemi e f n

/-- A run whose length is a gap makes the frontier inadmissible. This is the shape in which every
kill below is consumed. -/
theorem runsOK_fail {e f : ℕ} {runs : List ℕ} {n : ℕ} (hmem : n ∈ runs) (hgap : ¬ inSemi e f n) :
    ¬ runsOK e f runs := fun h => hgap (h n hmem)

/-! ## Gap catalogue at `e = 1`

Each entry names the configuration that produces the run, and is proved by the corresponding
lemma of `OrderForcing`. -/

/-- The anchored south cover of a row `c`-edge: after the forced mate-top `a`, a partial right-end
edge would leave a run `n` with `n + f + t = f²` and `0 < t < f`, and no such `n` lies in the
semigroup. -/
theorem gap_south_straddle {f t n : ℕ} (hf : 3 ≤ f) (ht1 : 1 ≤ t) (htf : t < f)
    (hn : n + f + t = f * f) : ¬ inSemi 1 f n := by
  rintro ⟨x, y, z, h⟩
  simp only [sideA, sideB, sideC, one_mul] at h
  refine OrderForcing.south_cover_straddle (x := x) (y := y) (z := z) hf ht1 htf ?_
  have h9 : 9 ≤ f * f := by nlinarith
  obtain ⟨B, hB⟩ : ∃ B, f * f = B + 1 := ⟨f * f - 1, by omega⟩
  rw [hB] at h hn ⊢
  simp only [Nat.add_sub_cancel] at h ⊢
  omega

/-- The east cover of an `X`-cell's `b`-edge, after a leak tile lays its `a` first: the remaining
run `n` satisfies `n + 1 + f = f²` and is a gap. -/
theorem gap_east_cover {f n : ℕ} (hf : 3 ≤ f) (hn : n + 1 + f = f * f) :
    ¬ inSemi 1 f n := by
  rintro ⟨x, y, z, h⟩
  simp only [sideA, sideB, sideC, one_mul] at h
  refine OrderForcing.east_cover_gap (x := x) (y := y) (z := z) hf ?_
  have h9 : 9 ≤ f * f := by nlinarith
  obtain ⟨B, hB⟩ : ∃ B, f * f = B + 1 := ⟨f * f - 1, by omega⟩
  rw [hB] at h hn ⊢
  simp only [Nat.add_sub_cancel] at h ⊢
  omega

/-- Laying a `c` along a chord of length `2b` leaves a run `n` with `n + 2 = f²`, a gap for
`f ≥ 3`; at `f = 2` it equals `a`, the coincidence the `(1,2)` tilings exploit. -/
theorem gap_two_b_minus_c {f n : ℕ} (hf : 3 ≤ f) (hn : n + 2 = f * f) :
    ¬ inSemi 1 f n := by
  rintro ⟨x, y, z, h⟩
  simp only [sideA, sideB, sideC, one_mul] at h
  refine OrderForcing.gap_2b_minus_c (x := x) (y := y) (z := z) hf ?_
  have h9 : 9 ≤ f * f := by nlinarith
  obtain ⟨B, hB⟩ : ∃ B, f * f = B + 1 := ⟨f * f - 1, by omega⟩
  rw [hB] at h hn ⊢
  simp only [Nat.add_sub_cancel] at h ⊢
  omega

/-- The third run of the double-`c` configuration: a direct `β`-slot tile lays its `a` first along
the `2b` chord, and the far side must then partition `2b − a`, i.e. `n + f + 2 = 2f²`. A gap for
every `f ≥ 3`.

With `gap_east_cover` (`b − a`) and `gap_two_b_minus_c` (`2b − c`) this is the full arithmetic core
of the double-`c` kill. At `f = 4` the three runs are `11`, `26`, `14` against `⟨4,15,16⟩` — the
machine-checked instance used in the `(1,4)` argument — so the general statement subsumes it. -/
theorem gap_two_b_minus_a {f n : ℕ} (hf : 3 ≤ f) (hn : n + f + 2 = 2 * (f * f)) :
    ¬ inSemi 1 f n := by
  rintro ⟨x, y, z, h⟩
  simp only [sideA, sideB, sideC, one_mul] at h
  refine OrderForcing.gap_2b_minus_a (x := x) (y := y) (z := z) hf ?_
  omega

/-! ## The `2b` chord of the double-`c` configuration

The three gaps above are consumed by one geometric fact, which the `(1,4)` argument states as a
coordinate computation: with the base corner at the origin, the base along `+x`, and `u` the unit
vector along the equal side, the points `2c·u`, `Q = c·u + (f,0)` and `(2f,0)` are collinear, the
outer segment has length exactly `2b`, and `Q` is its midpoint. The runs the `β`-slot tile leaves on
that chord are then `2b − a` (direct: its `a` is laid first), `b − a` (the stretch remaining to `Q`)
and `2b − c` (mirrored: its `c` crosses `Q`) — precisely the three gaps.

The target's base angle is `β`: for the tile `(f, f²−1, f²)` the law of cosines gives
`cos β = (a²+c²−b²)/(2ac) = (3f²−1)/(2f³)`, which is exactly the isosceles ratio
`((3f²−1)/2)/f³` of the target `(f³, f³, 3f²−1)`. So `u = (cos β, sin β)` and the two hypotheses
below say just that: `2f³·cb = 3f²−1` fixes `cb = cos β`, and `cb² + sb² = 1` fixes `sb = sin β`.

Both identities are polynomial, hence general in `f` — nothing here is special to `f = 4`. -/

/-- **The chord has length `2b`.** `|2c·u − (2f,0)|² = (2b)²`. -/
theorem chord_two_b {f cb sb : ℝ} (hcos : 2 * f ^ 3 * cb = 3 * f ^ 2 - 1)
    (hpyth : cb ^ 2 + sb ^ 2 = 1) :
    (2 * f ^ 2 * cb - 2 * f) ^ 2 + (2 * f ^ 2 * sb) ^ 2 = (2 * (f ^ 2 - 1)) ^ 2 := by
  linear_combination (4 * f ^ 4) * hpyth - 4 * hcos

/-- **`Q` is the midpoint.** `|2c·u − Q|² = b² = |Q − (2f,0)|²`; both halves are the *same*
expression `(f²·cb − f)² + (f²·sb)²`, since `Q − 2c·u = -(f²cb − f, f²sb)` and
`(2f,0) − Q = (f − f²cb, −f²sb)`. Collinearity is then immediate: `Q` is the average of the two
endpoints, so the three points lie on a line. -/
theorem chord_two_b_half {f cb sb : ℝ} (hcos : 2 * f ^ 3 * cb = 3 * f ^ 2 - 1)
    (hpyth : cb ^ 2 + sb ^ 2 = 1) :
    (f ^ 2 * cb - f) ^ 2 + (f ^ 2 * sb) ^ 2 = (f ^ 2 - 1) ^ 2 := by
  linear_combination (f ^ 4) * hpyth - hcos

/-- `Q = c·u + (f,0)` really is the midpoint of `2c·u` and `(2f,0)`, componentwise. Collinearity
of the three points follows, with no hypothesis on `f` at all. -/
theorem chord_midpoint (f cb sb : ℝ) :
    (f ^ 2 * cb + f) = (2 * f ^ 2 * cb + 2 * f) / 2 ∧ (f ^ 2 * sb) = (2 * f ^ 2 * sb + 0) / 2 :=
  ⟨by ring, by ring⟩

/-- **The double-`c` kill: arithmetic core, general in `f`.**

The three runs a `β`-slot tile can leave on the `2b` chord are exactly `b − a`, `2b − a` and
`2b − c`, and none lies in the semigroup for `f ≥ 3`. Packaged as one disjunction, this is the
arithmetic half of escape route 2 of the advance-and-collide conjecture (companion,
`conj:advance`), which asks that a branch with an initial side `c`-block of length `≥ 2` die.

**Status of route 2, stated exactly.** Its ingredients are now all general:

* `first_run_kill` and `through_edge_exclusive` are vertex-figure statements in `(nα, nβ, nγ)`
  alone — they never mention `f`;
* `lem:topjunction` reduces to the signs of `f³ − 3f² + 1` (`f ≥ 3`) and `f³ − 3f² − f + 1`
  (`f ≥ 4`), so it is general with `f = 3` handled separately;
* the chord geometry is `chord_two_b` / `chord_two_b_half` above — polynomial identities;
* the residues are this lemma.

At `f = 4` the residues read `11`, `26`, `14` against `⟨4,15,16⟩`, the machine-checked instance
`gaps_4_15_16`; nothing above is special to that value.

**What is still missing.** The `f = 4` argument runs the case split on one word, `c c aᶠ c`
(the `k = 1` side walk `(fk, 0, f−k)`), with the base word starting `a a` so that `(2f,0)` is a
base junction. For general `f` the double-`c` words are the walks with `1 ≤ k ≤ f−2`, and the base
word of `thm:e1reduce` places its `b` anywhere in positions `3..f`. Route 2 closes in general only
once the same split is run over that whole family — the ingredients are in hand, the enumeration
is not. Route 1 (a deviating `a`-run whose new `c`-chord ends beyond the forced region) is
untouched. -/
theorem double_c_kill {f n : ℕ} (hf : 3 ≤ f)
    (hrun : n + 1 + f = f * f ∨ n + f + 2 = 2 * (f * f) ∨ n + 2 = f * f) :
    ¬ inSemi 1 f n := by
  rcases hrun with h | h | h
  · exact gap_east_cover hf h
  · exact gap_two_b_minus_a hf h
  · exact gap_two_b_minus_c hf h

/-! ## The `jb` chord: escape route 2 at every initial block length

A side whose initial `c`-block has length `j` reaches the point `j c·u`, and the chord from there to
the base point `(jf,0)` has length exactly `jb`, cut into `j` segments of length `b` by the points
`Q_i = i c·u + (j−i)(f,0)`. The `j = 2` case is the chord of the `f = 4` double-`c` kill.

Both facts below are polynomial identities in `f` and `j`, so neither the chord nor the residues
depend on the block length being `2`. -/

/-- **The chord has length `jb`.** `|j c·u − (jf,0)|² = (jb)²`. -/
theorem chord_jb {f j cb sb : ℝ} (hcos : 2 * f ^ 3 * cb = 3 * f ^ 2 - 1)
    (hpyth : cb ^ 2 + sb ^ 2 = 1) :
    (j * f ^ 2 * cb - j * f) ^ 2 + (j * f ^ 2 * sb) ^ 2 = (j * (f ^ 2 - 1)) ^ 2 := by
  linear_combination (j ^ 2 * f ^ 4) * hpyth - j ^ 2 * hcos

/-- **The chord is cut into segments of length `b`.** The point `Q_i = i c·u + (j−i)(f,0)` lies at
distance `(j−i)b` from `j c·u` and `i b` from `(jf,0)`; here in the form that both interior
distances are the same expression scaled, so the `j` pieces are equal. -/
theorem chord_jb_segment {f i cb sb : ℝ} (hcos : 2 * f ^ 3 * cb = 3 * f ^ 2 - 1)
    (hpyth : cb ^ 2 + sb ^ 2 = 1) :
    (i * f ^ 2 * cb - i * f) ^ 2 + (i * f ^ 2 * sb) ^ 2 = (i * (f ^ 2 - 1)) ^ 2 :=
  chord_jb (j := i) hcos hpyth

/-- **The residue on a `jb` chord is a gap.** Whatever edge the `β`-slot tile lays first has length
divisible by `f` (`a = f`, `c = f²`), and `jb` minus any positive multiple of `f` is outside
`⟨a,b,c⟩` for every `1 ≤ j < f`.

Stated subtraction-free as `n + t = j(f² − 1)`. Specializing `(j,t)`: `(1,f)` is `gap_east_cover`,
`(2,f)` is `gap_two_b_minus_a`, `(2,f²)` is `gap_two_b_minus_c`. -/
theorem gap_jb_minus_multiple {f j t n : ℕ} (hf : 3 ≤ f) (hj : 1 ≤ j) (hjf : j < f)
    (ht : 0 < t) (htf : f ∣ t) (hn : n + t = j * (f * f - 1)) :
    ¬ inSemi 1 f n := by
  rintro ⟨x, y, z, h⟩
  simp only [sideA, sideB, sideC, one_mul] at h
  exact OrderForcing.gap_jb_minus_multiple (x := x) (y := y) (z := z) hf hj hjf ht htf (by omega)

/-- The two edges a `β`-slot tile can lay first are `a = f` and `c = f²`, both multiples of `f`, so
the previous theorem applies to each. This is escape route 2 of `conj:advance` at an arbitrary
initial `c`-block length `j`, replacing the single length `j = 2` of the `f = 4` argument. -/
theorem double_c_kill_general {f j n : ℕ} (hf : 3 ≤ f) (hj : 1 ≤ j) (hjf : j < f)
    (hn : n + f = j * (f * f - 1) ∨ n + f * f = j * (f * f - 1)) :
    ¬ inSemi 1 f n := by
  rcases hn with h | h
  · exact gap_jb_minus_multiple hf hj hjf (by omega) ⟨1, by ring⟩ h
  · exact gap_jb_minus_multiple hf hj hjf (by nlinarith) ⟨f, rfl⟩ h

/-! ## Route 1: the escape configuration is rigid

The deviating `a`-run's new `c`-chord starts at the base junction `(f+c,0)` and ends at
`E = c·u + (f+c,0)`. The edge that ought to block it is the second side tile's `c`-edge, running
from `A = c·u` to that tile's third vertex `V = c·u + (c,0)`. Writing `R₁ = c·u + (f,0)` for the
point called `Q` in the `(1,3)` argument, all four lie at the common height `c·sin β`, in the order
`A —a— R₁ —(c−a)— V —a— E` with `|AV| = |R₁E| = c`. The escape is that `E` overshoots `V` by
exactly `a`, for every `f`. -/

/-- **`V` is the second side tile's third vertex.** That tile carries the `a`-edge `AB` on the side,
with `A = c·u` and `B = (c+a)·u`, and is mirrored, so it presents `β` at `A` and its `c`-edge runs
from `A`. The third vertex is then `V = c·u + (c,0)`, and this is the identity that pins it:
`|V − B|² = b²`. (The companion `|V − A|² = c²` is immediate, `V − A` being horizontal of length
`c`.) The cosine hypothesis is doing the work here. -/
theorem side_tile_third_vertex {f cb sb : ℝ} (hcos : 2 * f ^ 3 * cb = 3 * f ^ 2 - 1)
    (hpyth : cb ^ 2 + sb ^ 2 = 1) :
    (f ^ 2 * cb + f ^ 2 - (f ^ 2 + f) * cb) ^ 2 + (f ^ 2 * sb - (f ^ 2 + f) * sb) ^ 2
      = (f ^ 2 - 1) ^ 2 := by
  linear_combination (f ^ 2) * hpyth - hcos

/-- **The spacings.** All four points share the ordinate `c·sin β` by construction (each is
`c·u` plus a horizontal vector), so they are collinear; what carries content is the gaps. Along that
line the four abscissae are `c·cb`, `c·cb + a`, `c·cb + c`,
`c·cb + c + a`, so consecutive gaps are `a`, `c − a`, `a`, and `|AV| = |R₁E| = c`. In particular the
gap `[V,E]` between the blocking edge's end and the chord's endpoint is exactly `a`, which is what
route 1 must exploit. -/
theorem route1_spacings (f cb : ℝ) :
    (f ^ 2 * cb + f) - f ^ 2 * cb = f ∧
    (f ^ 2 * cb + f ^ 2) - (f ^ 2 * cb + f) = f ^ 2 - f ∧
    (f ^ 2 * cb + f ^ 2 + f) - (f ^ 2 * cb + f ^ 2) = f ∧
    (f ^ 2 * cb + f ^ 2) - f ^ 2 * cb = f ^ 2 ∧
    (f ^ 2 * cb + f ^ 2 + f) - (f ^ 2 * cb + f) = f ^ 2 :=
  ⟨by ring, by ring, by ring, by ring, by ring⟩

/-- **The overshoot of `prop:doublec`(iv).** A `c`-edge laid along the chord's last segment, whose
length is exactly `b`, passes the base point by `c − b = e²`, which is positive for every `e`. At
`e = 1` this is the familiar `1`. Combined with the chord descending to the base, the continuation
leaves the target, which is why the `α`-slot flank cannot be a `c`-edge. -/
theorem overshoot_c_sub_b (e f : ℕ) (h : e * e ≤ f * f) :
    (f * f) - (f * f - e * e) = e * e := by omega

/-! ## The wedge-filler hypothesis, and where it fails

Several corner-chain steps fill a wedge of angle exactly `α` with a single `α`-tile, justified in
`lem:wallclimb` by "`α` is the minimal angle". That is not the load-bearing fact. What is needed is
that no two smaller angles fit, i.e. `2β > α`; with `3α + 2β = π` this reads `α < π/4`.

The distinction is not academic. The two conditions disagree: at `(e,f) = (3,4)` one has `b < a`, so
`β` is the minimal angle, yet `α < π/4` still holds and the step survives. Conversely the step does
fail somewhere, and the criterion is exact and integral.

`cos α = 1 − e²/(2f²)`, since `b² + c² − a² = (f²−e²)(2f²−e²)` and `2bc = 2f²(f²−e²)`. So
`α < π/4` iff `2f² − e² > √2 f²`, and squaring (both sides positive as `f > e`) gives the integer
criterion `e⁴ − 4e²f² + 2f⁴ > 0`. It fails on `(4,5), (5,6), (6,7), (7,8), (7,9), (8,9), (9,10),
(9,11), (10,11), (10,13), (11,12), (11,13)` among `e ≤ 11`, `f ≤ 19` — every one a close pair, and
including `(5,6)`, which is `N = 83`. -/

/-- **The closed form of `cos α`.** `(b²+c²−a²)·2f² = (2f²−e²)·2bc` for the family
`(a,b,c) = (ef, f²−e², f²)`, i.e. `cos α = 1 − e²/(2f²)`. At `e = 1` this is `(2f²−1)/(2f²)`. -/
theorem cos_alpha_closed (e f : ℝ) :
    ((f ^ 2 - e ^ 2) ^ 2 + (f ^ 2) ^ 2 - (e * f) ^ 2) * (2 * f ^ 2)
      = (2 * f ^ 2 - e ^ 2) * (2 * (f ^ 2 - e ^ 2) * f ^ 2) := by ring

/-- **The wedge-filler criterion.** `α < π/4` iff `2f² − e² > √2 f²`, which on squaring is the
integer condition below. This is what `lem:wallclimb`'s step actually needs; minimality of `α` is
neither necessary nor what is used. -/
theorem wedge_criterion (e f : ℝ) :
    (2 * f ^ 2 - e ^ 2) ^ 2 - 2 * f ^ 4 = e ^ 4 - 4 * e ^ 2 * f ^ 2 + 2 * f ^ 4 := by ring

/-- **Separated members satisfy it.** `f² > 2ef + e²` is `b > 2a`, and it implies
`e⁴ − 4e²f² + 2f⁴ > 0`, so the wedge step is safe at every separated member; the failures are
confined to close pairs. -/
theorem separated_wedge_ok {e f : ℝ} (he : 0 < e) (hef : e < f)
    (hsep : 2 * e * f + e ^ 2 < f ^ 2) :
    0 < e ^ 4 - 4 * e ^ 2 * f ^ 2 + 2 * f ^ 4 := by
  -- `f² − e² > 2ef`; squaring gives `f⁴ + e⁴ > 6e²f²`, and the claim follows with room to spare.
  have hs : 0 < f ^ 2 - e ^ 2 - 2 * e * f := by linarith
  nlinarith [mul_pos hs hs, sq_nonneg (e * f), sq_nonneg f, mul_pos he (he.trans hef)]

/-- Separated members also have `b > 2a`, hence `a < b`: `α < β` there. Recorded because it is the
edge-inequality form of the separation condition. -/
theorem separated_b_gt_two_a {e f : ℕ} (hsep : 2 * e * f + e * e < f * f) :
    2 * (e * f) < f * f - e * e := by
  have hx : 2 * e * f = 2 * (e * f) := by ring
  omega

/-! ## Close pairs: an exact reduction of the base column

At a close pair the base admits extra columns beyond the walls form, all with `y = e + kf` for some
`k ≥ 1` (companion, `rem:closepairs`), and the difficulty is that no bound on `k` follows from size.
Substituting `y = e + kf` into the base equation collapses it: the whole thing is `f` times a linear
relation in `x` and `z` alone. So for each `k` the surviving columns are the solutions of a
two-variable linear Diophantine equation, not a three-variable search.

Verified against brute enumeration on every close pair with `e ≤ 25`, `f ≤ 59`: 655 surviving
columns, zero violations. Specialising, `k = 1` forces `(x,y,z) = (e,\ e+f,\ 2e-f)`, which exists
exactly when `f ≤ 2e−1`. -/

/-- **The base equation, reduced.** With `y = e + kf` the base relation is `f` times
`x·e + z·f = 2ef − k·b`, where `b = f² − e²`. Stated over `ℤ` as an identity, so the equivalence
for `f ≠ 0` is immediate. -/
theorem base_column_reduction (e f k x z : ℤ) :
    x * (e * f) + (e + k * f) * (f * f - e * e) + z * (f * f) - e * (3 * f * f - e * e)
      = f * (x * e + z * f - (2 * e * f - k * (f * f - e * e))) := by ring

/-- **The `k = 1` column is forced.** In the reduced equation with `k = 1` and `x = e`, the
remaining unknown is pinned: `z = 2e − f`. So that column exists only for `f ≤ 2e − 1`. -/
theorem base_column_k_one (e f z : ℤ) (hf : f ≠ 0)
    (h : e * e + z * f = 2 * e * f - (f * f - e * e)) : z = 2 * e - f := by
  have hfz : (z - (2 * e - f)) * f = 0 := by linear_combination h
  rcases mul_eq_zero.mp hfz with h0 | h0
  · linarith
  · exact absurd h0 hf

/-- **An explicit bound on `k`.** Since `x, z ≥ 1`, the reduced equation forces
`k·b ≤ 2ef − e − f`. The size bound of `rem:closepairs` gives only `k·b ≤ 2ef`, so this is the same
shape sharpened by the two unconditional positivity constraints; it is still not `k = 0`. -/
theorem base_column_k_bound (e f k x z : ℤ) (hx : 1 ≤ x) (hz : 1 ≤ z) (he : 0 < e) (hf : 0 < f)
    (hkey : x * e + z * f = 2 * e * f - k * (f * f - e * e)) :
    k * (f * f - e * e) ≤ 2 * e * f - e - f := by
  nlinarith [mul_le_mul_of_nonneg_right hx (le_of_lt he),
             mul_le_mul_of_nonneg_right hz (le_of_lt hf)]

/-- **The reduced equation pins `x` modulo `f`.** From `xe + zf = 2ef − kb` one gets
`e(x − ke) = f(2e − kf − z)`, so `f ∣ e(x − ke)`, and coprimality gives `f ∣ x − ke`. Hence for each
`k` the admissible `x` form a single residue class mod `f`, and the surviving columns of that `k`
are the members of that class with `z = (2ef − kb − xe)/f ≥ 1` and `x + z ≥ 4`.

That criterion is exact: over every close pair with `e ≤ 25`, `f ≤ 59` it reproduces the surviving
`k`-set at all 198 members carrying survivors, with no exception. In particular the 12 members where
the sharp bound is not attained are solvability failures of `xe + zf = R` — a Frobenius condition on
`⟨e,f⟩` — rather than a further geometric filter. -/
theorem column_x_congruence (e f k x z : ℤ) (hco : IsCoprime f e)
    (h : x * e + z * f = 2 * e * f - k * (f * f - e * e)) : f ∣ x - k * e := by
  have key : e * (x - k * e) = f * (2 * e - k * f - z) := by linear_combination h
  exact hco.dvd_of_dvd_mul_left ⟨2 * e - k * f - z, key.symm ▸ key⟩

/-- **At most one surviving column per `k`.** For fixed `k` the solutions of `xe + zf = R` with
`x` in the class of `column_x_congruence` form a chain `x = x₀ + tf`, `z = z₀ − te`, so there are
`⌊(z₀−1)/e⌋ + 1` of them with `z ≥ 1`, and exactly one when `z₀ ≤ e`. Writing `ke = qf + r` that is
equivalent to `e(1+q) ≤ kf`, which is this lemma.

The proof needs neither coprimality nor the close-pair hypothesis: since `e < f` we have
`ke/f < k`, so `q ≤ k−1` and `1 + q ≤ k`, whence `e(1+q) ≤ ek < fk`. -/
theorem one_column_per_k {e f k q : ℕ} (he : 0 < e) (hef : e < f) (hk : 1 ≤ k)
    (hq : q * f ≤ k * e) (hq' : k * e < (q + 1) * f) : e * (1 + q) ≤ k * f := by
  have h1 : k * e < k * f := by nlinarith
  have hqk : q < k := by nlinarith
  have h2 : 1 + q ≤ k := by omega
  have h3 : e * (1 + q) ≤ e * k := Nat.mul_le_mul_left e h2
  nlinarith

/-- **The sharp `k`-bound.** The previous bound used only `x, z ≥ 1`. The corner parallelogram also
forces `x + z ≥ 4` (`cornerpara_filter`), and since `e < f` the minimum of `xe + zf` under
`x, z ≥ 1`, `x + z ≥ 4` sits at `(x,z) = (3,1)`, giving `3e + f` rather than `e + f`. Hence

  `k·b ≤ 2ef − 3e − f`,

better than `k·b ≤ 2ef − e − f` by `2e`. Checked against brute enumeration on every close pair with
`e ≤ 25`, `f ≤ 59`: no violation, and the bound is *attained* — equal to the largest surviving `k` —
at 186 of the 198 members carrying survivors. With one surviving column per `k` (observed on all 655
columns, not proved), this describes the surviving set completely. -/
theorem k_bound_sharp (e f k x z : ℤ) (he : 0 < e) (hef : e < f)
    (hx : 1 ≤ x) (hz : 1 ≤ z) (hxz : 4 ≤ x + z)
    (hkey : x * e + z * f = 2 * e * f - k * (f * f - e * e)) :
    k * (f * f - e * e) ≤ 2 * e * f - 3 * e - f := by
  -- `xe + zf ≥ e + f + (x−1+z−1)e ≥ 3e + f`, using `f > e > 0`
  nlinarith [mul_le_mul_of_nonneg_left (le_of_lt hef) (by linarith : (0:ℤ) ≤ z - 1),
             mul_nonneg (by linarith : (0:ℤ) ≤ x - 1) (le_of_lt he)]

/-- **Where `k ≥ 2` is already impossible.** Combining the bound `k·b ≤ 2ef − e − f` with `k ≥ 1`:
if `2b` exceeds that right-hand side then `k = 1` outright. The criterion
`2(f²−e²) > 2ef − e − f` is asymptotically `f > eφ`, `φ` the golden ratio, and it holds at 84 of the
198 close-pair members carrying survivors (`e ≤ 25`, `f ≤ 59`), covering 84 of the 655 columns. At
those members there is nothing for a `k ≥ 2` argument to kill. -/
theorem k_eq_one_of_bound (e f k B : ℤ) (hk : 1 ≤ k) (hb : 0 < f * f - e * e)
    (hbound : k * (f * f - e * e) ≤ B)
    (hgap : B < 2 * (f * f - e * e)) : k = 1 := by
  by_contra hne
  have h2 : 2 ≤ k := by omega
  nlinarith [mul_le_mul_of_nonneg_right h2 (le_of_lt hb)]

/-! ## The close-pair base columns, assembled

The pieces above combine into one statement about the extra columns at a close pair. -/

/-- **Characterisation of the extra base columns.** Let `y = e + kf` with `k ≥ 1`, and let
`(x,y,z)` be a base column surviving the two unconditional positivity filters and the corner
parallelogram (`x, z ≥ 1`, `x + z ≥ 4`). Then the three-variable base equation is equivalent to a
two-variable one, `x` is pinned modulo `f`, and `k` is bounded:

* `x·e + z·f = 2ef − k·b`,
* `f ∣ x − ke`,
* `k·b ≤ 2ef − 3e − f`,

with `b = f² − e²`. -/
theorem close_pair_column {e f k x z : ℤ} (he : 0 < e) (hef : e < f) (hf : f ≠ 0)
    (hco : IsCoprime f e) (hx : 1 ≤ x) (hz : 1 ≤ z) (hxz : 4 ≤ x + z)
    (hbase : x * (e * f) + (e + k * f) * (f * f - e * e) + z * (f * f)
             = e * (3 * f * f - e * e)) :
    x * e + z * f = 2 * e * f - k * (f * f - e * e)
    ∧ f ∣ x - k * e
    ∧ k * (f * f - e * e) ≤ 2 * e * f - 3 * e - f := by
  have hid := base_column_reduction e f k x z
  rw [hbase] at hid
  simp only [sub_self] at hid
  have hred : x * e + z * f = 2 * e * f - k * (f * f - e * e) := by
    rcases mul_eq_zero.mp hid.symm with h0 | h0
    · exact absurd h0 hf
    · linarith
  exact ⟨hred, column_x_congruence e f k x z hco hred,
         k_bound_sharp e f k x z he hef hx hz hxz hred⟩

/-- **Uniqueness for a given `k`.** Two columns with the same `k` coincide. The hypotheses `z ≤ e`
are what `one_column_per_k` supplies: the least admissible `x` in the residue class carries
`z ≤ e`, and any larger member of the class would force `z ≤ 0`. -/
theorem close_pair_column_unique {e f k x z x' z' : ℤ} (he : 0 < e) (hf : f ≠ 0)
    (hco : IsCoprime f e) (hze : z ≤ e) (hze' : z' ≤ e) (hz : 1 ≤ z) (hz' : 1 ≤ z')
    (h : x * e + z * f = 2 * e * f - k * (f * f - e * e))
    (h' : x' * e + z' * f = 2 * e * f - k * (f * f - e * e)) : x = x' ∧ z = z' := by
  have hkey : (x - x') * e = (z' - z) * f := by linarith
  have hdvd : f ∣ x - x' := hco.dvd_of_dvd_mul_left ⟨z' - z, by linarith [hkey]⟩
  obtain ⟨t, ht⟩ := hdvd
  have hcancel : f * (t * e) = f * (z' - z) := by
    have : (x - x') * e = (f * t) * e := by rw [ht]
    linarith [hkey, this]
  have hte : t * e = z' - z := mul_left_cancel₀ hf hcancel
  have ht0 : t = 0 := by
    rcases lt_trichotomy t 0 with hlt | heq | hgt
    · nlinarith
    · exact heq
    · nlinarith
  rw [ht0, mul_zero] at ht
  rw [ht0, zero_mul] at hte
  exact ⟨by linarith, by linarith⟩

/-! ## The sharp criterion: which `k` actually carry a column

`k_bound_sharp` bounds `k` but does not decide it: at `(8,17)` it permits `k = 1` while no column
exists, and it over-permits at 551 of the 1558 close pairs with `e ≤ 60`. The gap is that the bound
ignores the residue class of `x`. Writing the least positive member of that class as
`x = ke − mf` with `1 ≤ x ≤ f`, the two facts combine into an exact test. -/

/-- The identity behind the criterion: with `x = ke − mf` the quantity whose sign decides `z ≥ 1`
factors through `f`. -/
theorem column_criterion_identity (e f k m : ℤ) :
    (k * e - m * f) * e + f + k * (f * f - e * e) - 2 * e * f
      = f * (k * f - (m + 2) * e + 1) := by ring

/-- **The sharp criterion.** If the column's `x` is the least positive member of its class,
`x = ke − mf`, then `z ≥ 1` holds exactly when `kf ≤ (m+2)e − 1`. Verified against brute
enumeration on all 17296 close pairs with `e ≤ 200`, covering 67218 columns: no disagreement
(`code/close_pair_columns.py`). -/
theorem column_criterion {e f k m x z : ℤ} (hf : 0 < f) (hz : 1 ≤ z)
    (hx : x = k * e - m * f)
    (hkey : x * e + z * f = 2 * e * f - k * (f * f - e * e)) :
    k * f ≤ (m + 2) * e - 1 := by
  have hid : x * e + f + k * (f * f - e * e) - 2 * e * f
      = f * (k * f - (m + 2) * e + 1) := by
    rw [hx]; exact column_criterion_identity e f k m
  have hle : x * e + f + k * (f * f - e * e) - 2 * e * f = f * (1 - z) := by linarith
  have hneg : f * (k * f - (m + 2) * e + 1) ≤ 0 := by
    rw [← hid, hle]; nlinarith
  by_contra hc
  push_neg at hc
  nlinarith

/-- **At `k = 1` the criterion reads `f ≤ 2e − 1`.** Since `1 ≤ e < f`, the least positive member
of the class of `e` modulo `f` is `e` itself, so `m = 0`. Consequently a member with `f ≥ 2e`
carries no extra column at all: this clears 5065 of the 17296 close pairs with `e ≤ 200`, and it
covers every `e = 1` member vacuously, matching the `e = 1` theory. -/
theorem k_one_forces_f_le_two_e_sub_one {e f z : ℤ} (hf : 0 < f) (hz : 1 ≤ z)
    (hkey : e * e + z * f = 2 * e * f - (f * f - e * e)) :
    f ≤ 2 * e - 1 := by
  have h : f * z = f * (2 * e - f) := by linear_combination hkey
  have hzv : z = 2 * e - f := mul_left_cancel₀ (ne_of_gt hf) h
  linarith

/-- The residue index moves by `0` or `1` per step in `k`: the least positive representatives
advance by `e`, and `0 < e < f`. -/
theorem residue_step {e f k m m' x x' : ℤ} (he : 0 < e) (hef : e < f)
    (hx : x = k * e - m * f) (hx' : x' = (k + 1) * e - m' * f)
    (h1 : 1 ≤ x) (h2 : x ≤ f) (h1' : 1 ≤ x') (h2' : x' ≤ f) :
    m ≤ m' ∧ m' ≤ m + 1 := by
  have hf0 : 0 < f := lt_trans he hef
  have hd : x' - x = e + (m - m') * f := by rw [hx, hx']; ring
  constructor
  · by_contra hc
    push_neg at hc
    have hge : (1:ℤ) ≤ m - m' := by omega
    have := mul_le_mul_of_nonneg_right hge (le_of_lt hf0)
    rw [one_mul] at this
    linarith
  · by_contra hc
    push_neg at hc
    have hle : m - m' ≤ -2 := by omega
    have := mul_le_mul_of_nonneg_right hle (le_of_lt hf0)
    linarith

/-- **The criterion's slack strictly decreases in `k`.** Writing `g k = (m+2)e − 1 − kf` for the
slack, one step costs at least `f − e > 0`. Hence `{k : g k ≥ 0}` is an initial segment: the
admissible `k` are `1, …, K` with no gaps, and `K ≤ 1 + ⌊(2e−1−f)/(f−e)⌋`. Checked on all 17296
close pairs with `e ≤ 200`: the surviving set is an initial segment in every one, and the bound on
`K` is never violated. -/
theorem g_strict_drop {e f k m m' : ℤ} (he : 0 < e) (hmm' : m' ≤ m + 1) :
    ((m' + 2) * e - 1 - (k + 1) * f) ≤ ((m + 2) * e - 1 - k * f) - (f - e) := by
  have h : m' - m ≤ 1 := by omega
  nlinarith [mul_le_mul_of_nonneg_right h (le_of_lt he)]

/-! ## Extending the base trichotomy past separation

`base_trichotomy` is stated for separated members (`f² > 2ef + e²`); separation is used only to
exclude base columns with `y > e`. Those are excluded already under `f > 2e`. The criterion above
cannot be reused here: it assumes `x, z ≥ 1`, whereas the trichotomy allows `x = 0` and `z = 0`.
The bound `f > 2e` is sharp — coprimality makes `f = 2e` possible only at `(1,2)`, and that member
really does carry the extra column `(1,3,0)`, which escapes exactly at `z = 0`. -/

/-- The identity in the `z ≥ 0` regime: no `+f` term, so the factor is `kf − (m+2)e`. -/
theorem column_identity_nonneg (e f k m : ℤ) :
    (k * e - m * f) * e + k * (f * f - e * e) - 2 * e * f
      = f * (k * f - (m + 2) * e) := by ring

/-- **No base column with `y > e` when `f > 2e`**, with `x, z ≥ 0` only. Writing `y = e + kf` with
`k ≥ 1` and `x = ke − mf`, the hypotheses force `2m < k` and `2k < m + 2`, which is impossible.
Checked by structured enumeration on all 165038 members with `f > 2e`, `e ≤ 300`: no decomposition
outside the three of `base_trichotomy` (`code/close_pair_columns.py` shares the enumerator). -/
theorem no_extra_column_of_f_gt_two_e {e f k m x z : ℤ}
    (he : 0 < e) (hf2 : 2 * e < f) (hk : 1 ≤ k)
    (hx0 : 0 ≤ x) (hx : x = k * e - m * f) (hz : 0 ≤ z)
    (hkey : x * e + z * f = 2 * e * f - k * (f * f - e * e)) : False := by
  have hf : 0 < f := by linarith
  have hmf : m * f ≤ k * e := by rw [hx] at hx0; linarith
  -- `z ≥ 0` becomes `k*f ≤ (m+2)*e`
  have hid : x * e + k * (f * f - e * e) - 2 * e * f = f * (k * f - (m + 2) * e) := by
    rw [hx]; exact column_identity_nonneg e f k m
  have hle : x * e + k * (f * f - e * e) - 2 * e * f ≤ 0 := by nlinarith
  have hkf : k * f ≤ (m + 2) * e := by
    rw [hid] at hle; nlinarith
  -- `2m < k`
  have h2m : 2 * m < k := by
    by_cases hm : 0 < m
    · nlinarith [mul_lt_mul_of_pos_left hf2 hm]
    · have hm' : m ≤ 0 := not_lt.mp hm
      nlinarith
  -- `f > 2e` and `k ≥ 1` give `2ke < kf ≤ (m+2)e`, hence `2k < m+2`; with `2m ≤ k-1`, `k < 1`
  nlinarith [mul_lt_mul_of_pos_left hf2 (lt_of_lt_of_le zero_lt_one hk)]

/-- The catalogue is non-vacuous in the other direction: the run `n` with `n + f = f²` *is* in the
semigroup, being `f − 1` copies of `a`. A predicate that excluded everything would say nothing. -/
theorem south_cover_mem {f n : ℕ} (hf : 3 ≤ f) (hn : n + f = f * f) : inSemi 1 f n := by
  obtain ⟨g, hg⟩ : ∃ g, f = g + 1 := ⟨f - 1, by omega⟩
  subst hg
  refine ⟨g, 0, 0, ?_⟩
  simp only [sideA, sideB, sideC, Nat.zero_mul, Nat.add_zero, one_mul]
  have hring : g * (g + 1) + (g + 1) = (g + 1) * (g + 1) := by ring
  omega

/-! ## Corner rigidity for the two open instances at `N = 84` and `N = 88`

Both remaining instances below `N = 91` have every target corner filled in exactly one way, so the
corner tiles are forced in angle. The fill equations use the branch relation of each tile.

* `N = 84`: tile `(2,3,4)`, target `(24,24,42)`, with `γ = 2α+β` and `3α+2β = π`. The corners are
  `α`, `α` and `α+2β`.
* `N = 88`: tile `(3,5,7)`, target `(21,55,56)`, with `γ = 2π/3` and `α+β = π/3`, so `γ = 2α+2β`.
  The corners are `α`, `2β` and `2α+β`.
-/

/-- `N = 84`: the apex angle `α+2β` is filled only by `{α, β, β}`. -/
theorem corner84_apex (x y z : ℕ) (h1 : x + 2 * z = 1) (h2 : y + z = 2) :
    x = 1 ∧ y = 2 ∧ z = 0 := by omega

/-- `N = 84`: each base angle `α` is filled only by a single `α`. -/
theorem corner84_base (x y z : ℕ) (h1 : x + 2 * z = 1) (h2 : y + z = 0) :
    x = 1 ∧ y = 0 ∧ z = 0 := by omega

/-- `N = 88`: the angle `2α+β` is filled only by `{α, α, β}`. -/
theorem corner88_a (x y z : ℕ) (h1 : x + 2 * z = 2) (h2 : y + 2 * z = 1) :
    x = 2 ∧ y = 1 ∧ z = 0 := by omega

/-- `N = 88`: the angle `2β` is filled only by two `β`-corners. -/
theorem corner88_b (x y z : ℕ) (h1 : x + 2 * z = 0) (h2 : y + 2 * z = 2) :
    x = 0 ∧ y = 2 ∧ z = 0 := by omega

/-- `N = 88`: the angle `α` is filled only by a single `α`. -/
theorem corner88_c (x y z : ℕ) (h1 : x + 2 * z = 1) (h2 : y + 2 * z = 0) :
    x = 1 ∧ y = 0 ∧ z = 0 := by omega

/-! ## The corner step at an `α`-corner

At a target corner of angle `α` the corner tile is unique and its flanks are `{b,c}`, so its
`a`-edge is a chord with both ends on the boundary. Its far side is a single whole `a`, because
`a` has a unique decomposition; the reflected partner would repeat `γ` at a straight junction and
`2γ > π`; so the direct partner is forced, the two together present `β` and `γ` at each end of the
chord, and exactly `α` remains. The unique filler of `α` has flanks `{b,c}`, so the next boundary
edge at either end is a `b` or a `c`, never an `a`. -/

/-- The residue at either end of the corner chord is `α`, whose fill is a single `α`-corner:
`β + γ + α = π` with `γ = 2α+β` reads `(1+2)α + (1+1)β = π`, i.e. `3α + 2β = π`. -/
theorem corner_step_residue (x y z : ℕ) (h1 : x + 2 * z = 1) (h2 : y + z = 0) :
    x = 1 ∧ y = 0 ∧ z = 0 := by omega

/-- One step further the chain branches: the residue `3α+β` admits both `{3α, β}` and `{α, γ}`,
so the forcing stops after the first edge at each corner. -/
theorem corner_step_branches :
    (3 + 2 * 0 = 3 ∧ 1 + 0 = 1) ∧ (1 + 2 * 1 = 3 ∧ 0 + 1 = 1) := by omega

end Erdos634.Frontier
