-- PgramTiling52.lean — zero-axiom kernel verification of a parallelogram tiling certificate (Erdos #634).
-- 52 copies of the tile (3, 8, 9) tile the parallelogram with corners [(0, 0), (156, 0), (234, 24), (78, 24)] (scaled by 6 into
-- Z[sqrt35]; a corner (x,y) denotes the point x + y*sqrt35). Kernel checks: (C1) squared side
-- multiset [324, 2304, 2916]; (C2) CCW + vertices in the closed quad (4 half-planes); (C3) an explicit
-- separating edge-line per pair (1326 pairs) => disjoint interiors; (C4) signed 2-areas sum
-- to the quad's. Generated by gencert_quad.py, which re-checks all four exactly in Python first.
-- No imports, no axioms.
namespace PgramTiling52
abbrev ZD := Int × Int
abbrev Pt := Int × Int × Int × Int
def zmul (u v : ZD) : ZD := (u.1*v.1 + 35*u.2*v.2, u.1*v.2 + u.2*v.1)
def zsub (u v : ZD) : ZD := (u.1 - v.1, u.2 - v.2)
def zadd (u v : ZD) : ZD := (u.1 + v.1, u.2 + v.2)
def znonneg (z : ZD) : Bool :=
  if 0 <= z.1 then (if 0 <= z.2 then true else 35*z.2*z.2 <= z.1*z.1)
  else (if z.2 < 0 then false else z.1*z.1 <= 35*z.2*z.2)
def znonpos (z : ZD) : Bool := znonneg (-z.1, -z.2)
def zpos (z : ZD) : Bool := !(znonpos z)
def px (p : Pt) : ZD := (p.1, p.2.1)
def py (p : Pt) : ZD := (p.2.2.1, p.2.2.2)
def cross (o a b : Pt) : ZD :=
  zsub (zmul (zsub (px a) (px o)) (zsub (py b) (py o))) (zmul (zsub (py a) (py o)) (zsub (px b) (px o)))
def dist2 (p q : Pt) : ZD :=
  zadd (zmul (zsub (px q) (px p)) (zsub (px q) (px p))) (zmul (zsub (py q) (py p)) (zsub (py q) (py p)))
abbrev Tri := Pt × Pt × Pt
def t1 (t : Tri) : Pt := t.1
def t2 (t : Tri) : Pt := t.2.1
def t3 (t : Tri) : Pt := t.2.2
def congOK (t : Tri) : Bool :=
  let d1 := dist2 (t1 t) (t2 t); let d2 := dist2 (t2 t) (t3 t); let d3 := dist2 (t3 t) (t1 t)
  let s : List ZD := [d1, d2, d3]
  s.contains ((324:Int),(0:Int)) && s.contains ((2304:Int),(0:Int)) && s.contains ((2916:Int),(0:Int))
  && d1.2 == 0 && d2.2 == 0 && d3.2 == 0 && (d1.1 + d2.1 + d3.1 == 5544)
def q1 : Pt := (0,0,0,0)
def q2 : Pt := (156,0,0,0)
def q3 : Pt := (234,0,0,24)
def q4 : Pt := (78,0,0,24)
def insideOK (t : Tri) : Bool :=
  zpos (cross (t1 t) (t2 t) (t3 t)) &&
  [t1 t, t2 t, t3 t].all (fun v =>
    znonneg (cross q1 q2 v) && znonneg (cross q2 q3 v) &&
    znonneg (cross q3 q4 v) && znonneg (cross q4 q1 v))
def sepBy (P Q : Pt) (A B : Tri) : Bool :=
  let sA := [t1 A, t2 A, t3 A].map (fun v => cross P Q v)
  let sB := [t1 B, t2 B, t3 B].map (fun v => cross P Q v)
  (sA.all znonneg && sB.all znonpos) || (sA.all znonpos && sB.all znonneg)
def edgeOf (t : Tri) (e : Nat) : Pt × Pt :=
  if e == 0 then (t1 t, t2 t) else if e == 1 then (t2 t, t3 t) else (t3 t, t1 t)
def area2 (t : Tri) : ZD := cross (t1 t) (t2 t) (t3 t)
def area2target : ZD := ((0:Int), (7488:Int))
def tiles : List Tri := [
  ((0,0,0,0), (18,0,0,0), (26,0,0,8)),
  ((18,0,0,0), (36,0,0,0), (44,0,0,8)),
  ((18,0,0,0), (44,0,0,8), (26,0,0,8)),
  ((36,0,0,0), (54,0,0,0), (62,0,0,8)),
  ((36,0,0,0), (62,0,0,8), (44,0,0,8)),
  ((54,0,0,0), (102,0,0,0), (105,0,0,3)),
  ((54,0,0,0), (71,0,0,1), (63,0,0,9)),
  ((102,0,0,0), (120,0,0,0), (128,0,0,8)),
  ((102,0,0,0), (128,0,0,8), (110,0,0,8)),
  ((120,0,0,0), (138,0,0,0), (146,0,0,8)),
  ((120,0,0,0), (146,0,0,8), (128,0,0,8)),
  ((138,0,0,0), (156,0,0,0), (164,0,0,8)),
  ((138,0,0,0), (164,0,0,8), (146,0,0,8)),
  ((156,0,0,0), (182,0,0,8), (164,0,0,8)),
  ((71,0,0,1), (88,0,0,2), (80,0,0,10)),
  ((71,0,0,1), (80,0,0,10), (63,0,0,9)),
  ((88,0,0,2), (105,0,0,3), (97,0,0,11)),
  ((88,0,0,2), (97,0,0,11), (80,0,0,10)),
  ((105,0,0,3), (114,0,0,12), (97,0,0,11)),
  ((26,0,0,8), (44,0,0,8), (52,0,0,16)),
  ((44,0,0,8), (62,0,0,8), (70,0,0,16)),
  ((44,0,0,8), (70,0,0,16), (52,0,0,16)),
  ((110,0,0,8), (128,0,0,8), (136,0,0,16)),
  ((110,0,0,8), (136,0,0,16), (118,0,0,16)),
  ((128,0,0,8), (146,0,0,8), (154,0,0,16)),
  ((128,0,0,8), (154,0,0,16), (136,0,0,16)),
  ((146,0,0,8), (164,0,0,8), (172,0,0,16)),
  ((146,0,0,8), (172,0,0,16), (154,0,0,16)),
  ((164,0,0,8), (182,0,0,8), (190,0,0,16)),
  ((164,0,0,8), (190,0,0,16), (172,0,0,16)),
  ((182,0,0,8), (208,0,0,16), (190,0,0,16)),
  ((63,0,0,9), (80,0,0,10), (72,0,0,18)),
  ((80,0,0,10), (97,0,0,11), (89,0,0,19)),
  ((80,0,0,10), (89,0,0,19), (72,0,0,18)),
  ((97,0,0,11), (114,0,0,12), (106,0,0,20)),
  ((97,0,0,11), (106,0,0,20), (89,0,0,19)),
  ((114,0,0,12), (123,0,0,21), (106,0,0,20)),
  ((52,0,0,16), (70,0,0,16), (78,0,0,24)),
  ((118,0,0,16), (136,0,0,16), (144,0,0,24)),
  ((118,0,0,16), (144,0,0,24), (126,0,0,24)),
  ((136,0,0,16), (154,0,0,16), (162,0,0,24)),
  ((136,0,0,16), (162,0,0,24), (144,0,0,24)),
  ((154,0,0,16), (172,0,0,16), (180,0,0,24)),
  ((154,0,0,16), (180,0,0,24), (162,0,0,24)),
  ((172,0,0,16), (190,0,0,16), (198,0,0,24)),
  ((172,0,0,16), (198,0,0,24), (180,0,0,24)),
  ((190,0,0,16), (208,0,0,16), (216,0,0,24)),
  ((190,0,0,16), (216,0,0,24), (198,0,0,24)),
  ((208,0,0,16), (234,0,0,24), (216,0,0,24)),
  ((72,0,0,18), (123,0,0,21), (75,0,0,21)),
  ((75,0,0,21), (123,0,0,21), (126,0,0,24)),
  ((75,0,0,21), (126,0,0,24), (78,0,0,24))
]
def wit : List (Bool × Nat) := [
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,0), (true,1),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,0), (true,1),
  (true,0), (true,0), (true,0), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (false,2), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,0), (false,2), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,0),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,0),
  (true,1), (true,0), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0),
  (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,0), (true,0), (true,0),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,0), (true,1), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,1), (true,0), (true,0), (true,0), (true,1),
  (true,1), (true,1), (true,2), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,0), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,1), (true,0),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,0), (true,1), (true,0), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2),
  (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,0), (true,0), (true,0), (true,1), (false,1), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,1), (true,0), (true,1), (true,0), (true,0), (true,0), (true,1), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1),
  (true,2), (true,1), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (false,0), (false,0), (false,0), (true,0),
  (true,1), (true,2), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,1), (true,1), (true,1), (true,0), (true,1), (true,0), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (false,2), (true,0), (false,2), (true,0), (true,0), (true,0),
  (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1),
  (true,0), (true,1), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1),
  (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,2), (true,2), (true,2), (true,0), (true,0), (true,0), (true,0), (true,0), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,1), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,0), (true,0), (true,0), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,1),
  (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,2), (true,1), (true,2), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1),
  (true,1), (true,1), (true,2), (true,2), (true,2), (true,0), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,0), (true,1), (true,0),
  (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,1), (true,1), (true,1),
  (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (false,0), (false,0), (false,0), (true,0), (true,0), (true,0), (false,1), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,2), (true,1), (true,2),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (false,0),
  (false,0), (false,0), (true,0), (true,2), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,2), (true,0), (true,0), (true,0), (true,0), (true,0),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2),
  (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,2), (true,2), (true,2),
  (true,2), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,0),
  (true,0), (true,0), (true,0), (true,0), (true,0), (true,0), (true,2), (true,2), (true,2), (true,2), (true,1), (true,1),
  (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,0), (true,0), (true,0), (true,0), (true,0), (true,2),
  (true,2), (true,2), (true,2), (true,1), (true,1), (true,1), (true,2), (true,2), (true,2), (true,0), (true,0), (true,0),
  (true,2), (true,2), (true,2), (true,2), (true,1), (true,2), (true,2), (true,2), (true,0), (true,2), (true,2), (true,2),
  (true,2), (true,2), (true,2), (true,1), (true,1), (true,2)
]
def pairSep (A B : Tri) (w : Bool × Nat) : Bool :=
  let pq := edgeOf (if w.1 then A else B) w.2
  sepBy pq.1 pq.2 A B
def checkPairs : List Tri → List (Bool × Nat) → Bool
  | [], ws => ws.isEmpty
  | t :: rest, ws =>
      let n := rest.length
      (ws.take n).length == n
      && (List.zip rest (ws.take n)).all (fun (u, w) => pairSep t u w)
      && checkPairs rest (ws.drop n)
def zsum (l : List ZD) : ZD := l.foldl zadd ((0:Int),(0:Int))
def checkAll : Bool :=
  tiles.length == 52 && tiles.all congOK && tiles.all insideOK
  && checkPairs tiles wit && zsum (tiles.map area2) == area2target
set_option maxRecDepth 16384 in
theorem pgramtiling52_certificate : checkAll = true := by decide
end PgramTiling52
