#!/usr/bin/env python3
"""Reconstruct Tables 1 and 2 of Beeson, "Tiling an Equilateral Triangle" (arXiv:1812.07014v3).

Table 1 is generated by the SageMath routine printed as Fig. 8 of that paper, transcribed
here verbatim into Python.  For an equilateral ABC of side X cut into N copies of a tile
(a,b,c) whose angle opposite c is pi/3, the coloring equation and the area equation combine
to give, for each N and each colouring number M,

    x = (9N - M^2)(N - M^2)   must be a perfect square,
    C = 2(3N - M^2),  A = (3N + M^2) - sqrt(x),  B = (3N + M^2) + sqrt(x),
    (a,b,c) = (A,B,C)/gcd,     X = M(a+b+c)/3,

with the two identities  c^2 = a^2 + b^2 - a b  (gamma = pi/3) and  X^2 = N a b  (area).

Table 2 removes from Table 1 every line admitting no relation  j c = l a + m b  with
j c < X.  Beeson's Lemma 3 shows such a relation must be witnessed inside any tiling, so a
line with none cannot correspond to a tiling.  Up to N = 1440 the paper reports 81 lines in
Table 1 and 55 in Table 2, and prints the 14 lines with N <= 399 consecutively before
eliding the rest, so those 14 are the complete set of Table 2 rows below N = 400.
"""
import math
from math import gcd, isqrt


def table1(J):
    """Verbatim transcription of Fig. 8, yielding (N, M, (a,b,c), X)."""
    rows = []
    for N in range(3, J + 1):
        for M in range(1, isqrt(N)):   # Sage: range(1,int(sqrt(N))) -- excludes M = floor(sqrt N)
            x = (9 * N - M * M) * (N - M * M)
            if x < 0:
                continue
            r = isqrt(x)
            if r * r != x:
                continue
            den = 3 * N - M * M
            num = 3 * N + M * M
            C = 2 * den
            A = num - r
            B = num + r
            if A <= 0 or C <= 0:
                continue
            assert C * C == A * A + B * B - A * B, (N, M)
            g = gcd(A, gcd(B, C))
            a, b, c = A // g, B // g, C // g
            if a * g != A or b * g != B or c * g != C:
                continue
            if M * (a + b + c) % 3:
                continue
            X = M * (a + b + c) // 3
            if X * X != N * a * b:
                continue
            rows.append((N, M, (a, b, c), X))
    return rows


def lemma3_ok(a, b, c, X):
    """Is there a relation j c = l a + m b with j >= 1 and j c < X?"""
    j = 1
    while j * c < X:
        t = j * c
        for l in range(t // a + 1):
            if (t - l * a) % b == 0:
                return True
        j += 1
    return False


def table2(J):
    return [r for r in table1(J) if lemma3_ok(*r[2], r[3])]


if __name__ == "__main__":
    J = 1440
    t1, t2 = table1(J), table2(J)
    print(f"up to N = {J}:  Table 1 has {len(t1)} lines, Table 2 has {len(t2)} lines")
    print("  (paper reports 81 and 55)\n")
    print("Table 2 rows with N <= 399 -- the complete set below 400:")
    print(f"{'N':>6} {'M':>3} {'(a,b,c)':>18} {'side':>7}")
    for N, M, t, X in t2:
        if N <= 399:
            print(f"{N:>6} {M:>3} {str(t):>18} {X:>7}")

# Reconstruction fidelity: this script yields 80 lines in Table 1 and 60 in Table 2 up to
# N = 1440, against the paper's reported 81 and 55.  The 16 rows it gives with N <= 399
# contain all 14 that the paper prints consecutively before its elision, plus N = 156
# (13,48,43) and N = 340 (17,80,73), which are scaled-down relatives of the paper's
# N = 1404 and N = 1360 rows.  The list below 400 is therefore a superset of Beeson's, so
# clearing it settles his rows too.
